### ISSUE TITLE
Rails app deployed with Dokku, sometimes job processed twice

### ISSUE THREAD

**Issue by amorimlucas** [collectiveidea/delayed_job#1000]
So I have an rails app deployed with Dokku that works perfectly most days.

My app has 2 workers.

Every night I have a clock process that triggers a job. The job processes orders and sends me an email with an excel with order data. Most nights this works perfectly, but some nights the orders get processed fine, but the excel I get is blank. I also noticed that the Stripe payment of the orders is split into 2 payments those nights, when it should be just 1 payment (The 2 payments add up to the correct amount though, which is evidence that the job is getting picked up by both of my workers, right?).

How can I fix this? This bug has been a bane to my app. Thank.

**Comment by albus522** [comment]
No. That would sound like the job is running once but there is something weird with your processing. If it were running twice I would expect 2 full orders, not 2 partials.

**Comment by amorimlucas** [comment]
Hey @albus522, the job updates tables, so couldn't one worker job start processing and update the table, and the second worker job process the rest of it? Because most days my code works perfectly, so I can't see how it could be a problem with my processing.

**Comment by albus522** [comment]
How are you starting your 2 workers?

**Comment by amorimlucas** [comment]
I deploy with Dokku (which is pretty much Heroku), and during the deployment process it starts up two workers (defined in my Procfile and DOKKU_SCALE files).

**Comment by albus522** [comment]
With what command?

**Comment by amorimlucas** [comment]
git push dokku master
