### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gameroster-us** [collectiveidea/delayed_job#1001]
rails 4.2.1
ruby 2.2.1

gem 'pg'
gem 'delayed_job_active_record'

bundle install

rails generate delayed_job:active_record
rake db:migrate

@event.delay.send_mail

Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)

**Comment by albus522** [comment]
DJ has nothing to do with Redis. Also, that error is likely that your Redis service is not running.
