### ISSUE TITLE
Possibility to revise query?

### ISSUE THREAD

**Issue by Awatatah** [collectiveidea/delayed_job#1002]
Is there a way to exclude `ORDER BY`, `priority`, and `run_at` queries and on the delayed jobs queue? I have a large table of delayed jobs I need to work quickly so I need the worker to ignore `priority` and `run_at` and to just grab the first job `WHERE locked_at = NULL`, lock it and work it.

**Comment by albus522** [comment]
Not officially no. But it is ruby, you can do almost anything.
