### ISSUE TITLE
MySQL table wrong character set for utf8 by default

### ISSUE THREAD

**Issue by cdekker** [collectiveidea/delayed_job#1005]
The delayed_jobs table that is created has the following character set collation `latin1_swedish_ci`, which does not support the usual UTF8 strings that Rails generally handles.

Just ran into this issue when trying to schedule a delayed_job if one of the parameters contains utf8 characters in a string, leading to the following error: 

```
Mysql2::Error: Incorrect string value: '\xEF\x80\xA2---...' for column 'handler' at row 1: INSERT INTO `delayed_jobs`
```

I had to manually run this command on the MySQL database to change the collation and make it compatible with the rest of the tables in my Rails application:

```
ALTER TABLE delayed_jobs CONVERT TO CHARACTER SET utf8;
```

This will make sure the delayed_jobs table gets the correct collation `utf8_general_ci`

**Comment by albus522** [comment]
Closing stale
