### ISSUE TITLE
delayed_job gem on ruby script

### ISSUE THREAD

**Issue by mm580486** [collectiveidea/delayed_job#1006]
hi guys
i want use delayed_job gem on ruby script for manage my background job but i cant find anything about this !!!
                  ‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌
```
                   ↓
!!!----> WITHOUT RAILS <----!!!
                   ↑
```

**Comment by albus522** [comment]
Delayed Job does not specifically rely on Rails but we do rely on ActiveSupport. I know a number of people have done this without rails as we have had issue requests over the years resolving specific reliances on Rails internals that were not absolutely required, however it is not an officially supported or documented setup. I did a search and noticed a number of results for how people had set things up themselves, but most appear fairly old and may not be accurate anymore. I know it is possible but at this time we do not have the resources to support each framework.
