### ISSUE TITLE
delayed_job worker connection with database.

### ISSUE THREAD

**Issue by Nguyenanh** [collectiveidea/delayed_job#1007]
Hello. 
Im using Rails 5, Ruby 2.4 and pg database.
so, on production environment i just run 1 worker for delayed_job and 2 worker for unicorn, but when i check session connect to DB by pgadmin4, i saw have 4 session are connecting. Could you explain for me about that. I think if i run 3 worker then 3 session connecting to DB
![screen shot 2017-11-10 at 6 25 56 pm](https://user-images.githubusercontent.com/7424863/32656640-3cbc671e-c645-11e7-84b9-f46eb0281b69.png)
![screen shot 2017-11-10 at 6 35 34 pm](https://user-images.githubusercontent.com/7424863/32656832-fdb70190-c645-11e7-83f1-26f89055bf6a.png)

**Comment by albus522** [comment]
Rails has a connection pool. Any process can have multiple connections to the database up to the connection pool limit specified in your database config. If you don't specify a limit, I believe the Rails default is 5.
