### ISSUE TITLE
Does delayed job perfom all database updates after the job is completed?

### ISSUE THREAD

**Issue by jgoodall628** [collectiveidea/delayed_job#1009]
I am trying to set up a progress bar for a file import using this gem https://github.com/d4be4st/progress_job. I have set up the job correctly, but the progress does not get updated till the very end. The 'current' progress is never returned until the entire job is complete. It just jumps from 0 to 100 with nothing in between. I am wondering if this is caused by delayed job or this gem or possible something else?

**Comment by albus522** [comment]
I have no knowledge of that gem and given the very specific behavior I would start with the progress job gem.

**Comment by paneq** [comment]
@jgoodall628 are you processing your job in a transaction? https://www.postgresql.org/docs/9.1/static/transaction-iso.html The progress might not be visible to others until the transaction is committed.

**Comment by jgoodall628** [comment]
This was the issue. Thanks
