### ISSUE TITLE
FAILED (4 prior attempts) with ArgumentError: wrong number of arguments (given 0, expected 1+)

### ISSUE THREAD

**Issue by array42-zz** [collectiveidea/delayed_job#1010]
Environment: create new Rails 5 Project, add active record delayed job gem, configured to use delayed_job as active_job.queue_adapter. Generated a job to test delayed_job. Windows OS. Since fork() is not available, using the rake worker.

Strange things happen: I enqueue a job, then that job fails, fails, works. Or it just does never work.
It complains with:
FAILED (4 prior attempts) with ArgumentError: wrong number of arguments (given 0, expected 1+)
Attempts it until it reaches the limit.

But the job is created with one parameter and is called with one parameter.
Signature of perform:
def perform(my_parameter, *args)

The strange part is, that it completes the same job when it tries it again. Sometimes.

Just found https://stackoverflow.com/questions/37553033/rails-5-with-delayedjob-resulting-in-an-error and that refers to https://github.com/collectiveidea/delayed_job/issues/896 so I assume rails 5 is supported?

So at the moment it's like gambling to get a job to complete right away.

**Comment by array42** [comment]
More details for one scenario, looking at the delayed_jobs table:
1. a JobWrapper and a Job gets created. Two handler Lines exist.
2. the JobWrapper executes, the task actually completes, the perform action is executed.
3. the Job (the second handler line) stays, that handler will re-execute and will fail.

**Comment by array42** [comment]
I won't use that:
Delayed::Job.enqueue SomeJob.new(param), ...
I will use:
SomeJob.set(wait: 2.minutes).perform_later(param)

**Comment by array42** [comment]
Also, when I enqueue with Delayed::Job.enqueue and add a queue Name there or inside the Job, it does not add the prefix to the queue.
Example setting: config.active_job.queue_name_prefix = :delayed_job_queue # only honored by ActiveJob, not by DelayedJob

**Comment by bgmat** [comment]
Hi,

Have you managed to solve this issue?
I have a similar environment (Rails 5, windows) and I get `ArgumentError (wrong number of arguments (given 0, expected 1))` each time I run `SomeJob.perform_later(param)`

**Comment by arivero** [comment]
For the casual user... remember that delayed_job does not reload classes automagically during development, so you need to kill the workers.

**Comment by albus522** [comment]
Closing stale
