### ISSUE TITLE
New Rubygems release for Rubuy 2.5.0 compatibility?

### ISSUE THREAD

**Issue by brchristian** [collectiveidea/delayed_job#1011]
It looks like the latest rubygems release of `delayed_job` isn’t compatible with Ruby 2.5.0, although the current `master` is. Could we get a gem release to include the recent changes (most notably https://github.com/collectiveidea/delayed_job/commit/6cf9b0b2c256d20148172d074ca60e13d6439903) for Ruby 2.5.0 compatibility?

**Comment by albus522** [comment]
Released
