### ISSUE TITLE
script/delayed_job: No such file or directory

### ISSUE THREAD

**Issue by colinbrogan** [collectiveidea/delayed_job#1013]
Hi,
I am trying to run delayed_job on a VPS (Ubuntu 12). I am trying to use the daemon script/delayed_job to start the workers. I am getting the following:
`script/delayed_job: No such file or directory`

The below console response shows that I have both the "daemons" gem and the "delayed_job_active_record" gem. You can also see that I've run "rails generate delayed_job", which I am assuming is suppose to create this 'script/delayed_job' file, but you can see through the response that it is not.

Am I missing something here?
 

bundle update
Fetching git://github.com/rails/rails.git
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies......
Using rake 12.3.0
Using concurrent-ruby 1.0.5
Using i18n 0.9.1
Using minitest 5.10.3
Using thread_safe 0.3.6
Using tzinfo 1.2.4
Using activesupport 5.0.6 from git://github.com/rails/rails.git (at 5-0-stable@a02a8d7)
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.3.0
Using nokogiri 1.8.1
Using rails-dom-testing 2.0.3
Using crass 1.0.3
Using loofah 2.1.1
Using rails-html-sanitizer 1.0.3
Using actionview 5.0.6 from git://github.com/rails/rails.git (at 5-0-stable@a02a8d7)
Using rack 2.0.3
Using rack-test 0.6.3
Using actionpack 5.0.6 from git://github.com/rails/rails.git (at 5-0-stable@a02a8d7)
Using nio4r 2.2.0 (was 2.1.0)
Using websocket-extensions 0.1.3
Using websocket-driver 0.6.5
Using actioncable 5.0.6 from git://github.com/rails/rails.git (at 5-0-stable@a02a8d7)
Using globalid 0.4.1
Using activejob 5.0.6 from git://github.com/rails/rails.git (at 5-0-stable@a02a8d7)
Using mini_mime 1.0.0
Using mail 2.7.0
Using actionmailer 5.0.6 from git://github.com/rails/rails.git (at 5-0-stable@a02a8d7)
Using activemodel 5.0.6 from git://github.com/rails/rails.git (at 5-0-stable@a02a8d7)
Using arel 7.1.4
Using activerecord 5.0.6 from git://github.com/rails/rails.git (at 5-0-stable@a02a8d7)
Using public_suffix 3.0.1
Using addressable 2.5.2
Using addressabler 0.1.2
Using debug_inspector 0.0.3
Using binding_of_caller 0.7.3
Using bundler 1.16.1
Using byebug 9.1.0
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using coffee-script 2.4.1
Using method_source 0.9.0
Using thor 0.20.0
Using railties 5.0.6 from git://github.com/rails/rails.git (at 5-0-stable@a02a8d7)
Using coffee-rails 4.1.1
Using coinbase 4.1.0
Using daemons 1.2.6
Fetching delayed_job 4.1.4 (was 4.1.3)
Installing delayed_job 4.1.4 (was 4.1.3)
Using delayed_job_active_record 4.1.2
Using ffi 1.9.18
Using multi_xml 0.6.0
Using httparty 0.15.6
Using multi_json 1.12.2
Using jbuilder 2.7.0
Using jquery-rails 4.3.1
Using json 1.8.6
Using kraken_client 1.2.1
Using sprockets 3.7.1
Using sprockets-rails 3.2.1
Using rails 5.0.6 from git://github.com/rails/rails.git (at 5-0-stable@a02a8d7)
Using rb-fsevent 0.10.2
Using rb-inotify 0.9.10
Using rdoc 4.3.0
Using sass-listen 4.0.0
Fetching sass 3.5.4 (was 3.5.3)
Installing sass 3.5.4 (was 3.5.3)
Using tilt 2.0.8
Using sass-rails 5.0.7
Using sdoc 0.4.2
Using spring 2.0.2
Using sqlite3 1.3.13
Using turbolinks-source 5.0.3
Using turbolinks 5.0.1
Fetching uglifier 4.1.2 (was 4.0.1)
Installing uglifier 4.1.2 (was 4.0.1)
Using web-console 2.3.0
Bundle updated!
[ps452222]$ bundle exec rails generate delayed_job
Running via Spring preloader in process 30732
   identical  bin/delayed_job
       chmod  bin/delayed_job
[ps452222]$ script/delayed_job start
-bash: script/delayed_job: No such file or directory

**Comment by albus522** [comment]
That is because Rails replaced the script directory with bin in Rails 4. There is a note in the documentation but we haven't re-written all the docs to `bin/delayed_job`
