### ISSUE TITLE
Duplicate jobs being performed with different ID's but only called once

### ISSUE THREAD

**Issue by MichaelA59** [collectiveidea/delayed_job#1014]
I have a mailer that is a delayed job. It is only called once, but we are receiving the same email twice. The logs show that the mailer is called the first time, succeeds and is logged as `COMPLETED`, but then starts up again and repeats the process, succeeding a second time.

The 1st & 2nd mailers have different ID's with the second being +1 from the first. Any idea what would cause this to send twice?

**Comment by albus522** [comment]
They have different ids so it looks like you are accidentally creating 2 jobs doing the same thing.
