### ISSUE TITLE
Delayed_job doesn't release memory after jobs completed

### ISSUE THREAD

**Issue by mithesh109** [collectiveidea/delayed_job#1015]
Hello,

I have noticed that delayed_jobs consumes memory once it starts processing a job. After the job is completed, it doesn't release back the memory. I have to manually restart the Delayed_job to release the memory.

Server : Amazon Linux AMI release 2016.03
RAM : 8GB
ruby 2.2.4p230
rails 4.2.5
delayed_job 4.1.1
delayed_job_active_record 4.1.0

![delayed_job](https://user-images.githubusercontent.com/17758669/35039720-bebd5630-fba4-11e7-8265-a30dee511f1f.png)

**Comment by albus522** [comment]
That is not an issue with delayed job. That is a ruby thing. Biggest culprit is usually something you store somewhere that doesn't get cleared, for instance class variables. Gems that use compiled libraries can also have some high issues. To solve this conclusively you will need to lookup how to search for a memory leak in ruby. There are a number of tools available that can help and there really isn't a right tool for all cases.

**Comment by vi-huynh** [comment]
@albus522 @mithesh109  
I have  more 1000 jobs, execute by 3 worker.  
After each jobs completed, i see memory increase 100MB, and never stop. 
I ready have temporary solution. 
https://github.com/collectiveidea/delayed_job/wiki/How-to-release-memory-after-jobs-completed-%3F
