### ISSUE TITLE
How to check the delayed_job is running in rails console?

### ISSUE THREAD

**Issue by huangjun604** [collectiveidea/delayed_job#1018]
Hi team,

Thanks for providing the awesome gem, is there any way to check if the `delayed_job` is running or not?

I have a rails app with `delayed_job` deployed on heroku. The DJ is running on `worker` dyno. However, it stopped working yesterday. I checked the `worker`'s status by `heroku ps` and it's `up`. And I also went to the rails console to check the queue by `Delayed::Job.all` and found there are 112 jobs waiting but not executed. I also checked the logs, but I didn't find any useful information. The worker log just stopped printing yesterday. Finally, I restarted the `worker` dyno and it worked again.

Does there any way to check why the `delayed_job` was not working?

Cheers

**Comment by albus522** [comment]
Start with fishing through the logs.

**Comment by albus522** [comment]
Another possibility is certain interactions with network calls can bypass ruby's timeout library. Did any external service you use have a blip that threw things off?

**Comment by albus522** [comment]
Closing stale
