### ISSUE TITLE
Delayed_job run_at is delayed by 2 hours

### ISSUE THREAD

**Issue by IElgohary** [collectiveidea/delayed_job#1021]
The time is actually saved correctly in the database but the job is run 2 hours after the run_at

**Comment by albus522** [comment]
run_at is the earliest something will run, not the exact time it will run. If there are a lot of jobs in the queue they get processed in a specific priority order which may mean your jobs scheduled for a specific time doesn't run then.

**Comment by IElgohary** [comment]
Oh I actually fixed that but I forgot that I created an issue with it.
It was an issue with the timezone so I had to specify the timezone of Active records and that of rails.
Thanks for your help :)
