### ISSUE TITLE
Add case of job rescheduling to wiki? Or even new Guides section?

### ISSUE THREAD

**Issue by prog1dev** [collectiveidea/delayed_job#1027]
Is this worth to add code example how to reschedule a job(make a delayed job enqueue itself) to wiki [Common problems](https://github.com/collectiveidea/delayed_job/wiki/Common-problems) section or even create new `Guides` section with best approaches to common use cases.

I had this case when job should run event 3 mins to check state of resource on 3rd party API. At that time I could not come up with better approach then raising `RescheduleError` and setting up 3 minutes time in `reschedule_at` method.

And after some time I found [this question on SO](https://stackoverflow.com/questions/50027706/how-to-make-a-delayed-job-enqueue-itself) about same problem and solutions there are better then mine. 

So I wonder if wiki guide with code example considered as a best practice for that case would be useful for anyone.

**Comment by albus522** [comment]
Closing stale
