### ISSUE TITLE
Presence of emoji's in handler breaks delayed jobs

### ISSUE THREAD

**Issue by atainton** [collectiveidea/delayed_job#1030]
We have had this issue for a while now and up to now we have needed to sanitise out data but out sources of data are increasing and we cant sanitise everything.

If an emoji is present in the handler then no new worker will spawn to process the queue. 

We have to manually remove the emoji to fix this.

**Comment by albus522** [comment]
What is the actual error you are seeing?

**Comment by atainton** [comment]
@albus522 
`Mysql2::Error: Incorrect string value: '\xF0\x9F\x91\xA8\xE2\x80...' for column 'last_error' at row 1: UPDATE `delayed_jobs` SET `last_error` = 'Mysql2::Error: Incorrect string value: \'\\xF0\\x9F\\x91\\xA8\\xE2\\x80...\' for column \'job_title\' at row 1: INSERT INTO `people` (`first_name`, `last_name`, `telephone`, `country_code`, `email`, `highest_level_of_education`, `job_title`, `created_at`, `updated_at`) VALUES (\'scottexample \', \'scottexample\', \'+12\', \'us\', \'testing@gmail.com\', 2, \'CEO ��‍�� \', \'2018-07-11 04:27:58\', \'2018-07-11 04:27:58\')`

**Comment by albus522** [comment]
Mysql doesn't have real UTF-8 support by default. You have to enable utf8mb4 to support emoji which has other consequences. You will need to look up mysql utf8mb4 and see if making the required changes will work in your environment.
