### ISSUE TITLE
Lock on delayed job transaction

### ISSUE THREAD

**Issue by vishnurkrishnan** [collectiveidea/delayed_job#1035]
Recently i am getting  lock issue on delayed job transaction

LOG: duration: 2725.244 ms statement: COMMIT
app postgres.101981 - - [OLIVE] [8-1] sql_error_code = 00000 LOG: process 101981 acquired ShareLock on transaction 1335941729 after 4390.609 ms

app postgres.88061 - - [OLIVE] [7-1] sql_error_code = 00000 LOG: duration: 4852.300 ms statement: COMMIT

app postgres.101981 - - [OLIVE] [8-2] sql_error_code = 00000 CONTEXT: while locking tuple (204,6) in relation "delayed_jobs"

app postgres.101981 - - [OLIVE] [8-3] sql_error_code = 00000 STATEMENT: UPDATE "delayed_jobs" SET locked_at = '2018-06-20 10:42:39.939279', locked_by = 'host:5a38ca52-6863-494b-8a67-d33582140dcc pid:4' WHERE id IN (SELECT id FROM "delayed_jobs" WHERE ((run_at <= '2018-06-20 10:42:39.938333' AND (locked_at IS NULL OR locked_at < '2018-06-20 06:42:39.938371') OR locked_by = 'host:5a38ca52-6863-494b-8a67-d33582140dcc pid:4') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *

yes normally this will happen when multiple transactions try to update (or to select for update) on the same tuple at the same time. but why this is taking more time? is there anyway to reduce that

**Comment by albus522** [comment]
Closing stale
