### ISSUE TITLE
What is the method 'record_stat'?

### ISSUE THREAD

**Issue by JohnSmall** [collectiveidea/delayed_job#1037]
In the examples for hooks there are 4 hooks using the method `record_stat`. But there's no explanation about what `record_stat` is.

Are we expected to 'just know' that it's a nonce method and we can replace it with any method of our own, or is it a special undocumented method in Delayed::Job. 

If it is a nonce method maybe a better name would be `foo` just to make it obvious.

**Comment by shanecav84** [comment]
It's just an example. You should replace it with whatever you want.

**Comment by astupidnerd** [comment]
I also think that documenting this would be a good idea. I just spent more time than I want to admit googling what `record_stat` does.
