### ISSUE TITLE
Doesn't update to the new database table name prefix

### ISSUE THREAD

**Issue by guleed** [collectiveidea/delayed_job#1040]
I've changed the database table name prefix in my rails application globally for ActiveRecord

> ActiveRecord::Base.table_name_prefix = 'webapp.'

However the delayed_job gem is still using the old one. Even though after re-migrating a new table was generated with the name webapp.delayed_job, the gem is still using the old one.

Is there any way to force the gem to reset or to manually configure which table to use?

**Comment by albus522** [comment]
`Delayed::Job` is a standard ActiveRecord model, so you can use `table_name=` to change the table name. You can also rerun `Delayed::Job.set_delayed_job_table_name` to cause DJ to refresh the default table name with the new prefix after you update the prefix.
