### ISSUE TITLE
Jobs executing twice

### ISSUE THREAD

**Issue by nledb** [collectiveidea/delayed_job#1042]
Hi Guys,

In my set up I have two postgres databases, one in the EU and one in the US which are synchronized with BDR. Both these databases have delayed_job instances in their regions contacting it for jobs.

I am running into the issue that at some point (usually after about 30 minutes) the same job will get executed in both the US and the EU.

**EU Server**
Aug 17 13:28:50 EU rails[17861]: 2018-08-17T13:28:50+0000: [Worker(delayed_job.10 host:EU pid:17861)] Job Alert (id=2274366) RUNNING
Aug 17 13:28:51 EU rails[17861]: 2018-08-17T13:28:51+0000: [Worker(delayed_job.10 host:EU pid:17861)] Job Alert (id=2274366) COMPLETED after 0.3726
Aug 17 13:28:51 EU rails[17861]: 2018-08-17T13:28:51+0000: [Worker(delayed_job.10 host:EU pid:17861)] Job Alert (id=2274367) RUNNING
Aug 17 13:28:51 EU rails[17861]: 2018-08-17T13:28:51+0000: [Worker(delayed_job.10 host:EU pid:17861)] Job Alert (id=2274367) COMPLETED after 0.4841
Aug 17 13:28:51 EU rails[17861]: 2018-08-17T13:28:51+0000: [Worker(delayed_job.10 host:EU pid:17861)] 2 jobs processed at 2.2883 j/s, 0 failed

**US Server**
Aug 17 13:28:50 US rails[8326]: 2018-08-17T13:28:50+0000: [Worker(delayed_job.21 host:US pid:8326)] Job Alert (id=2274366) RUNNING
Aug 17 13:28:52 US rails[8326]: 2018-08-17T13:28:52+0000: [Worker(delayed_job.21 host:US pid:8326)] Job Alert (id=2274366) COMPLETED after 2.0828
Aug 17 13:28:52 US rails[8326]: 2018-08-17T13:28:52+0000: [Worker(delayed_job.21 host:US pid:8326)] 1 jobs processed at 0.4700 j/s, 0 failed

**Versions**
Rails: 5.2.0
Delayed_job: 4.1.5
Delayed_job_active_record: 4.1.3

Any ideas ?

Thanks!

**Comment by albus522** [comment]
My guess would be that BDR doesn't support the high performance single query locking DJ uses. In order to do so every SQL update would have a 100ms+ delay as each server would first have to tell the other to lock the record for update before updating and cross continental latency would become a real problem.

**Comment by albus522** [comment]
Closing stale
