### ISSUE TITLE
How to run a delayed job in multi-tenant rails app?

### ISSUE THREAD

**Issue by prathip111** [collectiveidea/delayed_job#1043]
How I will allow rake jobs:work to work for the multiple schema in both development and production environment. Thanks in advance.

**Comment by albus522** [comment]
That is not a setup delayed_job actively supports, but if you google around, people have done it.

**Comment by raja-muthukathan** [comment]
I am facing the same issue. if anyone helps me it's great

**Comment by raja-muthukathan** [comment]
> How I will allow rake jobs:work to work for the multiple schema in both development and production environment. Thanks in advance.

How can I solve the issue?
