### ISSUE TITLE
Question: Docker, rake tasks and the same /etc/hostname

### ISSUE THREAD

**Issue by jufemaiz** [collectiveidea/delayed_job#1045]
Hi guys,
we are currently scaling out in ECS docker containers for Delayed::Job workers. I've spent some time reviewing the options to allow us to explicitly set names using container IDs in addition to hostname and process ID. The main reason is that all our process IDs are invariably the same (1) and the hostname is explicitly set (e.g. domain-delayed-job-worker) for our logging solution (this may not be the norm).

What we saw happening in practice was that all workers essentially had the same identifier rather than a unique one. The only somewhat unique reference available in a container is the [container ID](https://docs.docker.com/engine/reference/commandline/ps/) itself and to acquire that you need to do some digging around the `/proc/self/cgroup` file.

To this end I've added a GIST that may be more pertinent as a README.md reference rather than implemented (although happy for that to be the case! I'd just recommend working out if kubernetes, azure et al do something different with their `/proc/self/cgroup` listing - [aws ecs uses '/ecs/task-arn/container-sha'](https://github.com/aws/amazon-ecs-agent/issues/1119), while regular docker containers uses '/docker/container-sha').

https://gist.github.com/jufemaiz/dc016c844038c9b979c8b2dea5c98286

This then enables the ability to run container based tasks and includes the container-sha in the name of the worker. 

Just wondering your throughts?

**Comment by albus522** [comment]
Closing stale
