### ISSUE TITLE
Timeout exception is not showing max_run_time properly

### ISSUE THREAD

**Issue by knagode** [collectiveidea/delayed_job#1049]
When we limit max execution time on single job via `def max_run_time; 2; end` method I would expect that exception would be raised with proper message.

At the moment we are getting error which includes info about default timeout. 

```
*Delayed::WorkerTimeout*: execution expired (Delayed::Worker.max_run_time is only 14400 seconds)
```

I would expect error which includes info about specific job:

```
*Delayed::WorkerTimeout*: execution expired (Delayed::Worker.max_run_time is only 2 seconds)
```

https://github.com/collectiveidea/delayed_job/blob/73bd1b50e719b336b70fcbb8dc4a37ec9b2f6f35/lib/delayed/exceptions.rb#L7

**Comment by albus522** [comment]
Due to how timeouts work, the error doesn't have access to anything but class level things. Which means, we do not have the ability to reference anything on the job instance.
