### ISSUE TITLE
new development commands: run-first, run-id

### ISSUE THREAD

**Issue by foonlyboy** [collectiveidea/delayed_job#1054]
Hi at collectiveidea,

I'd like to propose some new commands for the delayed_job script to help in debugging:
- run-first
- run-last
- run-id id

`RAILS_ENV=development script/delayed_job run-first`
This should pick the first job from the queue, work on it and then quit.

`RAILS_ENV=development script/delayed_job run-first`
This should pick the latest job enqueued from the queue, work on it and then quit.

`RAILS_ENV=development script/delayed_job run-id id`
This should pick the job with id from the queue, work on it and then quit.

**Comment by albus522** [comment]
Closing stale
