### ISSUE TITLE
feature: enhance to a batch job scheduler

### ISSUE THREAD

**Issue by foonlyboy** [collectiveidea/delayed_job#1059]
Hi at collectiveidea,

I'm using delayed_job with great success.
Today I enabled delayed_job:cron, seems to work quite well.

I'd like to discuss with yours if it would be feasible,
to extend delayed_job towards a more generic batch job engine.

One thing that comes to my mind,
I want to enqueue a job to run *only once* (or fail otherwise)
(we might need a new columns like :max_attempts)

I'd also like to add more interaction with the jobs.
There should be a shell interface to admin the jobs.

**Comment by albus522** [comment]
Closing stale
