### ISSUE TITLE
Deserialization is broken when using Psych.load_tags

### ISSUE THREAD

**Issue by lcrepet** [collectiveidea/delayed_job#1062]
Hi,

I had weird errors sometimes when a job tried to run, like:
_"Job failed to load: undefined method `allocate' for
"ActiveModel::AttributeSet":String."_
It was actually happening during the job handler deserialization, in the
method [Delayed::PsychExt::ToRuby#visit_Psych_Nodes_Mapping](https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/psych_ext.rb#L31):

`return revive(Psych.load_tags[object.tag], object) if Psych.load_tags[object.tag]`

The method `revive` tried to instantiate a class obtained from
Psych.load_tags hash. But this hash contains string; it seems like the method `revive`
should be called this way:

`return revive(resolve_class(Psych.load_tags[object.tag]), object) if Psych.load_tags[object.tag]`

You can compare with the implementation of [Psych::Visitors::ToRuby#visit_Psych_Node_Mapping](https://github.com/ruby/psych/blob/e01839af57df559b26f74e906062be6c692c89c8/lib/psych/visitors/to_ruby.rb#L160).

**Comment by albus522** [comment]
Were you deploying a rails upgrade? I vaguely recall running into something like this because the ActiveRecord models serialize and deserialize differently between different versions.

**Comment by albus522** [comment]
The fix is out in 4.1.6
