### ISSUE TITLE
How to terminated delayed_job?

### ISSUE THREAD

**Issue by GildedHonour** [collectiveidea/delayed_job#1065]
How to terminate it?

Not clear its queue -- terminate. 

Only via "kill -9 <pid>" ?

**Comment by albus522** [comment]
Delayed Job uses standard process management. A basic kill command will do the trick. So will ctrl-c for a foreground process. You should never be using `kill -9` for process management. `-9` is essentially force quit for misbehaving processes.

**Comment by GildedHonour** [comment]
On my server there's no one sitting at a desktop to do that trick by pressing Ctrl-c on the keyboard.

**Comment by GildedHonour** [comment]
It should be done automatically via a bash script. If not kill, what else?

**Comment by GildedHonour** [comment]
I'll use kill -2
