### ISSUE TITLE
Running multiple processes but staying in the foreground

### ISSUE THREAD

**Issue by drewB** [collectiveidea/delayed_job#1066]
When running in environments like heroku is it necessary to keep the process in the foreground.  If you only want to run a single process then you can accomplish this by just using `bundle exec script/delayed_job run` but doesn't help you if you want to run multiple processes.  `run` seems to ignore the `-n` option (which I think should include at least a warning).  Only method I could get to work was to use foreman to run multiple instances of `bundle exec script/delayed_job run` but that is pretty ugly and doesn't allow for quick changes to the number of processes through environment variables.  

Any thoughts on how to accomplish this?

**Comment by drewB** [comment]
I ended up using https://github.com/salsify/delayed_job_worker_pool which was better than a bash script but it hasn't had a commit in 2 years.  Seems like this is something that delayed_job should be able to handle.

**Comment by albus522** [comment]
Managing a set of running processes is not a simple task and is very environment specific. Even DJs use of the daemons gem to mostly handle this has had a lot of problems over the years and is probably one of the single greatest sources of issues. We know enough to know that is a maintenance nightmare we don't want to take on.

For heroku specifically, I have seen multiple buildpacks that will allow you to run multiple processes in a single dyno, I would recommend looking at one of those. Know that you will end up playing a memory management cat and mouse game with running multiple workers in one dyno. It can work, but it comes with built in issues.
