### ISSUE TITLE
deliver_later with ActionMailer not sending mail in production.

### ISSUE THREAD

**Issue by tasdendu** [collectiveidea/delayed_job#1068]
While executing the following code.
`EventMailer.notify_created(user.id, id).deliver_later`

The value get inserted correctly in the delayed job table. But the the job is never executed even though the delay job server is up.

Note: 
1. `EventMailer.notify_created(user.id, id).deliver_now` works perfectly fine.
2. Delay job with ActiveJob is also working fine.

Can any one please help me solve this issue.

**Comment by albus522** [comment]
Closing stale
