### ISSUE TITLE
Are delayed_jobs hooks designed to work with active_job ?

### ISSUE THREAD

**Issue by gs2589** [collectiveidea/delayed_job#1069]
It looks like it requires redefinition of a lot of the methods that are defined in active_jobs, causing collisions. For example, `#enqueue`

Further, it seems like there is no easy way to access the delayed_jobs data base columns from within an active_job, for example, in a job:
```
class AutoResolverJob < ApplicationJob
  queue_as :low_priority
  
  def perform(id)
    # do stuff
  end

end

```

How would I add the `#enqueue` hook  without redefining the ActiveJob#enqueue method AND
How would I access a custom DelayedJob db column to set it to a given value, for example id.

What I am trying to do is to  store a reference to the delayed business entity in the job as per 
https://www.sitepoint.com/delayed-jobs-best-practices/    ("Columns for your delayed entity")

**Comment by albus522** [comment]
ActiveJob uses a wrapper job that obscures the actual jobs from delayed job. At this point, there is no way to trigger what you want through ActiveJob, but that is an interesting idea for an improvement to ActiveJob's integration with DJ.
