### ISSUE TITLE
Encrypt delayed_jobs in the database

### ISSUE THREAD

**Issue by mashedkeyboard** [collectiveidea/delayed_job#1079]
For data security, it'd be great to have an option to encrypt the database's delayed_jobs at rest - perhaps using [attr_encrypted](https://github.com/attr-encrypted/attr_encrypted), which works really well for this sort of thing.

**Comment by nruth** [comment]
What data would that secure? Can't you put the sensitive data in encrypted storage instead of inside the job?

**Comment by mashedkeyboard** [comment]
Transient data that's part of an operation that takes a long time, but needs to be kept secure, in effect. Adding it into the database itself would be pointless, as it only needs to be kept for the duration of the job operation, and it adds an additional attack vector.

**Comment by albus522** [comment]
`Delayed::Job` is just an ActiveRecord model, you can do anything you want to as long as you don't mess with the fields we need to query by. `handler` is not one of these fields, so as long as `handler` and `handler=` work as before, DJ doesn't care what happens deeper down

**Comment by albus522** [comment]
Closing stale
