### ISSUE TITLE
migrating delayed_job handler from mysql to mysql2 gem

### ISSUE THREAD

**Issue by neils678** [collectiveidea/delayed_job#1082]
Hi, I have an existing app that uses Delayed Jobs to periodically update a Mysql DB. The current app uses mysql gem v 2.9.1. But this gem hasn't been updated in a long while, so I would like to migrate to mysql2 gem 0.4.10. But it looks like the serialised format of the delayed_job handler may be different between the 2 gems.

If I try to process a delay_job entry, created with the mysql gem, using the mysql2 gem I see the following error:

```
ERROR -- : 2019-03-15T10:11:04+0000: [Worker(delayed_job host:xxx pid:776)] Job Delayed::PerformableMethod (id=1) FAILED permanently with Delayed::DeserializationError: Job failed to load: undefined class/module ActiveRecord::ConnectionAdapters::MysqlAdapter::. Handler: 
```
If I create a new delayed_job with the same (msql2 based) app. it processes it correctly.

So it looks like I need to migrate the msql generated delay_job handlers somehow, when updating the app? Correct?

I'd be grateful of any pointers anyone can give me on how to do this. Or point me in the right direction if my analysis is wrong.

**Comment by ERRECabrera** [comment]
@neils678, I made a pull request to help with this problem.
Meanwhile you can use this lines
```ruby
# config/initializers/delayed_job.rb

# Monkey patch to use old class references
module Psych

  class << self; attr_accessor :old_class_references end
  @old_class_references = {}

  class ClassLoader
    private

    def find klassname
      klassname = ::Psych.old_class_references[klassname] || klassname
      @cache[klassname] ||= resolve(klassname)
    end
  end

  module Visitors
    class ToRuby < Psych::Visitors::Visitor
      def revive klass, node
        if klass.is_a? String
          klassname = ::Psych.old_class_references[klass] || klass
          klass = Kernel.const_get(klassname) rescue klassname
        end
        s = register(node, klass.allocate)
        init_with(s, revive_hash({}, node), node)
      end
    end
  end
end

# Add all old dependencies (hash keys) pointing to new references (hash values)
Psych.old_class_references = {
  'ActiveRecord::AttributeSet' => 'ActiveModel::AttributeSet'
  # ...
}
```

**Comment by albus522** [comment]
Closing stale
