### ISSUE TITLE
undefined class/module Delayed::PerformableMailer

### ISSUE THREAD

**Issue by TanookiMario** [collectiveidea/delayed_job#1094]
with the upgrade from 4.1.5 to 4.1.6 it seems like delayed_job can no longer find the PerformableMailer.

the error we are getting is:

```
Job Delayed::PerformableMailer (id=59) FAILED permanently with Delayed::DeserializationError: 
Job failed to load: undefined class/module Delayed::PerformableMailer. Handler: "--- !ruby/object:Delayed::PerformableMailer
```

we are using `ActionMailer::Base`. It works fine in version 4.1.5. Could it be a problem with how we are initializing delayed_jobs and/or ActionMailer?

**Comment by albus522** [comment]
Just pushed a new version that should fix your issue. I forgot rails doesn't eager load rake tasks, so in the right set of conditions the worker can kick off without ever triggering ActionMailer to load within rails, which is the trigger our updated loading code was relying on to load Delayed::PerformableMailer.

**Comment by TanookiMario** [comment]
thank you!
