### ISSUE TITLE
Uninstall delayed_job

### ISSUE THREAD

**Issue by vuvanquy1998** [collectiveidea/delayed_job#1096]
How to unintall delayed_job in my app

**Comment by gomesac** [comment]
Hi @vuvanquy1998, this seems not to be related to problems/issues with delayed job but just a general question for a how-to?

If you already migrated delayed job in a SQL db, drop the table with a new migration. Remove in Gemfile if present and update it. That should be all you need to uninstall it.

**Comment by kaioramos** [comment]
Hi, here are the steps that i take to remove DelayedJob Gem:

Rollback migration, in my case: rails db:rollback STEP=1
Remove the gem from Gemfile
Delete the migration for delayed_jobs
Remove the configuration on application_controller
Delete file delayed_job_config
Delete table delayed_jobs, eg.: ActiveRecord::Migration.drop_table(:delayed_jobs)

Hope it helps somebody.
