### ISSUE TITLE
Delayed job not working in background while in production

### ISSUE THREAD

**Issue by amit-mhetre** [collectiveidea/delayed_job#1097]
When we start delayed job in background with below commant, it shows that delayed_job process has started.

`RAILS_ENV=production bin/delayed_job start`

If we see the logs file `log/delayed_job.log` it also says `Starting job worker` and doesn;t executes the job.

But when I try to execute delayed job in foregqound with `RAILS_ENV=production rake jobs:work` then it properly executes the all pending jobs.

Is anyone familiar with this kind of scenario?

Note: When I ran same command as `RAILS_ENV=production bin/delayed_job start --exit-on-complete` it says `No more jobs available. Exiting`

I am using,
Ruby 2.3.1
Rails 4.2.7
delayed_job (4.1.5)
    activesupport (>= 3.0, < 5.3)
delayed_job_active_record (4.1.3)
    activerecord (>= 3.0, < 5.3)
    delayed_job (>= 3.0, < 5)

**Comment by amamrenko** [comment]
@amit-mhetre Did you solve this issue?

**Comment by shashank-saxena2k9** [comment]
i am also facing the same issue. Did you solved it ?

**Comment by albus522** [comment]
Closing stale
