### ISSUE TITLE
Delayed::Worker.delay_jobs = false with .deliver_later in Rails 6

### ISSUE THREAD

**Issue by knagode** [collectiveidea/delayed_job#1102]
In Rails 5 I used to have the following setting:  
```
Delayed::Worker.delay_jobs = false
config.active_job.queue_adapter = :inline
```

When I was running Mailer.send(...).deliver_later - emails were sent as expected. 

This is not true after I upgraded to Rails 6. After calling `.deliver_later` Nothing is in `ActionMailer::Base.deliveries`

How to solve this properly? I somehow need an ability to perform delayed jobs inline for the sake of testing.

**Comment by albus522** [comment]
DJ only has any interaction with deliver_later if `config.active_job.queue_adapter = :delayed_job` is set. My guess would be you have something changing `config.active_job.queue_adapter = :inline` that you don't expect.

**Comment by knagode** [comment]
Thanks @albus522. Yes I can confirm that this has nothing to do with DJ. Thanks for the hint but reading `Rails.application.config.active_job.queue_adapter` just before using `.deliver_later` shows that I am using `inline` adapter. Will research further. Thanks for putting me on the right track!
