### ISSUE TITLE
run command doesn't support multiple pool arguments

### ISSUE THREAD

**Issue by ysmood** [collectiveidea/delayed_job#1106]
The ones after the first one will be ignored.

Such as `bin/delayed_job run --pool "a" --pool "b"`, the `b` will be ignored.

**Comment by albus522** [comment]
Run the help command again and take a closer look at the pool argument. It takes a comma separated list.

**Comment by ysmood** [comment]
@albus522 But I want `a` and `b` to run in different pools. Have you ever tried my command?

**Comment by albus522** [comment]
`run` can only ever run one process. Run is highly limited and usually not what you want.

**Comment by ysmood** [comment]
@albus522 but the doc says run is the same as the start, there no doc to say it's different from the start. I think we should either fix the bug or fix the doc.

**Comment by ysmood** [comment]
If run `delayed_job` without any argument, it will print out the doc:

```
run          run the application in the foreground (same as start -t)
```

Which is not true, it doesn't support multiple pools. I think this is pretty confusing.

**Comment by ysmood** [comment]
> `run` can only ever run one process. 

By saying this you mean even I use something like this `run --pool "a:2"` it will only start one process?

**Comment by albus522** [comment]
That message is coming from the daemons gem https://github.com/thuehlinger/daemons/blob/bf0ca25aa9ead5b451fbb9a111ff73f9bc5dd942/lib/daemons/cmdline.rb#L106-L112 and isn't really true. It is only true for the most basic single process case.
