### ISSUE TITLE
Any Hook throws "wrong number of arguments (given 1, expected 0)"

### ISSUE THREAD

**Issue by Awatatah** [collectiveidea/delayed_job#1107]
Hi, when ever I use a hook
```
def success(job)
    # doesn't matter what is here
end
```

when the job runs it throws

> [Worker(host:my.com pid:21758)] Job HttpRequest (id=20) (queue=http_request) FAILED (1 prior attempts) with ArgumentError: wrong number of arguments (given 1, expected 0)

If I exclude the hook, the job runs fine and completes.
Any Ideas?

`delayed_job (4.1.8)`
`delayed_job_active_record (4.1.4)`
`rails 5.2`
`ruby 2.6.3`

This is how I queue the job:
`Delayed::Job.enqueue HttpRequest.new(uri, method, headers, basic_auth, data, retry_count), run_at: run_at, queue: "http_request"`

This is my job
```
class HttpRequest < Struct.new(:endpoint, :method, :headers, :basic_auth, :data, :retry_count)
  include HTTParty

  def perform
    if method == "POST"
      resp = HTTParty.post(
        endpoint,
        body: data.to_json,
        headers: headers,
        basic_auth: basic_auth,
      )
      handle_response(resp)
    elsif method == "PUT"
      resp = HTTParty.put(
        endpoint,
        body: data.to_json,
        headers: headers,
        basic_auth: basic_auth,
      )
      handle_response(resp)
    end
  end

  def max_attempts
    retry_count
  end

  def success(job)
    # doesn't matter what is here
  end

  private

  def handle_response(resp, opts = {})
    case resp.code
    when 200, 201
      return
    when 401
      raise ApiError::Unauthorized
    when 406
      raise ApiError::RecordInvalid
    else
      raise StandardError, resp
    end
  end
end
```

**Comment by albus522** [comment]
Something outside the information listed above is messing with the job object, methods, or trying to intercept all hooks. Possibly a system monitoring/error reporting gem.

This is what is running the hook https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/backend/base.rb#L101 which detects what arguments the method supports and only gives it what it can use.

If you don't need the `job` argument, a work around to try and sidestep what ever is interfering here would be to drop the `job` argument as the hook call will automatically adjust.

**Comment by albus522** [comment]
It could be the `include HTTParty` which isn't needed there, but I didn't see anything obvious from httparty that would interfere in this fashion.

**Comment by Awatatah** [comment]
I tried dropping `(job)` argument but I still get the error. This is my gem file
```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.3'
gem 'pg'
gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'bootsnap', '>= 1.1.0', require: false
# Dependencies
gem 'delayed_job_active_record'
gem 'activeadmin'
gem 'arctic_admin'
gem 'httparty'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry'
  gem 'dotenv-rails'
  gem 'rubocop'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by Awatatah** [comment]
I even tried reducing it to 
```
class HttpRequest < Struct.new(:endpoint, :method, :headers, :basic_auth, :data, :retry_count)
  def perform
    puts "hello there"
  end

  def max_attempts
    retry_count
  end

  def success
    puts "hello to you too"
  end

  private
end
```
still same error

**Comment by albus522** [comment]
Oh. I missed the obvious one. You are accidentally overriding the ruby method [`method`](https://ruby-doc.org/core-2.6.3/Object.html#method-i-method) by using it as part of your `Struct`. So DJ can't get the method for any of the callbacks

**Comment by Awatatah** [comment]
You are right... This should be documented to beware of what you are using in `Struct` 💯 

Thanks a lot! Resolved my issue
