### ISSUE TITLE
`raise_signal_exceptions` setting per job

### ISSUE THREAD

**Issue by arifkalayci** [collectiveidea/delayed_job#1116]
Is there a way define different `raise_signal_exceptions` per job? We find setting `raise_signal_exceptions = :term` very useful since we have long running jobs and they are subject to daily restarts on Heroku. But at the same time we have short jobs and it's a nightmare to handle the signal exception in each one of them separately. It's easier to just let them finish on their own. I see this setting is currently defined on the class level: https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/worker.rb#L61.

**Comment by albus522** [comment]
With the way signal exceptions work, DJ does not have a good way to tell what job is running where the exception gets raised from.

**Comment by albus522** [comment]
Closing stale
