### ISSUE TITLE
Updating from 4.1.4 to 4.1.5 might break rails initializers 

### ISSUE THREAD

**Issue by jlahtinen** [collectiveidea/delayed_job#1131]
Updating  delayed_job_active_record from 4.1.4 to 4.1.5 breaks rails initializers with code `Delayed::Jobs` with `NameError: uninitialized constant Delayed::Job`

**Comment by jlahtinen** [comment]
Adding `Delayed::Worker.backend = :active_record` before `Delayed::Jobs` "fixes" NameError.

**Comment by jlahtinen** [comment]
This issue maybe should be reported in delayed_job_active_record repo?

**Comment by albus522** [comment]
https://github.com/collectiveidea/delayed_job_active_record/issues/185

**Comment by jlahtinen** [comment]
following collectiveidea/delayed_job_active_record#185
