### ISSUE TITLE
How can I restart the jobs stuck in delayed job in postgres

### ISSUE THREAD

**Issue by Chandananimmu** [collectiveidea/delayed_job#1150]
@albus522 I'm using delayed job 4.1.9 , delayed_job_active_record 4.1.6 , when I try to send 10,000 emails via delayed job, it get stucks and the delayed job stops working, job will be in postgres, could you please help me to resolve this.

**Comment by pgib** [comment]
+1 literally experiencing the exact same thing

**Comment by albus522** [comment]
Closing stale
