### ISSUE TITLE
Using cached code

### ISSUE THREAD

**Issue by nomasprime** [collectiveidea/delayed_job#1151]
Unfortunately when running with Rails in production Delayed Job insists on using old, presumably cached, code.

Surprisingly, after searching the issue to death, there doesn't seem to be any clear info on how to deploy this gem in production.

**Comment by nomasprime** [comment]
Is `Rails.cache.clear` the way to deploy? Seems odd that it's not mentioned in readme if it is.

**Comment by danielmorrison** [comment]
@nomasprime what makes you think it is using old code? It sounds like maybe you're not restarting the workers after a deploy. 

See the Restarting docs: https://github.com/collectiveidea/delayed_job#restarting-delayed_job

**Comment by nomasprime** [comment]
Hi @danielmorrison I've restarted many times and still the same result, spent the whole day trying to debug. Only `Rails.cache.clear` seems to fix it.

I'm starting to wonder if relating to Docker build process.

**Comment by nomasprime** [comment]
Just ran `Rails.cache.clear` on development env and didn't fix it this time. No idea what's going on with this.

**Comment by uurcank** [comment]
@nomasprime  i am experiencing the same issue

**Comment by albus522** [comment]
There are usually 2 possible causes of this
1. An orphaned worker process somewhere still running the old code
2. A restart procedure that ends up carrying forward environment details especially all the hidden environment variables Bundler injects into running ruby processes.
