### ISSUE TITLE
Stops performing jobs after few days

### ISSUE THREAD

**Issue by owen2345** [collectiveidea/delayed_job#1154]
Hi,
Delayed_job stops performing background jobs after 3-4 days even if the system process looks normal.
### Analysis:
- system process looks running (normal)    
`ps ax` ==> `14 ?        Rl   33255:19 delayed_job`
- review jobs (are not performed)    
`Delayed::Job.count` ==> 1
`Delayed::Job.count` ==> 1 (still not processed after 1 hour)
- To have working again, I need to kill the pod (restart system)

### System
Hosting: Kubernetes
OS: Debian GNU/Linux 9
Ruby: 2.6
Rails: 6.0.2

**Comment by amamrenko** [comment]
> Hi, Delayed_job stops performing background jobs after 3-4 days even if the system process looks normal.
> 
> ### Analysis:
> * system process looks running (normal)
>   `ps ax` ==> `14 ?        Rl   33255:19 delayed_job`
> * review jobs (are not performed)
>   `Delayed::Job.count` ==> 1
>   `Delayed::Job.count` ==> 1 (still not processed after 1 hour)
> * To have working again, I need to kill the pod (restart system)
> 
> ### System
> Hosting: Kubernetes OS: Debian GNU/Linux 9 Ruby: 2.6 Rails: 6.0.2

I'm experiencing totally the same situation MacOS. Ruby 3.0.2. On 2.7.5 everything works well. I figured out that it's related to daemons gem.

**Comment by albus522** [comment]
Closing stale
