### ISSUE TITLE
DelayedJob kube containers not able to handle SIGQUITs and terminate abruptly

### ISSUE THREAD

**Issue by kiransajeev** [collectiveidea/delayed_job#1178]
We need mechanism for delayed_job to respond to SIGQUIT the same way it currently responds to SIGTERM due to disagreements between the rails and nginx about which should be triggering graceful shutdowns.

As of now delayed job containers terminate abruptly on SIGQUIT leaving jobs in a half done state.

**Comment by albus522** [comment]
You'll need to setup a trap similar to https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/worker.rb#L158-L168
