### ISSUE TITLE
Delayed Job records are getting duplicated in production rails app

### ISSUE THREAD

**Issue by seenivasang123** [collectiveidea/delayed_job#1199]
We are using delayed job to enqueue the background jobs in our rails application with (rails 5.2.5, ruby 2.6.3). We hosted application through Cloud 66 in this at the time of worker server down (delayed job process server) due to DeadLock and already queued delayed job record are getting duplicated. Based on the delayed job [documentation](https://github.com/collectiveidea/delayed_job) there is no possibility for record duplication. Please share some possibilities for this type of issue.

Example,

Main job with handler like, ( "--- !ruby/object:Delayed::PerformableMethod\nobject: !ruby/class 'SendNotificationJob'\nmethod_name: :perform_now\nargs:\n- 11111\n ") 

After server down duplicated jobs (around 1000 jobs) created with above same handler details and time.

**Comment by albus522** [comment]
There is nothing within DJ that creates jobs. Jobs are entirely created by your application.
