### ISSUE TITLE
How to use delayed_job with decidim ? [ Question ]

### ISSUE THREAD

**Issue by Jonathan1018** [collectiveidea/delayed_job#1207]
Hello

I try to use delayed_job as ActiveJob for decidim to send mail as indicated in the decidim official documentation:
https://docs.decidim.org/en/develop/services/activejob

But it doesn't work, delayed_job generate the email but don't send it

Could you please help me ?

Have a nice day
Jonathan

**Comment by Jonathan1018** [comment]
[log.txt](https://github.com/collectiveidea/delayed_job/files/14670608/log.txt)

You will find the log file in attachment

**Comment by albus522** [comment]
Your logs indicated the message was sent, the issue is not within DJ
