### ISSUE TITLE
Delayed::DeserializationError in rails 3

### ISSUE THREAD

**Issue by romaluca** [collectiveidea/delayed_job#183]
Hi i'm using delayed job gem for my site. In rails 2.3.8 i had no problems, but when i pass to rails 3 the process starts but in the delayed_jobs table of db i receive this error:

{Delayed::DeserializationError
/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/serialization/active_record.rb:7:in yaml_new'\n/accounts/lromagnoli/lib/ruby/1.8/yaml.rb:133:intransfer'\n/accounts/lromagnoli/lib/ruby/1.8/yaml.rb:133:in node_import'\n/accounts/lromagnoli/lib/ruby/1.8/yaml.rb:133:inload'\n/accounts/lromagnoli/lib/ruby/1.8/yaml.rb:133:in load'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/backend/base.rb:75:inpayload_object'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/backend/base.rb:83:in invoke_job'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/worker.rb:119:inrun'\n/accounts/lromagnoli/lib/ruby/1.8/timeout.rb:62:in timeout'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/worker.rb:119:inrun'\n/accounts/lromagnoli/lib/ruby/1.8/benchmark.rb:308:in realtime'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/worker.rb:118:inrun'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/worker.rb:176:in reserve_and_run_one_job'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/worker.rb:103:inwork_off'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/worker.rb:102:in times'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/worker.rb:102:inwork_off'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/worker.rb:77:in start'\n/accounts/lromagnoli/lib/ruby/1.8/benchmark.rb:308:inrealtime'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/worker.rb:76:in start'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/worker.rb:73:inloop'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/worker.rb:73:in start'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/command.rb:100:inrun'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/command.rb:79:in run_process'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/daemons-1.1.0/lib/daemons/application.rb:250:incall'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/daemons-1.1.0/lib/daemons/application.rb:250:in start_proc'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/daemons-1.1.0/lib/daemons/daemonize.rb:199:incall'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/daemons-1.1.0/lib/daemons/daemonize.rb:199:in call_as_daemon'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/daemons-1.1.0/lib/daemons/application.rb:254:instart_proc'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/daemons-1.1.0/lib/daemons/application.rb:294:in start'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/daemons-1.1.0/lib/daemons/controller.rb:70:inrun'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/daemons-1.1.0/lib/daemons.rb:193:in run_proc'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/daemons-1.1.0/lib/daemons/cmdline.rb:112:incall'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/daemons-1.1.0/lib/daemons/cmdline.rb:112:in catch_exceptions'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/daemons-1.1.0/lib/daemons.rb:192:inrun_proc'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/command.rb:78:in run_process'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/command.rb:72:indaemonize'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/command.rb:70:in times'\n/accounts/lromagnoli/lib/ruby/gems/1.8/gems/delayed_job-2.1.2/lib/delayed/command.rb:70:indaemonize'\n/accounts/lromagnoli/www/nerto/script/delayed_job:5

How can i fix it?

thanks

**Comment by knagode** [comment]
We are having same isssue with Octopus gem
