### ISSUE TITLE
using DelayedJob results in multiple email Amazon SES emails

### ISSUE THREAD

**Issue by workingBen** [collectiveidea/delayed_job#260]
I'm using delayed_job to send emails with the Hominid Amazon SES gem.  When I do not use delayed job to send my emails, a single copy of each email (correctly) is delivered.  When I delay the email with delayed job, every email gets duplicated.

I have a 'puts' statement in the caller method and it only ever gets printed once:

```
UserMailer.delay.new_user_activation(email_to_mail, activation_url, first_name, school_name)
puts "\n\n\n\n\nSENDING ACTIVATION INSTRUCTIONS\n\n\n\n\n"
```

I have a 'puts' statement in the callee method and it also only ever gets printed once:

```
mail(to: email, from: "\"User Activations\" <info@example.com>", subject: "Hi #{first_name}! Please Activate your User Account.").deliver
puts "\n\n\n\n\n\nnew_user_activation\n\n\n\n\n"
```

My output from the worker I'm running shows that only one dj is added, and successfully processed:

```
[Worker(host:bp.local pid:34672)] Class#new_user_activation completed after 2.1800
[Worker(host:bp.local pid:34672)] 1 jobs processed at 0.4474 j/s, 0 failed ...
```

Despite all this (which appears that I'm only sending one email), two emails are sent.  When I use the exact same code sans the 'delay' call, only one email is delivered.

I've checked with Amazon SES and everything is working fine on their end.  I've done tons of digging and found delayed job is the only variant between single and duplicate email deliveries.

Any help would be great.
-Ben

**Comment by matheus-caldeira** [comment]
I had the same problem as he! This section in the Readme not working with SES.

> You may also wish to consider using [Active Job with Action Mailer](https://edgeguides.rubyonrails.org/active_job_basics.html#action-mailer) which provides convenient `.deliver_later` syntax that forwards to Delayed Job under-the-hood.
```
ruby '2.7.1'

gem 'rails', '~> 6.0.3.6'
gem 'delayed_job', '4.1.10'
gem 'delayed_job_active_record', '4.1.7'
gem 'aws-sdk-s3', '~> 1'
gem 'aws-sdk-rails'
```
