### ISSUE TITLE
Multiple delayed_job processes for the same environment.

### ISSUE THREAD

**Issue by heaven** [collectiveidea/delayed_job#341]
Since delayed job support named queues I thought I can run different processes to work with different queues, like that:

```
run "cd #{current_path} && RAILS_ENV=#{rails_env} script/delayed_job --queue=rss_import start"
run "cd #{current_path} && RAILS_ENV=#{rails_env} script/delayed_job --queue=profiles_dump start"
run "cd #{current_path} && RAILS_ENV=#{rails_env} script/delayed_job --queue=lists_export start"
```

But I got this error when trying to launch 

```
ERROR: there is already one or more instance(s) of the program running
```

How to use these queues?

**Comment by hoprocker** [comment]
I'm still seeing this -- launching single-instances of delayed_job with multiple queues in the same environment seems to fail. Even using the ```-p``` prefixing flag seems to fail; the only way to do this seems to be to use the ```-n``` flag to trick the delayed job worker into launching differently-named processes.

The documentation has a clear example of this working, so I'm confused why this wouldn't work:

```
RAILS_ENV=production script/delayed_job --queue=queue1 start
RAILS_ENV=production script/delayed_job --queue=queue2 start
```

This results in the ```already one or more instance(s)``` error. I'm using DJ 4.1.3 on Ubuntu 16 with Rails 4 and Ruby 2.1.2.

**Comment by albus522** [comment]
https://github.com/collectiveidea/delayed_job#running-jobs has multiple examples for starting up workers

**Comment by hoprocker** [comment]
@albus522 Right, I see that -- my example was motivated by that. I'm doing the Rails 4 equivalent with bin/delayed_job, and here's my output:

```
> RAILS_ENV=production rvm 2.1.2 do bundle exec ./bin/delayed_job --queue=test1 start
delayed_job: process with pid 18292 started.
> RAILS_ENV=production rvm 2.1.2 do bundle exec ./bin/delayed_job --queue=test2 start
ERROR: there is already one or more instance(s) of the program running
```
I can get this to *sort* of work with the ```--pool``` option, but even then, if a process w/ the same name is already running, DJ fails:

```
> RAILS_ENV=production rvm 2.1.2 do bundle exec ./bin/delayed_job --pool=test1 start
delayed_job.0: process with pid 19446 started.
> ps aux | grep delayed_job
me  19446  7.7  3.5 338668 138132 ?       Sl   14:21   0:00 delayed_job.0
> RAILS_ENV=production rvm 2.1.2 do bundle exec ./bin/delayed_job --pool=test2 start
ERROR: there is already one or more instance(s) of the program running
> RAILS_ENV=production rvm 2.1.2 do bundle exec ./bin/delayed_job --pool=test1 --pool=test2 start
ERROR: there is already one or more instance(s) of the program running
delayed_job.1: process with pid 20165 started.
> ps aux | grep delayed_job
me  19446  1.4  3.6 339548 139016 ?       Sl   14:21   0:02 delayed_job.0
me  20165  1.7  3.5 338712 138348 ?       Sl   14:22   0:00 delayed_job.1
```
So I get that delayed_job just manages processes by the suffix of the process name, regardless of which queue the process is looking at, what the prefix is set to, the argument passed to ```--pool```, etc. Ie, this doesn't work:
```
RAILS_ENV=production ./bin/delayed_job -n 1 start
RAILS_ENV=production ./bin/delayed_job stop
```
The only way I could actually get this to work was to use multiple ```--pool``` arguments at once; but, once again, this seems to manage processes using suffix-based namespacing. Ie, this works:
```
RAILS_ENV=production ./bin/delayed_job --pool=test1 --pool=test2:9 start
RAILS_ENV=production ./bin/delayed_job -n 10 stop
```
I guess this is just how delayed_job works, and that's fine, but if that's the case, the README should be a bit more explicit about it, and the example including multiple ```--queue``` commands in a row is quite confusing.
