### ISSUE TITLE
SystemStackError, stack level too deep

### ISSUE THREAD

**Issue by sonereker** [collectiveidea/delayed_job#349]
With latest RVM, Ruby 1.9.2, delayed_job_active_record (0.3.2), Rails 3.2.0, pow (or webrick/thin);

I get "stack level too deep" error with notifier.

```
Notifier.delay(queue: "invitation").invitation(email, name)
```

Any suggestions?

**Comment by Fire-Dragon-DoL** [comment]
This should be written in bold:

**If you have an #enqueue method in your job model, you'll get this error**
