### ISSUE TITLE
max_attempts reached, failed_at remains nil

### ISSUE THREAD

**Issue by resistorsoftware** [collectiveidea/delayed_job#422]
Hi,

delayed_job (3.0.1)

I set the max_attempts to 2 on a job. I raise an error in the perform, trap it with a hook, and then watch what happens. I check my Delayed Job table, and sure enough, I get 2 attempts. I also get 2 failure exceptions recorded by Airbrake, so all is well. 

Now, I want to clean out these kinds of failed jobs, and the documentation states the failed_at timestamp should be set non-nil? once the max attempts are reached. I am seeing this attribute remain set to nil. 

Is that the expected behaviour? I am curious becuase while it is nice to know jobs failed, I also want to remove the ones that have based on some reliable criteria and I guess I misinterpreted the docs on the failed_at timestamp... any thoughts?

**Comment by pjmartorell** [comment]
I had the same issue with `ActiveJob` + `DelayedJob`. My issue was having `ActiveJob` with the default number of attempts (5 attempts) and on the other hand having `DelayedJob` with the default `max_attempts` (25 attempts), so it was not consistent. Setting `Delayed::Worker.max_attempts = 5` solved the issue and now `failed_at` is being set properly.
