### ISSUE TITLE
Crash after finishing job

### ISSUE THREAD

**Issue by satb** [collectiveidea/delayed_job#473]
$RAILS_ENV=development script/delayed_job status
delayed_job: running [pid 53594]

My delayed_job_config.rb

Delayed::Worker.destroy_failed_jobs = false
Delayed::Worker.sleep_delay = 15
Delayed::Worker.max_attempts = 3
Delayed::Worker.delay_jobs = !Rails.env.test?
Delayed::Worker.logger = Rails.logger

In my UserMailer class

def reset_password_email(user)
    @user = user
    @url  = "http://localhost:3000/password_resets/#{user.reset_password_token}/edit"
    mail(:to => user.email, :subject => "Your password has been reset")
  end

Then, trigger the reset_password_email using the controller (using sorcery gem)....everything works (including getting the email), then

$RAILS_ENV=development script/delayed_job status
delayed_job: no instances running

In the log file

 Class#send failed with ActiveRecord::StatementInvalid: PG::Error: : BEGIN - 0 failed attempts
   (0.1ms)  BEGIN
PG::Error: connection not open
: BEGIN
  SQL (0.1ms)  UPDATE "delayed_jobs" SET locked_by = null, locked_at = null WHERE (locked_by = 'delayed_job host:nd5rta.local pid:53648')
PG::Error: connection not open
: UPDATE "delayed_jobs" SET locked_by = null, locked_at = null WHERE (locked_by = 'delayed_job host:nd5rta.local pid:53648')
PG::Error: connection not open
: UPDATE "delayed_jobs" SET locked_by = null, locked_at = null WHERE (locked_by = 'delayed_job host:nd5rta.local pid:53648')

Any ideas? 

Using rails 3.2.11, ruby 1.9.3-p327 and postgres 9.2.1

Update: Surprisingly, happening only on my Mac. If I deploy to production, there is no problem. So weird.

**Comment by mishra-rajat** [comment]
https://stackoverflow.com/questions/54213316/delayed-job-not-able-to-connect-to-pg
