### ISSUE TITLE
0.4.0 / Unicorn Delayed Jobs logs

### ISSUE THREAD

**Issue by yongfook** [collectiveidea/delayed_job#477]
I updated my Rails according to this patch:
http://weblog.rubyonrails.org/2013/2/11/SEC-ANN-Rails-3-2-12-3-1-11-and-2-3-17-have-been-released/

and Delayed Job was updated to 0.4.0 at the same time.

I'm running Unicorn.

When I run my app now, Delayed Job seems to be spitting out much more to the logs. Is this expected behaviour?

> 11:40:37 worker.1 |   SQL (0.4ms)  UPDATE "delayed_jobs" SET "locked_at" = '2013-02-12 03:40:27.849168', "locked_by" = 'host:my-imac.local pid:13313' WHERE "delayed_jobs"."id" IN (SELECT id FROM "delayed_jobs" WHERE ((run_at <= '2013-02-12 03:40:27.848544' AND (locked_at IS NULL OR locked_at < '2013-02-11 23:40:27.848572') OR locked_by = 'host:my-imac.local pid:13313') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1) AND ((run_at <= '2013-02-12 03:40:27.848544' AND (locked_at IS NULL OR locked_at < '2013-02-11 23:40:27.848572') OR locked_by = 'host:my-imac.local pid:13313') AND failed_at IS NULL)
> 
> 11:40:37 worker.1 |   SQL (0.4ms)  UPDATE "delayed_jobs" SET "locked_at" = '2013-02-12 03:40:32.851916', "locked_by" = 'host:my-imac.local pid:13313' WHERE "delayed_jobs"."id" IN (SELECT id FROM "delayed_jobs" WHERE ((run_at <= '2013-02-12 03:40:32.851348' AND (locked_at IS NULL OR locked_at < '2013-02-11 23:40:32.851382') OR locked_by = 'host:my-imac.local pid:13313') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1) AND ((run_at <= '2013-02-12 03:40:32.851348' AND (locked_at IS NULL OR locked_at < '2013-02-11 23:40:32.851382') OR locked_by = 'host:my-imac.local pid:13313') AND failed_at IS NULL)
> 
> 11:40:37 worker.1 |   SQL (0.4ms)  UPDATE "delayed_jobs" SET "locked_at" = '2013-02-12 03:40:37.854636', "locked_by" = 'host:my-imac.local pid:13313' WHERE "delayed_jobs"."id" IN (SELECT id FROM "delayed_jobs" WHERE ((run_at <= '2013-02-12 03:40:37.854057' AND (locked_at IS NULL OR locked_at < '2013-02-11 23:40:37.854091') OR locked_by = 'host:my-imac.local pid:13313') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1) AND ((run_at <= '2013-02-12 03:40:37.854057' AND (locked_at IS NULL OR locked_at < '2013-02-11 23:40:37.854091') OR locked_by = 'host:my-imac.local pid:13313') AND failed_at IS NULL)

It seems to be doing this every 5 seconds i.e. every time DJ polls my DB.

Perhaps this is just a new logging feature that I was unaware of or is this not expected behaviour?

**Comment by alwaysanirudh** [comment]
I'm facing the same issue in my production environment. I understand that DelayedJob polls DB every 5 seconds but there should be a way to silence it. Having said that the actual DelayedJob execution logs should be present in the logs. The above solution looks good but my concern is that it should not silence other DelayedJob logs.

**Comment by xHire** [comment]
DJ can have its own logger for AR too, no need for the hassle in the patch above. I just added the following line to `config/initializers/delayed_job_config.rb`:

```ruby
Delayed::Backend::ActiveRecord::Job.logger = Logger.new(Rails.root.join('log', 'delayed_job_ar.log'))
```

**Comment by wpsamurai** [comment]
@xHire I'm afraid that your change will send all ActiveRecord logs to delayed_job_ar.log file, not only those from DelayedJobs gem.

**Comment by xHire** [comment]
@wpsamurai Ah, I didn’t notice it, but when I do run `grep -v delayed_jobs` I see that you are right. I’ll have yet to find out a way to restrict the initializer to affect only the DJ daemon then. Thank you for pointing this out! :+1:

**Comment by aiomaster** [comment]
Based on the monkey patch of @dsgh I want to offer a more "clean" monkey patch like this:
```ruby
if Rails.env.development?
  Delayed::Backend::ActiveRecord::Job.prepend(
    Module.new do
      def reserve(*)
        previous_level = ::ActiveRecord::Base.logger.level
        ::ActiveRecord::Base.logger.level = Logger::WARN if previous_level < Logger::WARN
        value = super
        ::ActiveRecord::Base.logger.level = previous_level
        value
      end
    end
  )
end
```

**Comment by pebneter** [comment]
This worked well for years, but after upgrading to Rails 6.0 / 6.1 I get
```NameError: undefined method `reserve' for class `#<Class:Delayed::Backend::ActiveRecord::Job>'````
Any idea how to fix this again?

**Comment by pebneter** [comment]
I can answer my own question and contribute to the solution. Based on your work, I found this approach to be working for me in Rails 6.1.3:

1) Create a new file for the patch in /lib
```ruby
# /lib/patches/delayed_job.rb

module Delayed::Backend::ActiveRecord
  class Job
    self.singleton_class.prepend(
      Module.new do
        def reserve(*)
          previous_level = ::ActiveRecord::Base.logger.level
          ::ActiveRecord::Base.logger.level = Logger::WARN if previous_level < Logger::WARN
          value = super
          ::ActiveRecord::Base.logger.level = previous_level
          value
        end
      end
    )
  end
end
```
2) Make sure the patch is loaded. I did it by creating a new initializer for all custom patches
```ruby
# /initializers/patches.rb

Dir.glob(Rails.root.join('lib/patches/**/*.rb')).sort.each do |filename|
  require filename
end
```

**Comment by xHire** [comment]
Nowadays, I use the following patch, which effectively separates DJ-related AR logging without affecting the rest of my application:
```diff
--- a/bin/delayed_job	2017-05-02 11:08:24.809361621 +0200
+++ b/bin/delayed_job	2020-03-19 17:23:27.338214244 +0100
@@ -2,4 +2,5 @@
 
 require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
 require 'delayed/command'
+Delayed::Backend::ActiveRecord::Job.logger = ActiveSupport::Logger.new(Rails.root.join('log', 'dj_ar.log'))
 Delayed::Command.new(ARGV).daemonize
```
Might be helpful for folks who don’t want to disable the logs altogether (or can log into `/dev/null` without monkey patching log levels). Tested with Rails 6.0.
