### ISSUE TITLE
Delayed::DeserializationError with Rails 3.2.12

### ISSUE THREAD

**Issue by tomrossi7** [collectiveidea/delayed_job#512]
I believe their may be an issue with delayed_job 3.0.5 (delayed_job_active_record 0.4.1) on Rails 3.2.12.   I am having problems with some of my jobs failing because of "Deserialization". Here is a really simple example of one of the failing handlers:

``` ruby
--- !ruby/struct:Delayed::PerformableMethod
object: LOAD;Project;924951
method: :send_project_open_close_without_delay
args: []
```

Errors out with this message:

``` ruby
Delayed::DeserializationError: Job failed to load: undefined method `members' for nil:NilClass.
```

Everyone seems to think this is caused by an AR object that no longer exists. In my case, I can run the handler just fine:

``` ruby
Project.find(924951).send_open_close_without_delay
```

Someone else thought adding this to the `boot.rb` may fix the issue, but it didn't:

``` ruby
require 'rubygems'
require 'yaml'
YAML::ENGINE.yamler = 'syck'
```

Is this a bug with Delayed Job?  Is there something else I can try?

**Comment by bbergstrom** [comment]
When `Delayed::DeserializationError: Job failed to load` occurs it appears that an attempt is not incremented, the job is never retried and the worker process gets stuck.  We experienced this during our upgrade rollout and had to manually restart workers to clear out this bad state.
