### ISSUE TITLE
DJ always appends _without_delay to certain method

### ISSUE THREAD

**Issue by drale2k** [collectiveidea/delayed_job#522]
DJ works fine on all methods except for this one. It does always append '_without_delay' to this methods and i don't know why.

This is the Foreman output:

```
03:06:41 worker.1 | [Worker(host:Drazens-MacBook-Air.local pid:98827)] VideoAsset#encode_without_delay completed after 0.0948
03:06:41 worker.1 | [Worker(host:Drazens-MacBook-Air.local pid:98827)] 1 jobs processed at 8.0676 j/s, 0 failed ...
```

This is the Model code:

``` ruby
class VideoAsset < ActiveRecord::Base

  include Rails.application.routes.url_helpers
  include VideoEncoder

  after_save :encode

  belongs_to :assetable, polymorphic: true
  has_many :zencoder_jobs, :uniq => true, :inverse_of => :video_asset, :dependent => :destroy

  # Validations
  validates :video, :poster, :presence => true

  # CarrierWave Mount Uploaders
  mount_uploader :poster, VideoAssetPosterUploader

  def encode
    # Encode only if the video file has changed (or is new)
    if self.video_changed?
      response = VideoEncoder.encode(self, notification_api_v1_zencoder_jobs_url)
      if response.success?
        job_id = response.body["id"]
        video_id = self.id
        ZencoderJob.create(:job_id => job_id, :video_asset_id => video_id, :encoded_state => "processing")
      end
    end
  end
  # Run this method always with DJ
  handle_asynchronously :encode
end
```

Is it maybe a problem to call the method in the after_save callback?

Using Ruby 2.0 and Rails 3.2.13

**Comment by bbnnt** [comment]
damn it. this thing should be highlighted in the readme.

If I understand it wee though : 
In my app, i have let's say the following
```
after_save :do_delayed_stuff
def do_delayed_stuff
...
end
handle_asynchronously :do_delayed_stuff
```
Which always returns an error, ```undefined do_delayed_stuff_without_delay```

If In understand what's explained here, I should have two methods :
```
def do_delayed_stuff
end
```
and
```
def do_delayed_stuff
end
```

with pretty much the same code in each (or a shortcut like you shown) if i wanted it all to work correctly
Am I right ?

**Comment by drale2k** [comment]
No the way you modelled it in the first block is correct

````
after_save :do_delayed_stuff
def do_delayed_stuff
...
end
handle_asynchronously :do_delayed_stuff
````

He just explained what happens under the hood. You don#t have to do that manually. The error you get could be related to something different.

**Comment by bbnnt** [comment]
Damn so far DJ has been evil to me :/

I might be in a desperate need to understand what would be the entry point to understand I get this recurrent ```undefined {method}_without_delay``` error

**Comment by albus522** [comment]
Getting undefined method errors is usually a result of the worker not running the same code as the web process. There are many ways this can happen. Most involve a failed restart of the worker process after a code deploy. The easiest way to fix that is to stop all worker processes manually and start up a clean set of worker processes.

**Comment by bbnnt** [comment]
Feels like my mina deploy recipe is not doing the right thing
Thanks a lot for your reply @albus522 , feel more confident about it then.
