### ISSUE TITLE
Mailer Interceptor not firing?

### ISSUE THREAD

**Issue by cspeer** [collectiveidea/delayed_job#542]
Hey,

this is more of a question than a real issue.
I happen to have to set things like the from address when sending mails right at the moment when the mail is about to send. Therefore I wrote an Rails Interceptor which works just fine for mails that are NOT delivered through delayed jobs.
I am not entirely sure, but is it possible that those interceptors, registered with ActionMailer::Base.register_observer(MailObserver) will not loaded/fired when using delayed jobs?
And if so, is there any other way to hook into delayed jobs, so I could set some environment variables such as ActionMailer::Base.default?

Thanks,
Chris

**Comment by akaspick** [comment]
@cspeer Old message, but were you able to get interceptors working with delayed job callbacks/hooks?
