### ISSUE TITLE
delayed_job breaks unsaved/deleted AR object YAML serialization using psych

### ISSUE THREAD

**Issue by lifeBCE** [collectiveidea/delayed_job#587]
rails 3.2.13
delayed_job 4.0.0

Seems delayed_job breaks all YAML serialization for all unsaved ActiveRecord objects. Even those objects that have not been designated as part of a delayed job. I am serializing objects as part of an event log I have developed. I have logic that will serialize a blank (new) object or deleted object for reference that is broken by delayed_job.

Portion of delayed_job extension causing issues:

``` ruby
        case object.tag
        when /^!ruby\/ActiveRecord:(.+)$/
          klass = resolve_class($1)
          payload = Hash[*object.children.map { |c| accept c }]
          id = payload["attributes"][klass.primary_key]
          begin
            klass.unscoped.find(id)
          rescue ActiveRecord::RecordNotFound
            raise Delayed::DeserializationError
          end
```

Same crap dealing with masking ActiveRecord::RecordNotFound exception. Main difference between my issue and others I have seen reported on this same problem for last 2 years is I am not trying to delay a job on an unsaved object. My unsaved object issue is completely outside the scope of delayed_job yet delayed_job's extensions still break the required functionality. Aside from broken functionality, these extensions also cause major performance issues. An application that serializes hundreds or thousands (if not hundreds of thousands) of objects will be crippled if they install delayed_job and start being forced to query the database for every object as a normal part of serialization logic.

**Comment by patrickdavey** [comment]
I'm currently upgrading a very old rails 3 app and I ran into this issue with `serialize` no longer working on rails models after upgrading to DJ 4.1.  This was occuring for me for saved records outside of any DJ workflow.

I used the patch from @lifeBCE https://github.com/collectiveidea/delayed_job/issues/587#issuecomment-32522318 and all worked well again. I'm unsure why @albus522 said this shouldn't be an issue any more, but, it did bite me.
