### ISSUE TITLE
MySQL deadlock when a job is complete

### ISSUE THREAD

**Issue by joongimin** [collectiveidea/delayed_job#611]
I'm running 8 processes of delayed_job and queued some million jobs that takes couple hundred ms to complete. Jobs seem to be completed successfully but occasionally errors are thrown while trying to remove the job after completion. Would there be any work around?

Here's my error message. I've got couple hundreds of them just like this one:

```
An ActiveRecord::StatementInvalid occurred in background at 2013-12-14 07:28:43 +0900 :

  Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction: DELETE FROM `delayed_jobs` WHERE `delayed_jobs`.`id` = 253860
```

And here's my Gemfile.lock regarding delayed_job:

```
    delayed_job (4.0.0)
      activesupport (>= 3.0, < 4.1)
    delayed_job_active_record (4.0.0)
      activerecord (>= 3.0, < 4.1)
      delayed_job (>= 3.0, < 4.1)
```

Thanks in advance.

**Comment by taurauko** [comment]
We're still getting errors like this using the latest versions of both DJ and DJ+AR.

```
Job MyJob FAILED (0 prior attempts) with ActiveRecord::Deadlocked: Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction: DELETE FROM `delayed_jobs` WHERE `delayed_jobs`.`id` = 3262358
```

Any suggestions how to resolve this?

**Comment by synth** [comment]
Same here. We see this most with two conditions:
1. We start scaling up the number of workers
2. Deadlock or Lock wait timeouts occur when trying to delete the delayed job record after its completion. 

DJ v4.1.5
DJ+AR v4.1.3
