### ISSUE TITLE
Difference between `bin/delayed_job` and `rake jobs:work`?

### ISSUE THREAD

**Issue by dideler** [collectiveidea/delayed_job#659]
The README says both "will start working off jobs". 

The README seems to present `delayed_job` script as the preferred method since it's introduced first. 

[The Heroku DJ guide](https://devcenter.heroku.com/articles/delayed-job#setting-up-delayed-job) uses `rake jobs:work`.

[Ryan Bates has a RailsCast](http://railscasts.com/episodes/171-delayed-job-revised) where he says to use the `delayed_job` script instead of `rake jobs:work` in production.

> So far we've been starting Delayed Job by running `rake jobs:work` but in production we should use the delayed_job script provided in the script folder.

Any tips for when to use which?

**Comment by wired00** [comment]
what about when running via supervisord which requires foreground processes?

**Comment by albus522** [comment]
`rake jobs:work` is no less production worthy than `bin/delayed_job`. Use what works for your use case.

**Comment by javanux** [comment]
I want to run `delayed_job` as a foreground process since I as using `runsv` to supervise the workers. But the `--pid-dir` option doesn't work while running it in foreground i.e `pid-file` is not created in `approot/shared//tmp/pids` which is preventing me to send `kil`l signal to that process while deploying.

**Comment by hiveer** [comment]
I have the same question. When I look into the source code of both two ways,  I found actually they are doing the similar things, except `bin/delayed_job` will start the worker in a daemon process(this is the reason why you need to install gem 'daemons')`.

You can refer to the source code below:
```ruby
    #lib/delayed/command.rb
    def run_process(process_name, options = {})
      Delayed::Worker.before_fork
      Daemons.run_proc(process_name, :dir => options[:pid_dir], :dir_mode => :normal, :monitor => @monitor, :ARGV => @args) do |*_args|
        $0 = File.join(options[:prefix], process_name) if @options[:prefix]
        run process_name, options
      end
    end

def run(worker_name = nil, options = {})
      Dir.chdir(root)

      Delayed::Worker.after_fork
      Delayed::Worker.logger ||= Logger.new(File.join(@options[:log_dir], 'delayed_job.log'))

      worker = Delayed::Worker.new(options)
      worker.name_prefix = "#{worker_name} "
      worker.start
    rescue => e
      STDERR.puts e.message
      STDERR.puts e.backtrace
      ::Rails.logger.fatal(e) if rails_logger_defined?
      exit_with_error_status
    end
```

```ruby
  #lib/delayed/tasks.rb
  desc 'Start a delayed_job worker.'
  task :work => :environment_options do
    Delayed::Worker.new(@worker_options).start
  end
```
