### ISSUE TITLE
Document the usage through Active Job

### ISSUE THREAD

**Issue by Nowaker** [collectiveidea/delayed_job#711]
It would be good to include some getting started instructions for Active Job from Rails 4.2+ in README.md. I'm already using Delayed Job in other Rail 4 project, but it's not clear to me how to get started with delayed_job through Active Job. For example, should the Delayed::Worker initializer stay or not?

I'm aware it's Active Job developers who implemented the integration and should document all the stuff, but having it documented directly in Delayed Job README.md would really come in handy.

**Comment by avand** [comment]
I'm also looking to upgrade to 4.2 and use Delayed Job. It's not clear to me what I have to do to have ActiveJob play nicely with DJ.

**Comment by patrickpilch** [comment]
👍  on this ticket as well.
I am consistently running into issues with DJ and ActiveJob interoperability. After getting past max_attempts with the gem referenced in #715, I'm now having problems getting the `error` hook to be triggered.
