### ISSUE TITLE
set max_attempts per job in ActiveJob

### ISSUE THREAD

**Issue by Nowaker** [collectiveidea/delayed_job#715]
According to [ActiveJob Feature Matrix](http://edgeapi.rubyonrails.org/classes/ActiveJob/QueueAdapters.html) Delayed Jobs doesn't support overriding the maximal number of retries. Well, in raw ol' Delayed Job it's possible by overriding `max_attempts` method. Since ActiveJob will be the source of many new users, I suggest to implement it. Thanks!

**Comment by ajporterfield** [comment]
@Nowaker, here's a gem I recently published that allows you to override max_attempts in ActiveJob - https://github.com/ajporterfield/activejob_dj_overrides
