### ISSUE TITLE
Where is the find_available method defined?

### ISSUE THREAD

**Issue by danielristic** [collectiveidea/delayed_job#726]
Hi,

I'm trying to understand how available jobs are selected to be processed and I stumbled upon the following code in base.rb:

```
def reserve(worker, max_run_time = Worker.max_run_time)
  # We get up to 5 jobs from the db. In case we cannot get exclusive access to a job we try the next.
  # this leads to a more even distribution of jobs across the worker processes
  find_available(worker.name, worker.read_ahead, max_run_time).detect do |job|
    job.lock_exclusively!(max_run_time, worker.name)
  end
end
```

The next step would be to see what the find_available method does but I can't find it defined anywhere.

Am I missing something?

**Comment by nbrustein** [comment]
I think this answer is no longer correct.  Now (version 4.1.1), it looks like delayed_job_active_record overrides the reserve method entirely, and does not implement find_available.
