### ISSUE TITLE
Sending Mails from Rails 3 "uninitialized constant Mail::ParameterHash"

### ISSUE THREAD

**Issue by mmack** [collectiveidea/delayed_job#73]
Hi all,

i get this error message when starting the worker process:

Job failed to load: uninitialized constant Mail::ParameterHash. Try to manually require the required file. Handler: "--- !ruby/struct:Delayed::PerformableMethod \n:object: !ruby/object:Mail::Message \n  body: !ruby/object:Mail::Body \n    boundary:...

This is how the job is generated:

ReceiptsMailer.attendee_invoice(@user, @order).send_later(:deliver)

I'm using rails 3 and ruby 1.9.1

Can someone confirm this? Or does someone have a bug fix?

Greetings Max

**Comment by lutonda** [comment]
nice
