### ISSUE TITLE
invoke_job No Longer Catches Exception -Yay! But This Is a Breaking Change

### ISSUE THREAD

**Issue by sshaw** [collectiveidea/delayed_job#741]
While I do support RuboCop imposing the death sentence for such egregious violations there is (unfortunately) code in the wild that raises `Exception` instead of `StandardError` subclasses :crying_cat_face:.  [This commit](https://github.com/collectiveidea/delayed_job/commit/d3ce893b8f800b731ad197e2b93e42dfd5b3690b#diff-69793f05cfd20679fbdfcf77fa7d4e10L107) causes the delayed job worker to exit when those Java loving classes do their dirty deeds...

**Comment by aaronjensen** [comment]
yeah, this is a huge change. Broke production delayed_job for us, took a bit to track down. It should definitely be in release notes in bold/all caps.

**Comment by aaronjensen** [comment]
Awesome, thanks!

**Comment by maxjacobson** [comment]
:smile: thanks!
