### ISSUE TITLE
DJ job's handler bigger in Rails 4.2 and causing issues with Draper

### ISSUE THREAD

**Issue by gotchahn** [collectiveidea/delayed_job#762]
I recently started to upgrade my application from Rails 4.1 to Rails 4.2. And now that i am focus on test our emails with DelayedJob i found some bad behaviours while using `delay` like this: `EmailClass.delay.action(args)` the error is ALWAYS trying to call a method from a decorated object (Using `Draper`), For example inside my action's mailer i have this code: 
`contact = company.collaboration.invitable_contacts.first` and when i run `jobs:work` i get:

``` ruby
[Worker(host:localhost pid:9044)] Job CollaborationMailer.invitation (id=677666) RUNNING
[Worker(host:localhost pid:9044)] Job CollaborationMailer.invitation (id=677666) FAILED (2 prior attempts) with NoMethodError: undefined method `collaboration' for #<CompanyDecorator:0x007f9ee64977f8>
```

But on console i can perfectly call that method from a decorated `Company` object.

Digging on this, i notice that the handler that is saved on DB is different from Rails 4.1 to 4.2, dunno if that create a conflict with the decorated object.

I am using `delayed_job_active_record (4.0.3)` and `delayed_job (4.0.6)`

**Comment by ravicious** [comment]
Did you manage to fix this? I have similar issue. A decorated object gets serialized with OrderDecorator and then the job tries to call a method on OrderDecorator (which doesn't exist). 

```ruby
irb(main):011:0> puts job.handler
--- !ruby/object:Delayed::PerformableMethod
object: !ruby/object:MixpanelService
  tracker: !ruby/object:Mixpanel::Tracker
    token: 1234
    async: false
    persist: false
    env:
      mixpanel_events: []
    api_key:
method_name: :track_checkout_end
args:
- :order: !ruby/object:OrderDecorator
    raw_attributes:
      id: '1337'
```

**Comment by gotchahn** [comment]
Nop i couldn't fix it. I just decided to refactor my delayed jobs for sending just the IDs of my objects instead of the whole object.
