### ISSUE TITLE
Backtrace in logs

### ISSUE THREAD

**Issue by tiredenzo** [collectiveidea/delayed_job#763]
In case of Job failing we could maybe add an optional backtrace of the exception to the logs..
Would it be ok if i do a pull request with this feature. If so any recommendations/tips on the implementation before I start (in command.rb method run)

**Comment by albus522** [comment]
You could do a pull request, but error reporting tools, such as HoneyBadger and Airbrake, already capture full error info. And if you are looking for alternate handling the error hook is probably your best bet, which doesn't require any changes to DJ.
