### ISSUE TITLE
Delayed Job with multiple rails apps

### ISSUE THREAD

**Issue by joshpfosi** [collectiveidea/delayed_job#766]
This might be a rare situation for a lot of people but I thought I'd share (and maybe find a solution!). I was developing two rails apps at the same time on my local machine on two different ports. Rather than set them up each time I just leave them running so context switching is faster. However, as I introduced Delayed Job to the second of the two applications, and ran `rake jobs:work`, the query would look in the database of the first application, and log output to its log file. This took me about an hour to figure out and not sure if there is any preventative measure.

**Comment by albus522** [comment]
Rake tasks are purely dependent on the directory in which they are run. You must have accidentally run both instances of `rake jobs:work` in the one project's directory.
