### ISSUE TITLE
Rails 4.2

### ISSUE THREAD

**Issue by SaimonL** [collectiveidea/delayed_job#767]
Heads up. Rails 4.2 has 'Active Job' where you use Rails to generated Jobs and then use adapters like sidekiq, restque, delayjob to execute them. 

This is done to generalize the creation of Job queuing system so you can switch from one adapter to another without making massive code rewrite.

Also you will need to set the application.rb and tell rails which adapter you are using.
Example
<pre>
config.active_job.queue_adapter = :sidekiq
</pre>

I don't know for delayed job what it should be set to (delayed_job_active_record or delayed_job, or delayed_job_mongoid?).
I will keep an eye on Delay Job manual for Rails 4.2 updates.

For more information visit:
http://edgeguides.rubyonrails.org/active_job_basics.html

**Comment by aliaksandrb** [comment]
@SaimonL I believe that `config.active_job.queue_adapter = :delayed_job` will do the thing. [According to Active Job sources](https://github.com/rails/rails/blob/49c9f850fa3e2484e3aaf20b2479f61b1cc9375e/activejob/test/adapters/delayed_job.rb)

**Comment by lenart** [comment]
:+1: 

I can confirm that setting `config.active_job.queue_adapter = :delayed_job` in your application.rb (or somewhere in `environments/` folder) switches to DelayedJob backend. Thanks @aliaksandrb for finding the relevant file.

**Comment by SaimonL** [comment]
I am assuming this is standard way

```bash
vim config/initializers/active_job.rb
```

### For  Delayed Job

```ruby
ActiveJob::Base.queue_adapter = :delayed_job

Delayed::Worker.destroy_failed_jobs = false
Delayed::Worker.sleep_delay = 60
Delayed::Worker.max_attempts = 3
Delayed::Worker.max_run_time = 5.minutes
Delayed::Worker.read_ahead = 10
Delayed::Worker.default_queue_name = 'default'
Delayed::Worker.delay_jobs = !Rails.env.test?
Delayed::Worker.raise_signal_exceptions = :term
Delayed::Worker.logger = Logger.new(File.join(Rails.root, 'log', 'delayed_job.log'))
```

### For  Sidekiq

_TESTED_

```ruby
ActiveJob::Base.queue_adapter = :sidekiq

Sidekiq.default_worker_options = {
  backtrace: true,
  queue: :default,
  retry: false
}
```

### For  Resque

_TESTED_

```ruby
ActiveJob::Base.queue_adapter = :resque

Resque.configure do |config|
  # Set the redis connection. Takes any of:
  #   String - a redis url string (e.g., 'redis://host:port')
  #   String - 'hostname:port[:db][/namespace]'
  #   Redis - a redis connection that will be namespaced :resque
  #   Redis::Namespace - a namespaced redis connection that will be used as-is
  #   Redis::Distributed - a distributed redis connection that will be used as-is
  #   Hash - a redis connection hash (e.g. {:host => 'localhost', :port => 6379, :db => 0})
  config.redis = 'localhost:6379:alpha/high'
end
```
