### ISSUE TITLE
No jobs are being saved in the database

### ISSUE THREAD

**Issue by ewamarciniak** [collectiveidea/delayed_job#772]
I am using Rails 4.1.1 and implementing delayed job to add scheduled notifications. I have implemented the gem and used 'delayed' method as follows:
````
class MessageSocialAccount < ActiveRecord::Base
  attr_accessible :social_account_id, :message_id, :read_time, :push_notification
  attr_reader :when_to_run
  belongs_to :message
  belongs_to :social_account

  def when_to_run
    message.deliver_at || Time.now
  end

  def push
    social_account.send_push(msg_sca.message)
    update_attributes!(:push_notification => true)
  end
  handle_asynchronously :push, :run_at => Proc.new {|i| i.when_to_run }
end
````
I am calling the push method from another model but that should not really matter.
The workers are started ( run rake jobs:work) but when I run `Delayed::Job.all` in the console, an empty array is returned. I am pretty sure the table has been created so can you please let me know if I am doing something incorrectly or is it a bug? Thanks

**Comment by albus522** [comment]
The job is deleted after it has run. Is the job running?

**Comment by ewamarciniak** [comment]
When I schedule the job to be run at some time in the future ( e.g. in 2 hours) I expect to see the job saved in the table and wait there for 2 hours before disappearing, but there is nothing in there.

**Comment by albus522** [comment]
Are you checking the correct environment?

**Comment by ewamarciniak** [comment]
I am testing locally, and checking in the console.

**Comment by albus522** [comment]
Do you have `Delayed::Worker.delay_jobs` set to false?
What does running `message_social_account_instance.push` give you in the console?

**Comment by ewamarciniak** [comment]
Sorry albus522 for the delay. I realised that the app had already implemented sidekiq for another purpose and when I opened the sidekiq web interface I could see all the scheduled jobs in there so this other gem could have been causing this problem. I think I just need to decide on one or the other. Thanks for your help
