### ISSUE TITLE
undefined method delay for MyMailer

### ISSUE THREAD

**Issue by remon** [collectiveidea/delayed_job#778]
in development its working great but in production dj gives me 
undefined method delay for MyMailer

the output in rake jobs:work gives me 

Job MyMailer.inspect (id=2) FAILED (3 prior attempts) with NoMethodError: undefined method `delive
r' for "MyMailer":String
I am using delayed_job 4.0.3
ruby 2.1.5
rails 3.2.21

**Comment by albus522** [comment]
What is your exact delay line?

**Comment by remon** [comment]
MyMailer.delay.mymethd(arg)
in development it's working but in production the above errors are shown to me

**Comment by remon** [comment]
in the console ,it works great

**Comment by albus522** [comment]
That error message suggests that is not what the exact line looks like and that some meta programming may be involved.

**Comment by remon** [comment]
these is the complete method I use 
 MyMailer.delay.send_request(@profile.user,current_user)

do you think these could be an issue regarding using ruby 2.1.5?

**Comment by albus522** [comment]
That seems correct. Can you see if there is a difference in the generated handler in dev vs production? And post as much of it as you can. Be sure to change anything actually sensitive.

**Comment by remon** [comment]
…ms/delayed_job-4.0.6/lib/delayed/
performable_mailer.rb:   7:in `perform'
…1.0/gems/delayed_job-4.0.6/lib/delayed/backend/
base.rb:  94:in `block in invoke_job'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
/home/remoncpo/apps/myapp/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb
lifecycle.rb:  61:in `call'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  61:in `block in initialize'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  66:in `call'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  66:in `execute'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  40:in `run_callbacks'
…1.0/gems/delayed_job-4.0.6/lib/delayed/backend/
base.rb:  91:in `invoke_job'
…uby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
worker.rb: 204:in `block (2 levels) in run'
…moncpo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/
timeout.rb:  91:in `block in timeout'
…moncpo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/
timeout.rb: 101:in `call'
…moncpo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/
timeout.rb: 101:in `timeout'
…uby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
worker.rb: 204:in `block in run'
…uby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
worker.rb: 203:in `run'
…uby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
worker.rb: 280:in `block in reserve_and_run_one_job'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  61:in `call'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  61:in `block in initialize'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  66:in `call'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  66:in `execute'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  40:in `run_callbacks'
…uby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
worker.rb: 280:in `reserve_and_run_one_job'
…uby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
worker.rb: 187:in `block in work_off'
…uby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
worker.rb: 186:in `times'
…uby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
worker.rb: 186:in `work_off'
…uby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
worker.rb: 150:in `block (4 levels) in start'
…uby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
worker.rb: 149:in `block (3 levels) in start'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  61:in `call'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  61:in `block in initialize'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  66:in `call'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  66:in `execute'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  40:in `run_callbacks'
…uby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
worker.rb: 148:in `block (2 levels) in start'
…uby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
worker.rb: 147:in `loop'
…uby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
worker.rb: 147:in `block in start'
…s/delayed_job-4.0.6/lib/delayed/plugins/
clear_locks.rb:   7:in `call'
…s/delayed_job-4.0.6/lib/delayed/plugins/
clear_locks.rb:   7:in `block (2 levels) in <class:ClearLocks>'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  79:in `call'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  79:in `block (2 levels) in add'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  61:in `call'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  61:in `block in initialize'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  79:in `call'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  79:in `block in add'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  66:in `call'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  66:in `execute'
…/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
lifecycle.rb:  40:in `run_callbacks'
…uby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
worker.rb: 146:in `start'
…by/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
command.rb: 124:in `run'
…by/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
command.rb: 112:in `block in run_process'
…by/2.1.0/gems/daemons-1.1.9/lib/daemons/
application.rb: 255:in `call'
…by/2.1.0/gems/daemons-1.1.9/lib/daemons/
application.rb: 255:in `block in start_proc'
…ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/
daemonize.rb:  82:in `call'
…ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/
daemonize.rb:  82:in `call_as_daemon'
…by/2.1.0/gems/daemons-1.1.9/lib/daemons/
application.rb: 259:in `start_proc'
…by/2.1.0/gems/daemons-1.1.9/lib/daemons/
application.rb: 296:in `start'
….0/gems/daemons-1.1.9/lib/daemons/
application_group.rb: 159:in `block (2 levels) in start_all'
….0/gems/daemons-1.1.9/lib/daemons/
application_group.rb: 158:in `fork'
….0/gems/daemons-1.1.9/lib/daemons/
application_group.rb: 158:in `block in start_all'
….0/gems/daemons-1.1.9/lib/daemons/
application_group.rb: 157:in `each'
….0/gems/daemons-1.1.9/lib/daemons/
application_group.rb: 157:in `start_all'
…uby/2.1.0/gems/daemons-1.1.9/lib/daemons/
controller.rb:  80:in `run'
…ed/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/
daemons.rb: 197:in `block in run_proc'
…e/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/
cmdline.rb: 109:in `call'
…e/ruby/2.1.0/gems/daemons-1.1.9/lib/daemons/
cmdline.rb: 109:in `catch_exceptions'
…ed/bundle/ruby/2.1.0/gems/daemons-1.1.9/lib/
daemons.rb: 196:in `run_proc'
…by/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
command.rb: 110:in `run_process'
…by/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
command.rb:  91:in `block in daemonize'
…by/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
command.rb:  89:in `times'
…by/2.1.0/gems/delayed_job-4.0.6/lib/delayed/
command.rb:  89:in `daemonize'

and another logging error for another actionmailer method with delay 


…/20150211083312/app/controllers/
profiles_controller.rb:  78:in `sendmsg'
…/1.9.1/gems/searchkick-0.8.5/lib/searchkick/
logging.rb: 107:in `process_action'
…le/ruby/1.9.1/gems/journey-1.0.4/lib/journey/
router.rb:  68:in `block in call'
…le/ruby/1.9.1/gems/journey-1.0.4/lib/journey/
/home/remoncpo/apps/optlar/shared/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb
router.rb:  56:in `each'
…le/ruby/1.9.1/gems/journey-1.0.4/lib/journey/
router.rb:  56:in `call'
…uby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/
strategy.rb: 186:in `call!'
…uby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/
strategy.rb: 164:in `call'
…ems/rack-mobile-detect-0.4.0/lib/rack/
mobile-detect.rb: 164:in `call'
…dle/ruby/1.9.1/gems/warden-1.2.3/lib/warden/
manager.rb:  35:in `block in call'
…dle/ruby/1.9.1/gems/warden-1.2.3/lib/warden/
manager.rb:  34:in `catch'
…dle/ruby/1.9.1/gems/warden-1.2.3/lib/warden/
manager.rb:  34:in `call'
…red/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/
etag.rb:  23:in `call'
…/ruby/1.9.1/gems/rack-1.4.5/lib/rack/
conditionalget.rb:  35:in `call'
…/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/
id.rb: 210:in `context'
…/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/
id.rb: 205:in `call'
…bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/
sendfile.rb: 102:in `call'
…/ruby/1.9.1/gems/rack-1.4.5/lib/rack/
methodoverride.rb:  21:in `call'
…/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/
runtime.rb:  17:in `call'
…red/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/
lock.rb:  15:in `call'
…by/1.9.1/gems/rack-cache-1.2/lib/rack/cache/
context.rb: 136:in `forward'
…by/1.9.1/gems/rack-cache-1.2/lib/rack/cache/
context.rb: 143:in `pass'
…by/1.9.1/gems/rack-cache-1.2/lib/rack/cache/
context.rb: 155:in `invalidate'
…by/1.9.1/gems/rack-cache-1.2/lib/rack/cache/
context.rb:  71:in `call!'
…by/1.9.1/gems/rack-cache-1.2/lib/rack/cache/
context.rb:  51:in `call'
…by/1.9.1/gems/unicorn-4.8.3/lib/unicorn/
http_server.rb: 576:in `process_client'
…by/1.9.1/gems/unicorn-4.8.3/lib/unicorn/
http_server.rb: 670:in `worker_loop'
…by/1.9.1/gems/unicorn-4.8.3/lib/unicorn/
http_server.rb: 525:in `spawn_missing_workers'
…by/1.9.1/gems/unicorn-4.8.3/lib/unicorn/
http_server.rb: 536:in `maintain_worker_count'
…by/1.9.1/gems/unicorn-4.8.3/lib/unicorn/
http_server.rb: 294:in `join'

**Comment by remon** [comment]
@albus522  I updated my logs ,check it please

**Comment by albus522** [comment]
The handler not the backtrace, please.

**Comment by remon** [comment]
@albus522  you mean that 
Job MyMailer.inspect (id=2) FAILED (3 prior attempts) with NoMethodError: undefined method `delive
r' for "MyMailer":String

**Comment by remon** [comment]
these is all errors I got 

Completed 500 Internal Server Error in 24ms

NoMethodError (undefined method `delay' for MyMailer:Class):

the output in rake jobs:work gives me

Job MyMailer.inspect (id=2) FAILED (3 prior attempts) with NoMethodError: undefined method `delive
r' for "MyMailer":String

**Comment by albus522** [comment]
`Delayed::Job.last.handler`

**Comment by remon** [comment]
Delayed::Backend::ActiveRecord::Job Load (1.7ms)  SELECT "delayed_jobs".* FROM "delayed_jobs" ORDER BY "delayed_jobs"."id" DESC LIMIT 1

=> "--- !ruby/object:Delayed::PerformableMailer\nobject: !ruby/class 'MyMailer'\nmethod_name: :inspect\nargs: []\n"

**Comment by albus522** [comment]
Do you get the same results on production and dev?

**Comment by albus522** [comment]
For the handler

**Comment by remon** [comment]
only on production env , in development it works and gives me 

"--- !ruby/object:Delayed::PerformableMailer\nobject: !ruby/class 'MyMailer'\nmethod_name: :new_view\nargs:\n- !ruby/object:User\n
  attributes:\n    id: 3\n    email:....................etc

**Comment by albus522** [comment]
Make sure that the production worker has restarted properly and in the correct working directory. I think things are out of sync between the app and the worker

**Comment by albus522** [comment]
Also make sure there aren't any lingering workers sitting around

**Comment by remon** [comment]
I am putting these line on my deploy.rb file
require "delayed/recipes"
using capistrano 2

"Also make sure there aren't any lingering workers sitting around"
how can I do that?

**Comment by albus522** [comment]
Log in to the server and lookup the processes. Which is something I am not equipped to help much with. It will depend highly on the server setup

**Comment by remon** [comment]
@albus522  however in the console it's working but I will try 
how can I check for the delayed job processes ?

**Comment by albus522** [comment]
Like I said. It will depend on your server setup and I only know enough about server administration to be dangerous. I would start with `ps -ef`

**Comment by remon** [comment]
$ ps -ef | grep delayed_job

remon 13075     1  0 08:39 ?        00:00:23 delayed_job
remon 20480 23349  0 19:21 pts/1    00:00:00 grep --color=auto delayed_job

**Comment by albus522** [comment]
Try killing that process. Hopefully `cap delayed_job:stop` does it. If not, use `kill 13075`. Make sure the PID hasn't changed. Then start the process again with `cap delayed_job:start`

**Comment by albus522** [comment]
Run `cap` locally, but `kill` on the server

**Comment by remon** [comment]
I did that using cap commands and nothing changed

**Comment by albus522** [comment]
Then cap is not working and those scripts are notoriously buggy. Which likely means your worker is way out of sync from your app

**Comment by albus522** [comment]
What did the cap commands give you as output?

**Comment by remon** [comment]
cap delayed_job:stop
  * 2015-02-11 21:23:14 executing `delayed_job:stop'
  * executing "cd /home/remoncpo/apps/myapp/current;RAILS_ENV=production script/delayed_job stop"
   
    [server ip] executing command
 ** [out :: server ip] delayed_job: trying to stop process with pid 13075...
 ** [out :: server ip]
 ** [out :: server ip] delayed_job: process with pid 13075 successfully stopped.
    command finished in 9105ms


$ cap delayed_job:start
  * 2015-02-11 21:23:53 executing `delayed_job:start'
  * executing "cd /home/remoncpo/apps/myapp/current;RAILS_ENV=production script/delayed_job start"

    [server ip] executing command
    command finished in 7741ms

**Comment by albus522** [comment]
And the PID of the running DJ process didn't change?

**Comment by remon** [comment]
no ,the delayed_job pid has only these value 

21157

**Comment by albus522** [comment]
That would mean it updated because it was 13075. Try running a new job

**Comment by remon** [comment]
RAILS_ENV=production bundle exec rake jobs:work
[Worker(host:li270-147 pid:21352)] Starting job worker
and the same error is shown but the command output didn't changed

**Comment by albus522** [comment]
I am out of ideas

**Comment by remon** [comment]
@albus522  thanks a lot for your precious help
I will try to change to sidekiq and let you know , if it's related to delayed job gem or to my env
also I will try to change back to ruby 1.9.3 and give you the updates

**Comment by remon** [comment]
@albus522  I will till you the magic 
I restarted my unicorn process and it worked now

**Comment by albus522** [comment]
¯\_(ツ)_/¯
