### ISSUE TITLE
PerformableMethod-like classes aren't compatible with hooks

### ISSUE THREAD

**Issue by adamcooke** [collectiveidea/delayed_job#783]
I've recently been working on creating my own PerformableMethod-like class which inherits from `PerformableMethod` but includes a `before` method so something can be run before each of the jobs which use it.

My issue is that when a hook is called ([here](https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/backend/base.rb#L112-L115)], it uses this code which checks the `PerformableMethod` object responds to the hook name and then calls it through the `method` method.

``` ruby
if payload_object.respond_to?(name)
  method = payload_object.method(name)
  method.arity == 0 ? method.call : method.call(self, *args)
end
```

The `method` call is delegated to the performable method's object but the `responds_to?` will check both the `PerformableMethod` instance as well as the object. Therefore, if you define `before` hook on a performable method class it passes the `responds_to?` check and then raises an undefined error exception because it doesn't actually exist on the PM's object.

I haven't submitted a pull request because I don't actually know the best way to resolve this. Any thoughts would be greatly appreciated.

**Comment by albus522** [comment]
`PerformableMethod` is not intended to be a base class for anything. I am not sure there is anything to fix.

**Comment by adamcooke** [comment]
The use case here is the ability to add extra performable methods like `delay_with_tracking` which would be able to do extra things. Specifically for providing UI for users to see the status of background tasks which they have requested.

Rather than requiring such an extension to duplicate their own PerformableMethod, it would be nice to be able to use the existing method and simply add hooks to it.

**Comment by adamcooke** [comment]
This mostly stems from the fact that `perform` is not called with a the current job object whereas hooks can be. While this may be territory for another issue, where do you stand on passing the job instance to to the `perform` method in the same way as it is handled for hooks?

**Comment by albus522** [comment]
That is a no touch zone. Anyone that has generated a custom job class would have to change their code.

**Comment by adamcooke** [comment]
Helpful. Thank you for your assistance.

**Comment by adamcooke** [comment]
I've actually just realised what you meant at the end there - I was wrongly assuming that you were talking about the original point (the bug) rather than passing the job to `perform`. Apologies for leaping to that conclusion and being a dick.

Checking the arity of the `perform` method to see whether it accepts attributes or not wouldn't be too tricky, would it and providing the job if it supports them? Is it not safe to assume that all `perform` methods currently accept no arguments as otherwise a wrong number of attributes error would be thrown when the method was called through delayed job.

Finally, I did manage to work around the original `respond_to?` issue although it's not terribly pretty.

```ruby
class PerformableMethodWithHooks < Delayed::PerformableMethod

  HOOKS = {}

  HOOKS[:before] = Proc.new do |job|
    # Do stuff
  end

  HOOKS[:after] = Proc.new do |job|
    # Do other stuff
  end

  def respond_to?(symbol, include_private = false)
    HOOKS.keys.include?(symbol) || super
  end

  def method(name, *args)
    HOOKS[name.to_sym] || super
  end

end
```

**Comment by adamcooke** [comment]
I suppose it's not impossible that someone would have added optional args so that would be an issue.

**Comment by gvc** [comment]
@albus522 how would you suggest writing hooks for the use case of calling `object.delay.method` that is common in rails applications?

**Comment by albus522** [comment]
`PerfomableMethod` passes any method not defined on itself to the object `delay` was called on. So if that object implements any of https://github.com/collectiveidea/delayed_job#hooks methods, it should be called at the appropriate times.

**Comment by gvc** [comment]
Isn't that asking for the users of delayed_job to infringe the single responsibility principle to add hooks for delayed_job on their own objects? I think this is something to be taken into consideration, unless the project roadmap sees the use of `delay` having less priority.

**Comment by albus522** [comment]
It is not delayed job's responsibility to implement your object's hooks. The method you are calling is on the object, the logic living there really isn't a problem. If you really want single responsibility, you should be creating custom jobs to encapsulate the work to be done.

If you really want some hook around all jobs use
```
Delayed::Worker.lifecycle.before(:perform) do |job|
  # whatever you want
end
```
