### ISSUE TITLE
undefined method `bytesize' for #<DelayedJob:0x007f46823b47f8> (NoMethodError)

### ISSUE THREAD

**Issue by resistorsoftware** [collectiveidea/delayed_job#784]
Something is up with ActiveModel 4.2 and DelayedJob. 

Cannot seem to access the handler text without throwing this error. DJ 4.0.6

**Comment by albus522** [comment]
What is the full stack trace?

**Comment by resistorsoftware** [comment]
Unfortunately this is beyond me, Heroku is not dumping much of use to me. A brief gist is here:

https://gist.github.com/resistorsoftware/ac4351616b729dcc224c

All I wanted to do was inspect the handler to get a couple of precise bits of info out of. Serialized in the handler was an url and some object I needed... wrapping any calls that access the DJ itself in a rescue block never trigger... hard for me to understand where the real issue lies.

**Comment by betamatt** [comment]
This looks like a bug in how you're attempting to render the DJ object with sinatra.

**Comment by resistorsoftware** [comment]
Really? How I am trying to render an object? So this is crazy? 

    dj = DelayedJob.first
    stuff = YAML.load(dj.handler)
    puts 'igloo loveshack' if stuff.url == 'fizz buzz.whatever.com' 

Not sure why I am wrong there.. but that code trigger the blowing of chunks as a small example.

**Comment by albus522** [comment]
`DelayedJob` is not defined by our gem. We use `Delayed::Job`, so I have no idea where with is coming from.

**Comment by resistorsoftware** [comment]
I am sorry. To be more explicit. When one uses the Ruby gem called ActiveRecord, it wraps objects around database tables for people that cannot write SQL. I use it for convenience. One can create a class that acts as a model to database table. In my case, I have a model called DelayedJob, that allows me to iterate instances of Delayed Jobs. That is what I did. 

When I make a new Delayed Job though, I use this gem called delayed_job, and the call is indeed Delayed::Job.enqueue or for that matter, anything Delayed::Job. 

Again, sorry for the confusion. When I access instances of delayed jobs, they blow chunks on this byte size issue, which seems to stem from something in ActiveModel 4.2 which is perhaps the real culprit.

**Comment by resistorsoftware** [comment]
I honestly thought that the problem somehow lies in DJ since the trigger for this error seems to be from trying to get a bytesize on a string, and the strings I am touching are DJ handlers. I am sorry if the true problem might lie somewhere else like in ActiveModel which is some new code I have never seen before released by the Rails dudes for their whatever needs. I am using as little as possible from Active* code... but in my Sinatra codes... I do use ActiveRecord when perhaps I should use something better...

**Comment by albus522** [comment]
That error is not trying to get the bytesize of a string. It is trying to get the bytesize on your custom DelayedJob model. So you aren't doing what you think you are doing.

**Comment by betamatt** [comment]
Also:
```
[8] pry(main)> Delayed::Job.superclass
=> ActiveRecord::Base
```

**Comment by resistorsoftware** [comment]
I am doing what I think I am doing, but clearly there is a bug somewhere in ActiveModel that was manifesting itself as I touched on Delayed Job instances. I will move my efforts to figure it out to that aspect of things.
