### ISSUE TITLE
Bug in .delay method when used with mailer

### ISSUE THREAD

**Issue by pisaacs** [collectiveidea/delayed_job#785]
Hello, 

There appears to be a bug in the `.delay` method when used with mailer. I've confirmed this this issue through testing. When two jobs exist for the same user record, DJ somehow uses (merges/references) values from only the later record and not each 'respective' record.

Using the standard rails mailer without `.delay` does not exhibit this behavior:
``` ruby
...
self.password_reset_token = SecureRandom.urlsafe_base64
self.password_reset_sent_at = Time.zone.now

status = self.save
UserMailer.delay(queue: 'email_password').password_reset_email(self) if status # both emails reference same token
#UserMailer.password_reset_email(self).deliver if status # Rails standard mailer works as expected
status
```

Long story short: for a password reset function using DJ, both emails had the same token even though the tokens were different for both serialized user objects (i.e, in the handler column). I started researching this issue after a second incident (spanning over a few months) where a user reset his/her password and ended with two duplicate password reset emails. 

My Gemfile/setup:
``` ruby
ruby '2.1.5'
gem 'delayed_job', '4.0.4'
gem 'rails', '4.1.8'
```

``` ruby
--- !ruby/object:Delayed::PerformableMailer
object: !ruby/class 'UserMailer'
method_name: :password_reset_email
args:
- !ruby/object:User
  attributes:
    id: 101
    email: blahblah@gmail.com
    password_reset_token: vZYIB15wYwoDFv4M7HN1uQ
    password_reset_sent_at: 2015-02-21 15:08:00.081758000 Z
 	...
    updated_at: 2015-02-21 15:08:00.092050000 Z



--- !ruby/object:Delayed::PerformableMailer
object: !ruby/class 'UserMailer'
method_name: :password_reset_email
args:
- !ruby/object:User
  attributes:
    id: 101
    email: blahblah@gmail.com
    password_reset_token: bfwYWRacJBqN01GFDrdcjg
    password_reset_sent_at: 2015-02-21 15:08:00.139158000 Z
    ....
    updated_at: 2015-02-21 15:08:00.144397000 Z
```

However, both emails ended up having the same link.  `http://localhost:3000/password_resets/bfwYWRacJBqN01GFDrdcjg/edit`

**Comment by albus522** [comment]
This is not a bug. We ignore the data in an ActiveRecord object and always load it from the database.

**Comment by pisaacs** [comment]
Thanks @albus522. Are there advantages to this method? I can think of a few examples where this would adversely relay the incorrect data to a recipient (in billing situation or say even in a scenario where an admin is changing the account status of a user - pending, approved, active...). The issue would easily and commonly arise if the mail service is down, and multiple user emails are queued up. 

If this is a 'wontfix', then perhaps we should add a note in the 'Queuing Jobs' section to further clarify how `.delay` really works.

**Comment by betamatt** [comment]
Not sure why you'd ever want to send an outdated password reset token, but...

As a rule, I only delay with scalar values. That way I don't have to trust DJ to have any particular semantics with regard to how objects get rehydrated. It's also much more compatible with other queueing implementations, produces smaller db records, and works with all DJ/Ruby version combinations.

So, if you're sending mail to a user, the mailer should accept a user id, not a User object. If there's a value at a specific moment that you need to capture then you include it at that time. Think of your job as an external API, not a method call on one of your models.

Ex: `UserMailer.delay(queue: 'email_password').password_reset_email(:user_id => self.id, :token => self.password_reset_token)`

**Comment by pisaacs** [comment]
Thanks @betamatt. Just be clear, my end goal isn't to send outdated password reset tokens but rather to understand how DJ queues and processes objects as the output was an unexpected behavior (until it was mentioned ActiveRecord object data is ignored). I'm not sure how many others are aware of this. 

How about the scenario where an admin changes a user's status from pending to approved to active, and the mail service is down? Once the mail service is back up, the recipient would get 3 emails saying all saying your status changed to active, to active, and to active (vs. to pending, to approved, to active). 

I like your example with passing in values into the mail service. However, the 'Queuing Jobs' doesn't describe `.delay` in this way.

**Comment by albus522** [comment]
Asynchronous programming is a very hard problem. The approach we have taken ensures we are always executing against the latest data. This is also how the new features introduced in ActiveJob work.

There are ways to be surprised no matter how you decide to handle these objects.
