### ISSUE TITLE
Job failed to load: undefined method `load_dj' for Syck:Module. 

### ISSUE THREAD

**Issue by manjunath-nm89** [collectiveidea/delayed_job#787]
Submitted a job and ran a DJ worker and the job failed with an exception `Job failed to load: undefined method 'load_dj' for Syck:Module. `

##### This is my configuration

- delayed_job version - 4.0.6
- delayed_job_active_record - 4.0.3
- Rails - 3.1.12
- YAML ENGINE: `YAML::ENGINE.yamler= 'syck'`

##### Exception Trace

Job failed to load: undefined method `load_dj' for Syck:Module. 
Handler: "--- !ruby/object:Delayed::PerformableMethod \nargs: \n- 198\n- 2015-02-25 01:08:41.226804 Z\nmethod_name: :set_favorite_last_accessed\nobject: !ruby/class SegmentReportQueriesController\n"

I debugged and this is what I found

The below code is from `delayed/backend/base.rb` For some reason the `def load_dj` defined in `syck_ext.rb` is not getting included.

``` ruby
def payload_object
  @payload_object ||= YAML.load_dj(handler)
  rescue TypeError, LoadError, NameError, ArgumentError, SyntaxError, Psych::SyntaxError => e
  raise DeserializationError, "Job failed to load: #{e.message}. Handler: #{handler.inspect}"
end
```

**Comment by albus522** [comment]
You don't need a new issue

**Comment by manjunath-nm89** [comment]
This is a duplicate and it is discussed on #786
