### ISSUE TITLE
Delayed Jobs logging

### ISSUE THREAD

**Issue by phoolish** [collectiveidea/delayed_job#792]
In Delayed Jobs 4.0.6, I am noticing that logs are being added to ENV log (IE stage.log or production.log) rather then defaulting to delayed_jobs.log unless I setup an initializer.  I was wondering if this was intended and, if so, when the README.md will be updated to reflect this.

Thanks.

**Comment by albus522** [comment]
Log redirection only occurs if you are using `bin/delayed_job`. The rake task does not and has never redirected the loggers.

**Comment by phoolish** [comment]
@albus522 Apologies for the miscommunication, but I am starting delayed_jobs with `bin/delayed_job`.

**Comment by albus522** [comment]
We have not changed anything. The logs are updated as part of https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/command.rb#L126
but if some other library update changed how the logs files are used then the log files may not be open when https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/command.rb#L116 is run and won't be updated by the `after_fork`

**Comment by phoolish** [comment]
Thanks for the explanation.  I'll see what other library might be causing the problem.
