### ISSUE TITLE
@ is not allowed as an instance variable name

### ISSUE THREAD

**Issue by danhunter** [collectiveidea/delayed_job#793]
Getting a `@' is not allowed as an instance variable name` error when trying to invoke a job, the method arguments include an instance of my User model. The id column of the users table has a not null constraint, which appears to be preventing YAML (with psych) from parsing the job handler. See shortened example below:
 
```
YAML.load("--- !ruby/object:Delayed::PerformableMethod
args:
- !ruby/object:User
  attributes:
    :attributes:
      id: '1'
    :column_types_override:
      id: &1 !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQLAdapter::OID::Integer {}
    :column_types:
      id: !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQLColumn
        null: false")
```

Ruby 2.1.2p95
Rails 4.1.3
delayed_job (4.0.4)
delayed_job_active_record (4.0.2)

**Comment by albus522** [comment]
A gem you are using, that is not DJ, is adding a bunch of extra stuff to the YAML output of the AR object. By default the YAML output of an AR object only contains the attributes. You will need to find and submit a bug to that gem maintainer.

**Comment by danhunter** [comment]
Aha, thanks! I'll investigate further.

**Comment by betamatt** [comment]
You may want to convert to either delaying a class method `User.delay.action(user.id)` or using a custom job object `Delayed::Job.enqueue UserAction.new(user.id)` with only scalar arguments such as the user's id. That way you can dodge the whole issue of encoding arbitrary objects.

**Comment by danhunter** [comment]
Thanks betamatt, I converted to sending IDs to avoid the problem. But will try and figure out which gem is screwing with my yaml output regardless.
