### ISSUE TITLE
Worker for nil queue?

### ISSUE THREAD

**Issue by machisuji** [collectiveidea/delayed_job#796]
Is it possible to have a worker that exclusively works off jobs that don't have a value for `queue` (i.e. `nil`)?

**Comment by betamatt** [comment]
Yes, by  setting a default queue name. `Delayed::Worker.default_queue_name = 'default'`

**Comment by machisuji** [comment]
The jobs are already created, though. :(
So I suppose the only way is to go through the records and set the queue to my default queue name by hand then.

**Comment by betamatt** [comment]
Correct. `Delayed::Job.where(:queue => nil).update_all :queue => 'default'`

**Comment by machisuji** [comment]
Alright, thanks!
