### ISSUE TITLE
Stopping multiple workers doesn't work with newer versions of daemons gem

### ISSUE THREAD

**Issue by ratdaddy** [collectiveidea/delayed_job#798]
It appears that changes to the daemons gem (versions 1.2.x) have broken `bin/delayed_job stop` if multiple workers were started via `bin/delayed_job -n # start`. In the newer daemons gem when it starts multiple processes it appends `_num#.pid` to the job name and now looks for that same pattern when stopping a group. Delayed job generates individual starts and thus doesn't follow this convention.

With the newer gem a subsequent `bin/delayed_job stop` has no output and doesn't stop any of the workers. Status and restart are similarly broken. This could cause serious problems for users not aware of the problem with older workers still running after a stop/start or restart sequence.

I also noticed that delayed_job doesn't depend on the daemons gem and given how coupled it appears to be to the behaviour of that gem.

I think the easiest fix is to match the `_num#.pid` naming convention when delayed_job starts multiple workers. This is still compatible with older versions of the daemons gem (at least for 1.1.9) as the pid file pattern name used to be more permissive than it is now.

Alternatively, daemons' `run_proc` could be called with the `multiple` flag to make full use of its pidfile naming conventions.

I'd be happy to submit a PR with a fix but would like to hear your thoughts on it first and what, if any, testing you'd like to have created for it (currently I don't see any testing for the command-line stuff other than for the pool option).

**Comment by mikechau** [comment]
We were just bitten by this bug, noticed a large amount of memory usage and this was from workers failing to stop when we redeploy. :(

How are you handling it currently @ratdaddy ? Downgrade to a lower version of the daemons gem?

**Comment by ratdaddy** [comment]
@mikechau, yes, we locked the daemons gem to 1.1.9 with:

```
gem 'daemons', '1.1.9'
```

in our `Gemfile`

**Comment by caesarsol** [comment]
hello, I had this problem too, I'm inheriting a project and I'm a little scared in changing gem version since the code is not tested :) 
I resolved with this Capistrano hack:

    namespace :delayed_job do
      task :stop_checking, :roles => :delayed_job do
        pidfile = File.join(shared_path, "pids", "delayed_job.pid")
        logfile = File.join(shared_path, "pids", "delayed_job.activity.log")
        delayed_job_pid = capture("[ -f #{pidfile} ] && cat #{pidfile} || echo").strip
        logger.debug "The pid of delayed_job is #{delayed_job_pid.inspect}"
        if delayed_job_pid.empty?
          logger.important "It appears no delayed_job is running (unexistant or empty #{pidfile})."
          logger.important "We are going to start it anyway, so don't worry."
          next
        end
        run "echo [`date`] #{delayed_job_pid} stopping >> #{logfile}"
        delayed_job.stop
        run <<-CMD.compact
          until [ `ps -fp #{delayed_job_pid} | wc -l` -eq 1 ]; do
            echo "Waiting for delayed_job with PID #{delayed_job_pid} to end...";
            sleep 2;
          done;
          echo "Ended";
        CMD
        run "echo [`date`] #{delayed_job_pid} stopped >> #{logfile}"
      end
    end

in brief, it tries to kill any running delayed_job process with an `until` cycle. I use it instead of `delayed_job:stop`.

I'm not so sure about this code, even if it's working so far. do you see any problems in this approach?

thanks!

**Comment by andrewhaines** [comment]
I've got a slightly different problem (I think). Even though I'm able to start/stop/restart workers, it seems that delayed_job won't execute the latest code. In other words, I'm changing scripts (in an ActionMailer template, in my case) and they're firing via delayed_job from a significantly older version of the file.

Maybe I'm in the wrong place, but thought I'd mentioned it here in case anyone else has experienced something similar.

**Comment by cthielen** [comment]
The 'daemons' folks thinks it's a delayed_job fix: https://github.com/thuehlinger/daemons/issues/40

**Comment by synth** [comment]
Any idea on what the accepted resolution is for this? I'm definitely hitting this issue with DJ v4.1.2 and daemons v1.2.3

**Comment by ratdaddy** [comment]
At this point I think the only thing you can do is pin the daemons gem to 1.1.9 as I mentioned above.

**Comment by synth** [comment]
Bummer,  I needed other fixes in daemons in newer releases :(

**Comment by deneuxa** [comment]
@ratdaddy  Same problem here
switch back to daemons 1.1.9 fixed it

@andrewhaines yes I have the exact same problem. It seems "normal" to me, as the instance of delayed Job is loader with the old path of the rails application and code remain in memory ?

**Comment by uberllama** [comment]
I see a demons PR but not a DJ PR. Is this still an issue?

**Comment by CarlosCD** [comment]
Yes, @uberllama , I've just run into this last night. This is about delayed_job creating pid files that don't conform with what the last versions of the daemons gem expects. So it fails when there is more than one worker.

`bin/delayed_job` can pass a file format switch to daemons, so there is a very easy fix suggested here: <https://github.com/thuehlinger/daemons/pull/72>

I am to sure  why the generator has not been fixed yet.

**Comment by albus522** [comment]
Closing stale
