### ISSUE TITLE
Delay only once - singleton jobs.

### ISSUE THREAD

**Issue by dblock** [collectiveidea/delayed_job#800]
We use delayed job to continuously index in the background, for example with ElasticSearch. Every time an instance changes, we queue a job. 

That adds up quickly. We'd like to queue a job, and not queue the same one again as long as there's already a queued one. We use MongoDB, so this is even possible atomically with an `upsert`, however this is rarely needed since delayed jobs in our case get queued after something is saved, so if we see something still queued, it will for sure pickup the update we just made.

Any suggestions regarding an implementation of something like this? At the least we want to override `.delay` to check for an existing job.

```ruby
where(handler: options[:payload_object].to_yaml).any?
```

**Comment by JoshMcKin** [comment]
Use a queue and check to see if any jobs exists in that queue before creating the job.

**Comment by dblock** [comment]
I am thinking of implementing this as a proper `delayed_job` extension. Maybe `Foobar.delay.once.somethibng`?

**Comment by dblock** [comment]
@betamatt You just closed this? Am I not posting this in the right place? I just want a place to discuss this.

**Comment by albus522** [comment]
Discussions usually belong on the mailing list. http://groups.google.com/group/delayed_job

You could also submit a PR to center discussion around.

**Comment by dblock** [comment]
Thanks, I opened https://github.com/collectiveidea/delayed_job/pull/801/files with some working code.
