### ISSUE TITLE
cannot load such file -- delayed_job in production

### ISSUE THREAD

**Issue by kunalchaudhari** [collectiveidea/delayed_job#804]
In production getting this error: cannot load such file -- delayed_job

rails 4.2
ruby 2.0

**Comment by albus522** [comment]
What web server are you using?

**Comment by kunalchaudhari** [comment]
Unicorn

**Comment by albus522** [comment]
I am going to guess you are deploying via capistrano and doing "zero downtime restarts". Bundler and unicorn don't get along well. Unicorn is probably stuck on a very old Gemfile. I can't remember what the long term fix is, but shutting down and starting up unicorn should correct things. And then google for issues with unicorn and bundler

**Comment by kunalchaudhari** [comment]
Okie. Thanks
