### ISSUE TITLE
Duplicate workers

### ISSUE THREAD

**Issue by danielristic** [collectiveidea/delayed_job#807]
Hi,

Since I'm using the latest version of delayed jobs (4.0.6), I sometimes find that workers are duplicated:

I have 3 workers haldeling different queues that I start with something like `delayed_job start -i n` where n is an integer between 1 and 3. As a result when I use the `ps` command I see something like 

```
delayed_job.1
delayed_job.2
delayed_job.3
```

In the past 30 days, I frequently find duplicate workers labeled with the same integer but different pids. When this happens, the regular `delayed_job stop -i n` command does not work and I have to manually kill the duplicated workers.

**Comment by mikechau** [comment]
Try the following: https://github.com/collectiveidea/delayed_job/issues/798#issuecomment-96815090

**Comment by danielristic** [comment]
Thanks! Adding `gem 'daemons', '1.1.9'` to the Gemfile did the trick for me!

**Comment by albus522** [comment]
Closing stale
