### ISSUE TITLE
DJ stops polling a named queue

### ISSUE THREAD

**Issue by norman** [collectiveidea/delayed_job#808]
I'm sorry to post a vague bug report (my pet peeve on the projects I maintain) but I've been researching this for the better part of two days and am utterly baffled by some behavior we're seeing in one of our applications at work.

The behavior I have observed is that a Delayed Job worker will sometimes stop polling a named queue and only begin polling again after a restart. I can verify this by turning on statement logging in our Postgres database and tailing the log to look for the polling queries.

This occurs even though I can verify through our logs that no job is being processed and blocking polling. I can wait longer than the job's timeout too - it doesn't time out and start polling again, I can only make this happen by restarting DJ. Using `ps` I can confirm all the worker processes are present; they're just not... working.

Here comes a dump of what I think may be some information about our application:

* Rails 4.0.12
* Delayed Job 4.0.4
* ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-linux-gnu]
* Ubuntu 12.04.5 LTS (Precise Pangolin)

Our configuration initializer looks like this:

```ruby
Delayed::Worker.max_attempts = 6
Delayed::Worker.max_run_time = 5.hours
Delayed::Worker.destroy_failed_jobs = false
```

We also have some very long-running jobs and use a  custom lazy job rescheduler:

```ruby
module LazyDelayedJobRescheduler
  # Instead of DJ's default backoff of N ^ 4 + 5, we use N ^7  + 300, which results in this schedule
  #  Attempt	Seconds	Minutes	Hours
  #  1        301     5.02    0.08
  #  2        428     7.13    0.12
  #  3        2487    41.45   0.69
  #  4        16684   278.07	4.63
  #  5        78425   1307.08	21.78
  def reschedule_at(current_time, attempts)
    current_time + (attempts ** 7) + 300
  end
end
```
Delayed job is started via Foreman/Upstart using the Rake task `bundle exec rake jobs:work QUEUES=crawl`. The "crawl" queue uses 10 workers in production, and 1 worker in our alpha environment. Because of the difference in concurrency, in production we'll notice the queue begin to drain more and more slowly as more workers stop polling over time, while in alpha we'll just see job processing stop at some point.

I don't observe any log messages from Delayed Job indicating a failure or error condition from within DJ itself. I've looked through the worker source to find what messages it might publish on error conditions and don't see any of them in my logs.

Also, this happens "randomly" as in, I can't predict how long the workers will process jobs successfully and don't notice anything unusual in our logs or monitoring when it happens.

Again, sorry to throw my hands up in the air and ask for help like this without more specifics. I'd be grateful for any suggestions you might be offer on how I can research this better and discover what the problem is on my own. I would not be surprised at all if the fault were entirely my own, but do think there's a non-zero chance it's a DJ bug.

**Comment by albus522** [comment]
My initial thought is that the polling "stops" because a polling query doesn't return and hangs the process. Check to see if you can identify any running queries or error logs from your database. It may have other clues as well.

**Comment by norman** [comment]
Thanks for the reploy, @albus522. I've cranked up logging on the database server and am waiting for the issue to occur again.

**Comment by norman** [comment]
I've discovered the source of the problem: our worker tried to serialize a Capybara::Session object to JSON in order to send debugging information to Rollbar, which with the version of Capybara Webkit we're using causes a hang. I think there's nothing here for Delayed Job to fix - the worker's Ruby VM is totally locked up so the worker can't exit without a separate reaper process or thread. I'll close this for now.
