### ISSUE TITLE
delayed_job (or rather, the daemons library it uses) breaks rbnacl

### ISSUE THREAD

**Issue by aetherknight** [collectiveidea/delayed_job#809]
## Environment
- Ruby version: 2.0.0p645 (and we also tested under 2.1.5)
- delayed_job version: 4.0.6
- daemons version: 1.1.9
## Problem

Running a delayed_job worker breaks rbnacl's `RbNaCl::Random.random_bytes(32)` pretty horribly --- it causes libsodium, a C library that rbnacl wraps, to call `abort()` (which sends a SIGABRT to the process) after it tries to read from a previously-opened file descriptor that refers to /dev/urandom.
## Root-Cause Analysis

Upon investigating, we have discovered a few things.

rbnacl, upon being `require`d [initializes itself](https://github.com/cryptosphere/rbnacl/blob/master/lib/rbnacl.rb#L88-L91), which also causes it to open the mentioned file descriptor. This usually happens before delayed_job daemonizes --- e.g., when it loads a Rails app and all of its Gemfile dependencies.

When we run the delayed_job script to daemonize the worker, delayed_job's `lib/delayed/command.rb` winds up calling `Daemons.run_proc`.

This causes the Daemons gem to eventually close **ALL FILE DESCRIPTORS!!!!111** (except for 0, 1, and 2, which it appropriately redirects later) [link](https://github.com/thuehlinger/daemons/blob/master/lib/daemons/daemonize.rb#L132-L134). (apologies, it is late on Friday):

``` ruby
3.upto(8192) do |i|
  IO.for_fd(i).close rescue nil
end
```

This specifically includes file descriptors opened outside of the Ruby runtime. However, there is no way to configure the Daemons gem to _not_ do this.

The consequence is that Daemons closes rbnacl's file descriptor unnecessarily, which causes libsodium to discover that its file descriptor is no longer valid, and thus abort. There is no need to close this file descriptor, and it is not Daemons' place to close this file descriptor (not to mention, it will close the file descriptor of every other C library, and of all log files that were opened before daemonizing).
## Possible Solutions
- File a bug against daemons and hope they fix it.
- Use a different daemonizing library that does not aggressively close all the things. Or at least one that lets you disable closing all file descriptors.
- Monkey-patch daemons so that `Daemonize.close_io` is a noop.
- We could try to defer loading of rbnacl until after daemonizing, but we would still have to do this for every other piece of code in our application that opens a file descriptor before daemonizing (such as logging facilities)

**Comment by betamatt** [comment]
Most of the time the solution is to re-open the resources in the child process using the `after_fork` hook. You're correct that you have to do it for everything like logging, database connections, and file handles.

**Comment by albus522** [comment]
Closing stale
