### ISSUE TITLE
lifecycle.before(:enqueue) not working?

### ISSUE THREAD

**Issue by stephenreid321** [collectiveidea/delayed_job#810]
Hi guys,

I'm having problems with `lifecycle.before(:enqueue)`. Whilst other lifecycle callbacks seem to fire, enqueue doesn't. Is anyone experiencing this?

```
module Delayed
  module Plugins
    class Test < Plugin
      callbacks do |lifecycle|
        lifecycle.before(:enqueue) do |job|          
          raise 'just testing' # never reaches this
        end
      end
    end
  end
end

Delayed::Worker.plugins << Delayed::Plugins::Test
```

**Comment by bencolon** [comment]
Same for me with the latest release 4.0.6. 
Fixed on master by this commit I guess : https://github.com/collectiveidea/delayed_job/commit/f57d0aa106759510fd811879fb2de13bcdabf875

**Comment by brian-vogogo** [comment]
In 4.0.4 (and I think 4.0.6), running `Delayed::Worker.new` will cause the plugins to load. The `:enqueue` callback seems to trigger.

**Comment by albus522** [comment]
Closing stale
