### ISSUE TITLE
Delayed jobs using outdated code after a restart.

### ISSUE THREAD

**Issue by mariodarco** [collectiveidea/delayed_job#811]
## Environment:
Rails 4.2.1 and delayed_job 4.0.6.

## Problem:
I recently pushed some new code to my project, and after deploying and restarting the delayed jobs, those were still attempting to use the old code, which was of course crashing because of the recent changes in the database.

Tried to redeploy twice
- bin/delayed_job stop
- bin/delayed_job start
- bin/delayed_job restart

but kept failing, and only a full server restart fixed the issue.

Now, some investigation lead me to this old issue: https://github.com/collectiveidea/delayed_job/issues/3
I can see some workarounds there, but since its a 2009 issue I am not sure those are still the right way to proceed, and I wold like to know in general which is the suggested fix to this problem. Thank you.

**Comment by mikechau** [comment]
Have you tried locking the `daemons` gem to 1.1.9?

See: https://github.com/collectiveidea/delayed_job/issues/798#issuecomment-96815090

#798

**Comment by mariodarco** [comment]
That gem has never been locked in our system, and it was 1.1.9 up to 9 days ago, when we did a general gem update (it's now 1.2.2).

I guess this is the reason why we never had this problem before the gem update.

Thanks for your help.

**Comment by andrewhaines** [comment]
@mariodarco just checking to see if you did, in fact, discover that the gem lock worked as a solution. I'm having the same troubles; although I've tried locking the deamons gem to no avail. Hoping you have a quick update on what worked for you!

Thanks.

**Comment by chrismear** [comment]
@andrewhaines (I've been working on the same code as @mariodarco) We did lock to daemons 1.1.9, which I believe fixed this particular problem of DJ workers not getting stopped and started properly.

We were since able to upgrade to daemons 1.2.3, which includes [this fix](https://github.com/thuehlinger/daemons/pull/29), and our DJ restarts have also been working okay on that version.

**Comment by nomasprime** [comment]
Think I'm having this issue in production.

So, is the recommended way to use this gem in a deployed app is to use another gem? Seems fishy to me.
