### ISSUE TITLE
Sending mail delay dont do nothing but its records in delayed_job table.

### ISSUE THREAD

**Issue by michon** [collectiveidea/delayed_job#813]
Y have a class called EnvioCorreoJob. This class enqueue de jobs to send emails from some people.

```
class EnvioCorreoJob
    def envia_correo(envio)
        en = Envio.find(envio)
        frecuencia = 7215 
        en.clipotcategoria.clientespotenciales.each do |cli|
            Rails.logger.debug '--------------------------------------------------------------------'
            Rails.logger.debug ' bucle ' + cli.correo 
            Rails.logger.debug '--------------------------------------------------------------------'

            Noticia.delay(run_at: frecuencia.seconds.from_now).envios(cli.correo,en.chasqui.titulo, en.id).deliver
            frecuencia = frecuencia + 15
        end
    end
end
```

when i execute this code in my delayed_job table appears records, but when y execture "rake job:work" the records in de table don't disappear, and don't send de mails.

NOTIFICACIONES MAILER

```
def envios(correo, titulo, envio)
    @envio = Envio.find(envio)
     mail(to: correo, subject: titulo)
end
```

extract of de table delayed_job

| 876 | 2015-05-19 13:02:40 | --- !ruby/object:Delayed::PerformableMailer
object: !ruby/class 'Noticia'
method_name: :envios
args:
- arbol.test@gmail.com
- El Chasqui de Danfi
- 980191076
        |

What's hapend?

**Comment by albus522** [comment]
If it was actually executed and is still in the table, that means it errored. You will see the error in the `last_error` column

**Comment by michon** [comment]
thanks albus522, but I think it's not the problem. May be somthing relation with time UTC and Time in Spain, something about TimeZone? 

DATE COMMAND ON THIS SERVER
$: date
mar may 19 18:02:37 CEST 2015

SELECT FROM DELAYED_JOB TABLE
select id, run_at,  last_error from delayed_jobs order by id;
+-----+---------------------+------------+
| id  | run_at              | last_error |
+-----+---------------------+------------+
| 877 | 2015-05-19 17:01:26 | NULL       |
| 878 | 2015-05-19 17:01:56 | NULL       |
| 879 | 2015-05-19 17:02:12 | NULL       |
| 880 | 2015-05-19 17:02:27 | NULL       |
+-----+---------------------+------------+
4 rows in set (0.00 sec)

**Comment by albus522** [comment]
Time translation is done by ActiveRecord and it always stores data in UTC.

Make sure your rake command is run against the correct environment. You may need to add a `RAILS_ENV=your_env_here` before `rake jobs:work`.

Also note that the rake task is `rake jobs:work` not `rake job:work`

**Comment by michon** [comment]
I run it in console (rake jobs:work).

I think it's the timezone, because Delayed_job send the emails 2.hours later, the jobs are in de table 2 hours and then send it without fails
I probe it,  this is Worker display at 19:01:26

[Worker(host:web6 pid:6361)] 3 jobs processed at 3.2481 j/s, 0 failed
[Worker(host:web6 pid:6361)] Job Noticia.envios (id=877) RUNNING
[Worker(host:web6 pid:6361)] Job Noticia.envios (id=877) COMPLETED after 0.2448
[Worker(host:web6 pid:6361)] 1 jobs processed at 3.3530 j/s, 0 failed
[Worker(host:web6 pid:6361)] Job Noticia.envios (id=878) RUNNING
[Worker(host:web6 pid:6361)] Job Noticia.envios (id=878) COMPLETED after 0.2615
[Worker(host:web6 pid:6361)] Job Noticia.envios (id=879) RUNNING
[Worker(host:web6 pid:6361)] Job Noticia.envios (id=879) COMPLETED after 0.2057
[Worker(host:web6 pid:6361)] 2 jobs processed at 3.5196 j/s, 0 failed
[Worker(host:web6 pid:6361)] Job Noticia.envios (id=880) RUNNING
[Worker(host:web6 pid:6361)] Job Noticia.envios (id=880) COMPLETED after 0.2114
[Worker(host:web6 pid:6361)] 1 jobs processed at 3.5089 j/s, 0 failed

**Comment by albus522** [comment]
Closing stale
