### ISSUE TITLE
Delayed_job in production getting errors on jobs until i start/stop

### ISSUE THREAD

**Issue by jgrannas** [collectiveidea/delayed_job#816]
I am running rails 4.2.1 with
```
gem 'daemons', '~> 1.1.9'
gem 'delayed_job_active_record'
gem 'delayed-web', github: 'thebestday/delayed-web'
```

In production, some jobs are throwing errors. I'll come into my app after a day or two, and they'll be 10 jobs in the queue, each with an error. However, i can see the error doesn't make sense and the job should have worked fine. If I rerun these queued jobs they throw the same error.

HOWEVER! If i stop, then start delayed job, and rerun these jobs they execute and complete without error. What would cause these jobs to work only after restarting delayed job?

**Comment by jgrannas** [comment]
Is there a way i could debug this? I had backed up jobs from 5/30-6/2 and just had to go into my server console and use

RAILS_ENV=production script/delayed_job stop
RAILS_ENV=production script/delayed_job start

The pid process is there when i stop it... but it takes a stop/start for the jobs that are erroring to complete. 

Any tips on how i could debug this better? I can't understand why would these jobs error, but are not erroring after a restart of delayed_job?

**Comment by albus522** [comment]
My guess would be that your workers didn't get restarted after code deploy and are running an old version of your codebase

**Comment by jgrannas** [comment]
i am using a gem for capistrano & delayed job
gem 'capistrano3-delayed-job', '~> 1.0'

I can watch it stop and start delayed job in the console output after the code deploys, so i am pretty sure it's using the latest code.

**Comment by jgrannas** [comment]
Still happening. really annoying. If i restart delayed job, these jobs will all complete without issue.

![screen shot 2015-06-15 at 1 01 57 pm](https://cloud.githubusercontent.com/assets/2011886/8165495/de4c485c-135e-11e5-81a3-a02bddacb527.png)

**Comment by albus522** [comment]
This usually happens when the mysql server restarts or otherwise cuts the connection to the process. ActiveRecord is really quite terrible about handling mysql connection problems.

**Comment by jgrannas** [comment]
My main app is using postgresql, but this issue is related to me connecting to a 3rd party MySQL database (CRM)... basically I have an abstract model setup to handle these tasks:

```
class Crm < ActiveRecord::Base
 
  self.abstract_class = true
  establish_connection(adapter: 'mysql2', host:"IP.address", username:"Web", password:Rails.application.secrets.crm_password, database:"crm")

...

end

```

I have other delayed jobs using this same connection, but it seems only related/isolated to this one task. I guess it could lose connection, but then why would it not work on retry? Is it possible that its not opening a new connection on a retry attempt?

**Comment by albus522** [comment]
You are establishing connection at the class level, which means once at startup not every run.

**Comment by jgrannas** [comment]
Ok. Can you provide insight as to why restarting only the delayed_job worker fixes the issue? i'm not restarting the app itself...

From everything I read on an abstract class, setting it up how I did was the proper approach. What would be the proper way to establish_connection on each call?

**Comment by albus522** [comment]
The error is happening in the worker. That is why restarting the worker fixes the issue.

In order to establish a connection on each call, it has to happen in the method. Everything outside the methods happens once.

**Comment by jmcbri** [comment]
> My guess would be that your workers didn't get restarted after code deploy and are running an old version of your codebase

Stupidly, I've had this problem and didn't really get it.  Was NOT thinking that the delay_job worker was dragging along the old code in its process.  That is what you're saying right?  Anyway, interestingly, when I tried "Delayed::Command.new(["restart"]).daemonize" in my Rails initializer, I end up with two delayed_jobs running.  "Restart" is not killing the old process.  I'm guessing this is NOT the proper way to do it, in which case, what is?
