### ISSUE TITLE
Code reloading breaks the app when using Jruby Rack Worker or Trinidad Worker Extension to load delayed_job

### ISSUE THREAD

**Issue by sanelson2000** [collectiveidea/delayed_job#818]
The following commit: https://github.com/collectiveidea/delayed_job/commit/e4320858ef6ae3b69fc5506c9d86cc7aa1878602

Appears to break Trinidad in development.

```
jruby -S trinidad --threadsafe -p 3000 -e development
```

I'm seeing all kinds of errors.  Mostly stuff like this:

```
A copy of ApplicationController has been removed from the module tree but is still active!
```

I am able to work around the issue by overriding `reload_app?` in an initializer to always return false.

```
# The reload breaks trinidad.  Don't try it!
module Delayed
  class Worker
    def self.reload_app?
      false
    end
  end
end
```

**Comment by albus522** [comment]
The worker should not be running in your server process. You have something configured incorrectly.

**Comment by sanelson2000** [comment]
@albus522 Sorry, I forgot to mention, I am using the Jruby Rack Worker (https://github.com/kares/jruby-rack-worker) and Trinidad Worker Extensions (https://github.com/kares/trinidad_worker_extension) to run delayed_job in a separate thread along with the server in production and development, respectively.  It is not run as a separate task.

**Comment by sanelson2000** [comment]
Perhaps the best course of action for this is to just document the workaround (or better yet add a configuration option to disable code reloading and document it) in the README to disable code reloading when running delayed_job in a thread using one of the above workers.

**Comment by Loremaster** [comment]
@sanelson2000 +1 for the flag to disable reloading!

**Comment by craigcbrunner** [comment]
@sanelson2000 good god thank you for this patch, this caused such crazy and random errors but only like once every few page reloads and I could not figure out what was going on, this monkey patch solved it for me.

**Comment by albus522** [comment]
Closing stale
