### ISSUE TITLE
action_mailer reply_to field doesn't work when using delayed_job

### ISSUE THREAD

**Issue by alfie-max** [collectiveidea/delayed_job#819]
ReplyMailer
```
def reply_mail(sub, body, to_email, from_email)
    @subject            = sub
    @body               = body
    @to_email           = to_email
    @from_email         = from_email

    mail(:to => @to_email,
         :from => @from_email,
         :reply_to => @from_email,
         :subject => @subject) do |format|
      format.text
      format.html
    end
  end
```

Which is called later in a model as,
```
ReplyMailer.delay.reply_mail(sub, body, to_email, from_email)
```

This sends out a mail but it doesn't have a reply-to field.
Which works absolutely fine if i am not using delayed_job.

**Comment by albus522** [comment]
Delayed Job has absolutely no impact on the mail process. I suggest making sure the right arguments are set in the job. Also stop and start the worker to make sure you are actually running the code you think you are running.
