### ISSUE TITLE
Action Mailer emails not being sent

### ISSUE THREAD

**Issue by harryj** [collectiveidea/delayed_job#827]
So I'm trying to use delayed job with action mailer in my app and I've tested both locally and production and the email job is created and executed but the email is not being sent.

When I don't use delayed job and just use .deliver it works just fine.

The code for sending the email:

UserMailer.delay.followed_you(user)

In my console when I run Delayed::Job.all I see the job being enqueued. Then when I run rake jobs:work I see the job being executed successfully:

[Worker(host:f595047e-4de8-4247-8cdb-098774814694 pid:3)] Starting job worker [Worker(host:f595047e-4de8-4247-8cdb-098774814694 pid:3)] Job Class#followed_you (id=10326) RUNNING [Worker(host:f595047e-4de8-4247-8cdb-098774814694 pid:3)] Job Class#followed_you (id=10326) COMPLETED after 0.1035 [Worker(host:f595047e-4de8-4247-8cdb-098774814694 pid:3)] 1 jobs processed at 4.4194 j/s, 0 failed

But the email is never sent. My guess is it has to do with SMTP settings not being loaded in the delayed job? Any help would be appreciated. I'm using rails 4.0.13 and delayed job 4.0.2

Does it have something to do with RAILS_ENV?

**Comment by harryj** [comment]
I tried upgrading delayed job to 4.0.6 and now the logging is changed to:

[Worker(host:Kathys-MacBook-Air-2.local pid:62981)] Starting job worker
[Worker(host:Kathys-MacBook-Air-2.local pid:62981)] Job UserMailer.followed_you (id=686) RUNNING
[Worker(host:Kathys-MacBook-Air-2.local pid:62981)] Job UserMailer.followed_you (id=686) COMPLETED after 0.0572
[Worker(host:Kathys-MacBook-Air-2.local pid:62981)] 1 jobs processed at 3.7405 j/s, 0 failed

But it seems like the email is still not being sent

**Comment by jpbullalayao** [comment]
I'm a user of DelayedJob, and have the same issue. Were you able to figure this out @harryj?

**Comment by henrydjacob** [comment]
facing the same issue.
