### ISSUE TITLE
Pool workers and default queue

### ISSUE THREAD

**Issue by x3mka** [collectiveidea/delayed_job#828]
Is it possible to run X workers for the default queue and Y workers for a named queue?

script/delayed_job --pool=default:X --pool=named:Y start  doesn't pick jobs from default queue (I think it expects queue name be explicitly set to 'default')

script/delayed_job --pool=named:Y --pool=*:X start   runs X+Y workers for 'named' queue.

**Comment by alkuzad** [comment]
We have found similar problem, the solution is pretty simple. Write plugin that calls 

```ruby
lifecycle.before(:enqueue) do |job|
  next if job.queue
  job.queue = 'global'
end
```

and 
```ruby
lifecycle.before(:execute) do |worker|
  next if worker.queues != []
  worker.queues = ['global']
end
```
and add it to config/initializers with 
`Delayed::Worker.plugins << Delayed::Plugins::StrictGlobalQueue::Plugin`

**Comment by Yegorov** [comment]
Since [3.0.4](https://github.com/collectiveidea/delayed_job/blob/master/CHANGELOG.md#304---2012-11-09) version ([commit](https://github.com/collectiveidea/delayed_job/commit/eecaa33f50f8ad09f134efbdab70581708b8aaf4)) of DJ you can specify a default queue name.
For example:
```ruby
# config/initializers/delayed_job_config.rb
Delayed::Worker.default_queue_name = 'default'
```

**Comment by albus522** [comment]
Closing stale
