### ISSUE TITLE
rake jobs:clear causes "Can't connect to local MySQL server through socket '/tmp/mysql.sock'"

### ISSUE THREAD

**Issue by blackpond** [collectiveidea/delayed_job#830]
When I try running `rake jobs:clear` I get "Can't connect to local MySQL server through socket '/tmp/mysql.sock"

My database.yml file has has the socket set to the right location, but rake jobs:clear keeps trying to use /tmp/mysql.sock - is there a way I can force it to use /var/run/mysqld/mysqld.sock ?

Thanks!

**Comment by albus522** [comment]
Add RAILS_ENV=correct_env_here to the command
