### ISSUE TITLE
Locked but never processed

### ISSUE THREAD

**Issue by stephenbaidu** [collectiveidea/delayed_job#832]
I have jobs that get locked but never gets processed. Am using Rails 4.2.1 and running Delayed::Job.first in rails console gives this:
```
#<Delayed::Backend::ActiveRecord::Job id: 28, priority: 0, attempts: 0, handler: "--- !ruby/object:ActiveJob::QueueAdapters::Delayed...", last_error: nil, run_at: "2015-06-27 23:24:17", locked_at: "2015-06-28 00:56:22", failed_at: nil, locked_by: "host:56035604a366 pid:134", queue: "company_setup", created_at: "2015-06-27 23:24:17", updated_at: "2015-06-27 23:24:17">
```

Am using docker, when this happens, I have to restart the docker container before this particular job can get processed.

**Comment by Fivell** [comment]
@stephenbaidu , did you fix this somehow?

**Comment by entei** [comment]
@Fivell Try to check other running jobs, perhaps they have a higher priority

**Comment by Fivell** [comment]
@entei , @stephenbaidu , it was happening for me if job ran out of memory and process was killed. Is it expected behaviour ?

**Comment by albus522** [comment]
If the process dies at the system level, there is nothing DJ can do to unlock the job. In this case, DJ considers the job "unlocked" after max_run_time has expired.

Off the top of my head unrecoverable things include out of memory, SIG_KILL (kill -9), out of disk space (sometimes recoverable), and SEG_FAULT (yes those can occur in ruby). For these errors, the process execution is halted and no cleanup occurs.

**Comment by stephenbaidu** [comment]
@Fivell My problem was due to the fact that I was using [apartment](https://github.com/influitive/apartment) gem. So I stopped using delayedjob.

**Comment by gregblass** [comment]
@albus522 So what is the best practice here if you've got delayed job workers restarting due to memory consumption, and but jobs are sitting around locked? It would effectively hang the software on the client's end. Surely there must be a way to have the restarted delayed job worker pick up where it left off?

**Comment by albus522** [comment]
Pick up what where it left off? That is a very arbitrary concept and resuming where you left off in a giant process is not what DJ is built for. If you do individual process management and give each process a consistent identifier, it will pick up the job it was working on when it died. However, it will just run the job again, from the beginning and presumably end up at the same memory limit again. To fix what you are talking about you need to fix your memory issue.

**Comment by gregblass** [comment]
Got it. I'm exporting to excel, and I've got like ~10,000+ records exporting. They're a `Property` model, and I'm doing `@property.all.each do |property| (export exel row stuff here) end`. I'm wondering if I can break that down into batches. I know there's a 'find_in_batches'.

Alas, this isn't a discussion for delayed job at the end of the day. Thanks for responding @albus522.

**Comment by gregblass** [comment]
@albus522 If you're keen on this stuff any wanna do a paid codementor session, let me know! :)

**Comment by albus522** [comment]
`find_in_batches` is probably your best bet, but that has the limitation of overriding any order that you set. If you need a specific order, you could do some tricky stuff with pulling just a list of the ids you need ordered, break the list up, and load groups of the data based on the ids and order

**Comment by albus522** [comment]
Also certain excel libraries will hold the entire file in memory then write it out at the end while I think others will write as you go. If you can get away with CSV, you can absolutely write that as you go instead of all in memory

**Comment by gregblass** [comment]
I'm doing a FetchProperties call, which is a service object that just sets @properties = [query]

Then I'm doing:

`fetch_properties
  	xml = renderer.render(
  		template: 'reports/marketing/rep_lists/rep_list.xls.erb', 
  		locals: { job: @job, properties: @properties }
  	)`

where render is a background job rendering object.

The XLS is just an .xls.erb file that essentially uses Microsoft's XML XLS schema. Inside that I'm doing @properties.all.each do.

Not sure if any ideas come to mind for that use case. Thanks for your help!

**Comment by gregblass** [comment]
Turned out to be pretty simple - just use find_each(batch_size) and avoid any unnecessary variable creation!

**Comment by AxelTheGerman** [comment]
@albus522 Any other recommendations to handle the OOM issue? 

We sometimes get extremely large jobs that cause this issue and they get retried indefinitely - same issue was reported in #415 

My first thought was to increase the `attempts` when starting to process the job. that way they will eventually reach `max_attempts`. Can you see any negative side effects from this? (besides maybe that the attempts get counted twice for other failures. we don't care about the actual number of attempts as much as that it will eventually be canceled)

**Comment by albus522** [comment]
@AxelTheGerman unfortunately there isn't too much DJ can do automatically. You could try adding some kind of monitor that checks for jobs with run_at times that seem oddly old. Because the process runs out of memory and dies, the run_at time never gets updated. So you should be able to use that as a sort of alarm.

**Comment by jzaynal** [comment]
> If the process dies at the system level, there is nothing DJ can do to unlock the job. In this case, DJ considers the job "unlocked" after max_run_time has expired.
> 
> Off the top of my head unrecoverable things include out of memory, SIG_KILL (kill -9), out of disk space (sometimes recoverable), and SEG_FAULT (yes those can occur in ruby). For these errors, the process execution is halted and no cleanup occurs.

@albus522 we have the same issue and you're right, job only gets picked up after `Worker.max_run_time` exceeds. However, this does not take into account job-level `max_run_time` at start-up after a worker process crash. Do you know of this issue and how can we make it so job-level `max_run_time` is respected? 

We can see that the job does indeed have a lower max_run_time than default worker, so that isn't the issue.

We run in a containerised environment and sometimes due to scaling down, containers get killed that may have initiated processing a job but job remains in locked state until default max_run_time.

**Comment by jzaynal** [comment]
@albus522 we thought this repo was active and were hoping to get a response to my question above. It's been some time, should I forget about it? Or open a new issue for it?
