### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by johnnyshields** [collectiveidea/delayed_job#836]
In particular I was confused b/c the readme mentions `Delayed::Worker.delay_jobs` but it's not released.

BUT do not release before merging #815

**Comment by Jesus** [comment]
Maybe you'll find it useful to use this gem straight away from the repository. That way you won't have to wait for the maintainer to release a new version.

Check out this guide: http://bundler.io/git.html

You can use this trick to get away with your current issue. Later on, when they release the new version you can update your Gemfile again.

**Comment by johnnyshields** [comment]
@Jesus I'm aware of that, however we've gone over 8 months without a release.
