### ISSUE TITLE
undefined method `name' for nil:NilClassfor for array of images

### ISSUE THREAD

**Issue by shoaib-techverx** [collectiveidea/delayed_job#840]
Hi i am sending multiple images from paperclip in form of array and then process each image through delayed job,
my parammetrs are like ethis
"utf8"=>"✓",
 "authenticity_token"=>"7d9yFPVvfTiywcX6YRMxqtk/gg4Y+T2pS0W8TcJ0L2w=",
 "slider_image"=>{"slider_image"=>[#<ActionDispatch::Http::UploadedFile:0x007fc19561a4c8 @tempfile=#<Tempfile:/tmp/RackMultipart20150821-8626-1msvk5g>,
 @original_filename="sliderbg.jpg",
 @content_type="image/jpeg",
 @headers="Content-Disposition: form-data; name=\"slider_image[slider_image][]\"; filename=\"sliderbg.jpg\"\r\nContent-Type: image/jpeg\r\n">]}}
i am permitting attriubutes in form of array
params.require(:slider_image).permit({:slider_image=>[]})
i am getting undefined method `name' for nil:NilClass
please help

**Comment by albus522** [comment]
Not sure how this is a delayed job issue.
