### ISSUE TITLE
Delayed Job picking up jobs from all queues 

### ISSUE THREAD

**Issue by kritiagg** [collectiveidea/delayed_job#842]
Hi everyone,

I am using the following code to invoke jobs from a particular queue. But the worker is picking up jobs from other queues as well. 
QUEUE=queue_name rake jobs:work 

Any help is appreciated.

Thanks,
Kriti

**Comment by albus522** [comment]
That usually means you have another worker process running that you forgot about. Look for other running ruby processes on the machine and make sure none of them are workers.

Also try quoting the queue name `QUEUE="queue_name" rake jobs:work`.
