### ISSUE TITLE
Possible to modify the handle_asynchronously method to only work in production?

### ISSUE THREAD

**Issue by usctrojan** [collectiveidea/delayed_job#844]
I want to use delayed_jobs only in production mode. I thought about doing something like this:

      def some_action_here
        puts "Some text here"
      end
      handle_production_asynchronously :some_action_here

Right now, I have something like this in an config/initializers file:

    module Patch
      def handle_production_asynchronously(method, opts = {})
        Rails.env == "production" ? delay.method : method # Probably incorrect. What should I put here? 
      end
    end
    Module.send(:include,Patch)

Do you know what I should place in the initializers in the line above to execute the methods correctly?

**Comment by albus522** [comment]
`Delayed::Worker.delay_jobs = Rails.env.production?` in an initializer.

**Comment by usctrojan** [comment]
Great! Thanks so very much :)
