### ISSUE TITLE
Worker trying to run jobs outside of the specified queue (conflict)

### ISSUE THREAD

**Issue by dthstr** [collectiveidea/delayed_job#847]
I have 3 seperates (and distinct!) rails 4.1.x apps sharing the same database (all 3 apps providing a different sets of features based off the same data).

* Each app use a different default queue name (app1, app2, app3) when creating/adding new jobs
* Each app has a 1 worker started on its named queue: bin/delayed_job --queue=app1 start, etc.

The issue is that all 3 seperate workers still try to execute jobs outside of their specified queue, resulting in errors/locks when trying to execute jobs for methods and code belonging to a different app (in a different queue ans assigned to a another worker)

I've been trying to solve this for the past month with no luck.

delayed_job (4.0.6)
delayed_job_active_record (4.0.3)

**Comment by albus522** [comment]
There are only 2 ways that happens. Something in your code calls `Delayed::Worker.reset` after the worker has been initialized. Or something in your code sets `Delayed::Worker.queues` after the worker has been initialized.

**Comment by dthstr** [comment]
Thanks for the quick response -- But the only configuration I have in each app is a delayed_job_config.rb initializer with the following:
```
Delayed::Worker.destroy_failed_jobs = false
Delayed::Worker.sleep_delay = 60
Delayed::Worker.max_attempts = 3
Delayed::Worker.max_run_time = 5.minutes
Delayed::Worker.read_ahead = 10
Delayed::Worker.default_queue_name = 'app1'
Delayed::Worker.delay_jobs = !Rails.env.test?
```
