### ISSUE TITLE
How run queue and add to it tasks with auto start in run_at time

### ISSUE THREAD

**Issue by stopanko** [collectiveidea/delayed_job#854]
I have some methods to post articles into FB Twitter Vkontakte. After user create post at site i must post it after 10 minutes. I have this code using DJ in my model.

    def post_to_facebook
    if self.publish_changed? && self.publish
      fb = Facebook.new
      fb.delay(:queue => 'facebook', run_at: DateTime.now + 10.minute).perform(self.id)
      # Facebook.perform_in(10.minutes, self.id)
    end
    end

    def post_to_twitter
    if self.publish_changed? && self.publish
      tw = TwitterW.new
      tw.delay(:queue => 'twitter', run_at: DateTime.now + 10.minute).perform(self.id)
      # TwitterW.perform_in(10.minutes, self.id)
    end
    end

     def post_to_vk
    if self.publish_changed? && self.publish
      vk = Vkontakte.new
      vk.delay(:queue => 'vkontakte', run_at: DateTime.now + 10.minute).perform(self.id)
      # Vkontakte.perform_in(10.minutes, self.id)
    end
    end

But i don`t understand how i can run this 3 queues in production. I need that all jobs in queue will run. And when i add new tasks i need run it automatically at run_at time

**Comment by albus522** [comment]
https://github.com/collectiveidea/delayed_job/tree/v4.1.1#running-jobs
