### ISSUE TITLE
Mail sent in job doesn't use asset pipeline correctly

### ISSUE THREAD

**Issue by patches11** [collectiveidea/delayed_job#857]
I've got a delayed job task which sends emails with images hosted on my rails site. When the mail is sent directly the image src is correct (example.com/assets/image-fingerprint123.png). When it is sent through delayed job the src is incorrect (no fingerprint: example.com/images/image.png).

**Comment by Jesus** [comment]
I don't think anyone will be able to help unless you provide some further information. For example, what method are you using to generate the URL ?

**Comment by patches11** [comment]
I'm using rails standard image_tag

**Comment by albus522** [comment]
Usual culprit is that you are starting DJ under the wrong environment. Meaning DJ is running under RAILS_ENV development while your app is running as production. Make sure your startup command includes RAILS_ENV=production

**Comment by patches11** [comment]
DJ connects to the correct database, and uses some production specific config variables correctly so I don't think that is the problem.

**Comment by patches11** [comment]
Never mind, I'm an idiot. If any one sees this make sure you are compiling your assets on your delayed job servers if you intend to use them there.
