### ISSUE TITLE
reschedule_at doesn't seem to work with ActiveJob

### ISSUE THREAD

**Issue by jtmarmon** [collectiveidea/delayed_job#862]
```rb
# app/jobs/test_job.rb
class TestJob < ActiveJob::Base
  queue_as :default

  def perform(*args)
    raise 'error'
  end

  def reschedule_at(foo, bar)
    p 'called reschedule_at'
    Time.now + 24.hours
  end
end
```

When I run `TestJob.perform_later` with `rake jobs:work` running, the job runs, and fails. Then after a small delay it's rerun. `'called reschedule_at'` is never printed

Am I missing something or is this just not working with ActiveJob?

rails version 4.2.3

**Comment by jtmarmon** [comment]
it's an ActiveJob adapter issue. see new thread here: https://github.com/rails/rails/issues/22359

**Comment by ajporterfield** [comment]
Take a look at https://github.com/ajporterfield/activejob_dj_overrides.  It's a gem that you can use to make the code you posted work (override reschedule_at using ActiveJob) as desired.
