### ISSUE TITLE
Delayed Job and Foreman

### ISSUE THREAD

**Issue by vladra** [collectiveidea/delayed_job#868]
I'm using foreman on production servers to start up everything.

Line for delayed job looks like this:
`bundle exec rake jobs:work`

The problem I have - when it's started like this, all jobs on fail are restarted, without keeping info about fail reason. `attempts` are always 0, and therefore job is running infinitely.

Any tips on how to use Delayed Job correctly with Foreman?

Thanks

--- UPDATE
I think it's doing so because when job is failed, whole process is crashed immediately, before it saves changes to DB. Then process restarted automatically and job started from the beginning. And this circle never ends

**Comment by JackDanger** [comment]
@vladra Does the process crash due to a bug in DelayedJob or is this because of code inside the job that crashes the process?

**Comment by vladra** [comment]
@JackDanger Unfortunately wasn't able to solve this, and switched to sidekiq afterwards. Will close this one
