### ISSUE TITLE
New gem release for queue priorities?

### ISSUE THREAD

**Issue by nruth** [collectiveidea/delayed_job#869]
Adding queue priorities seems like a nice thing for active-job users with one, or few background workers.

The readme says I can do this, 
```rb
Delayed::Worker.queue_attributes = [
  { name: :user_is_waiting, priority: 0 },
  {name: :default, priority: 100},
  { name: :low_priority, priority: 200 }
]
```

but the latest gem version blows up with `undefined method `queue_attributes=' for Delayed::Worker:Class (NoMethodError)`.

It looks like this came in after the latest gem version.

**Comment by albus522** [comment]
We will probably release a new gem after rails 5
