### ISSUE TITLE
SyntaxError while loading delayed_job.gemspec

### ISSUE THREAD

**Issue by obskein** [collectiveidea/delayed_job#870]
Using ruby 2.0.0 on the ubuntu docker image, I'm getting the following error when I bundle install:

```
Fetching git@github.com:DatabaseCleaner/database_cleaner.git
Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
Fetching https://github.com/collectiveidea/delayed_job
There was a SyntaxError while loading delayed_job.gemspec: 
/usr/local/lib/ruby/gems/2.0.0/bundler/gems/delayed_job-2014009496dd/delayed_job.gemspec:3: invalid multibyte
char (US-ASCII)
/usr/local/lib/ruby/gems/2.0.0/bundler/gems/delayed_job-2014009496dd/delayed_job.gemspec:3: invalid multibyte
char (US-ASCII)
/usr/local/lib/ruby/gems/2.0.0/bundler/gems/delayed_job-2014009496dd/delayed_job.gemspec:3: syntax error,
unexpected end-of-input, expecting ']'
...', 'Steve Richert', 'Tobias Lütke']
...                               ^

```

Suggest prepending the gemspec with a utf8 magic comment as per https://github.com/sinatra/sinatra-contrib/issues/109

Resolution appears to be adding ```# -*- encoding: utf-8 -*-``` to the first line of the file, as per https://github.com/plataformatec/simple_form/blob/master/simple_form.gemspec

**Comment by obskein** [comment]
Furthermore, I verified this works correctly with a fork - feel free to reference commit https://github.com/closeco/delayed_job/commit/3339f39c959914d6ebd2fba19d0a43adc208895d

**Comment by albus522** [comment]
@obskein You want to submit that as a PR to get credit?

**Comment by johnnyshields** [comment]
I've raised the PR giving @obskein credit in the comment, please merge.
