### ISSUE TITLE
Dont deamonize

### ISSUE THREAD

**Issue by emilebosch** [collectiveidea/delayed_job#875]
Hey in order to have our workers to run efficiently in docker we would love to have it not demonize when starting. So it can say pid one1. Is there an option to do this?

**Comment by betamatt** [comment]
If I'm understanding the question correctly then you're in a situation similar to people running DJ on Heroku. Use the `run` command instead of `start`, which will prevent the the parent process from daemonizing.

**Comment by albus522** [comment]
Or run via rake https://github.com/collectiveidea/delayed_job#running-jobs

**Comment by javanux** [comment]
But I don't know how to make `--pid-dir` work while starting `delayed_job` as run or the rake task with`jobs:work`. I needed the pid file because I want to fire certain signal to the `pid` while deploying my codebase. Do you guys know how can I specify the pid-dir in `delayed_job.rb`

**Comment by zx1986** [comment]
@javanux or try this base image? https://github.com/phusion/baseimage-docker

**Comment by albus522** [comment]
You can write a pid file manually by creating a simple plugin. Put something like this in the delayed job initializer or anywhere that is guaranteed to load.

```
class WritePidfile < Delayed::Plugin
  callbacks do |lifecycle|
    lifecycle.before(:execute) do |_worker|
      File.write("path/to/pidfile", "w") {|f| f.puts Process.pid }
    end
  end
end
```

**Comment by jdufresne** [comment]
> You can write a pid file manually by creating a simple plugin. Put something like this in the delayed job initializer or anywhere that is guaranteed to load.
> 
> ```
> class WritePidfile < Delayed::Plugin
>   callbacks do |lifecycle|
>     lifecycle.before(:execute) do |_worker|
>       File.write("path/to/pidfile", "w") {|f| f.puts Process.pid }
>     end
>   end
> end
> ```

Thanks for this suggestion. I needed something like this and thought this might be useful to other people. So I put it into PR #1202.
