### ISSUE TITLE
How to change database lookup interval?

### ISSUE THREAD

**Issue by madshargreave** [collectiveidea/delayed_job#879]
Hi

I want to run jobs right after they're enqueued, but right now, DelayedJob only scans for jobs every 5 seconds.

This means that on average, each job spends 2.5 seconds being idle

How can this be changed?

**Comment by Jesus** [comment]
You can change the `sleep_delay` with the command line option `--sleep-delay N`. You can also configure it at boot.

    # config/initializers/delayed_job_config.rb
    Delayed::Worker.sleep_delay = 60

I found that on the README.md.

However, this won't make a difference in most cases. Note that if one job finishes in 0.5s the next one will be performed straight away if it's available, it won't wait 4.5s. Another example: if 10 jobs are pending they're all performed in one shot (sequentially though) once they're found by a worker.

**Comment by madshargreave** [comment]
Imagine this scenario

(hh:mm:ss)

08:00:00 My job queue is empty
08:00:00 A database job scan is ran
08:00:01 A job is inserted
...
08:00:05 The job is scheduled

In this case, I have to wait 4 seconds because the job was inserted right after the previous scan

**Comment by maxjacobson** [comment]
I think you do this:

echo "Delayed::Worker.sleep_delay = 1" >> config/initializers/delayed_job.rb

**Comment by Jesus** [comment]
That's right.
