### ISSUE TITLE
Missing bin/delayed_job in Rails 5

### ISSUE THREAD

**Issue by micred** [collectiveidea/delayed_job#881]
I'm starting a new Rails 5 project and i add to the Gemfile:
    gem 'delayed_job_active_record'
    gem 'delayed_job', github: 'collectiveidea/delayed_job' 
    gem 'daemons'

I got no errors during bundle install but the delayed_job binary is missing.

**Comment by maxjacobson** [comment]
I think you need to run `bundle binstubs delayed_job` to generate the binary (or `bundle install --binstubs` to generate a whole mess of binstubs)

**Comment by micred** [comment]
I got:

    $ bundle binstubs delayed_job
    There are no executables for the gem delayed_job.

`bundle install --binstubs` generates a bunch of bins, but no delayed_job.

**Comment by albus522** [comment]
https://github.com/collectiveidea/delayed_job#installation

**Comment by wadtech** [comment]
If anyone else is blind like me, the docs link is: https://github.com/collectiveidea/delayed_job#running-jobs to explain how to get the `bin/delayed_job` file installed.
