### ISSUE TITLE
How to run delayed job in production?

### ISSUE THREAD

**Issue by jpbullalayao** [collectiveidea/delayed_job#885]
Hi everybody,

I'm trying to run delayed job in production (Elastic Beanstalk, AWS) using `RAILS_ENV=production bin/delayed_job start`, however I get the following permission error:

```
/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/command.rb:85:in `mkdir': Permission denied @ dir_s_mkdir - /var/app/current/tmp/pids (Errno::EACCES)
        from /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/command.rb:85:in `daemonize'
        from bin/delayed_job:5:in `<main>'
```

This probably isn't an issue with Delayed Job, but I couldn't really find an answer anywhere online to this permission issue and I figured someone here might have a clue on what I can do to make it work in production. 

Any help is greatly appreciated! Thanks!

**Comment by albus522** [comment]
DJ needs to be able to write a pid file in `/var/app/current/tmp/pids`. If that directory doesn't exist, or the user you are trying to run DJ as doesn't have permission to write there, DJ will fail. See capistrano's documentation on sharing and linking that directory.

**Comment by erikhSSI** [comment]
https://github.com/SilentSpringInstitute/DERBI_Deploy/commit/0d5dfc7
