### ISSUE TITLE
How to remove delayed_job activerecord logs in production.log?

### ISSUE THREAD

**Issue by rusikf** [collectiveidea/delayed_job#886]
Hello, in production.log I have a lot of records like this:
```
Delayed::Backend::ActiveRecord::Job Load (0.6ms)  UPDATE "delayed_jobs" SET locked_at = '2016-03-01 10:19:58.969011', locked_by 
```
How to disable it?
I have``` Delayed::Worker.logger = Logger.new(File.join(Rails.root, 'log', 'delayed_job.log'))```
in my initializer, but it looks, that it logs only delayed_job to this file, delayed_job tables logs to production.log.

**Comment by hoserdude** [comment]
Setting the `ActiveRecord::Base.logger.level = 1` in an initializer should handle that.  Note that the `Worker` will do `put` calls for it's own logging on top of the calling the currently configured logger, which is less than ideal.  The flag (`quiet`) to disable that is unfortunately in the initialize method and the default is false, and the provided rake task to start the worker has that hardcoded to false as well.

**Comment by albus522** [comment]
@hoserdude quiet is not hardcoded in the rake task https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/tasks.rb#L22

Logging is determined by how you start the worker. Daemonize has different requirements and therefore reopens all logging file descriptors to point to an independent delayed_job.log but does NOT change the system log level except it does define a new logger for DJ specific messages. The rake task simply uses the rails logging settings, as we don't touch the rails logger. Be aware rails recently changed the default production log level to debug, which means you get a ton of noise in your production logs.

**Comment by saifuddin** [comment]
Hi,

So I'm having this exact same problem. I tried adding these:

`
Delayed::Worker.destroy_failed_jobs = false
Delayed::Worker.sleep_delay = 60
Delayed::Worker.max_attempts = 3
Delayed::Worker.max_run_time = 5.minutes
Delayed::Worker.read_ahead = 10
Delayed::Worker.default_queue_name = 'default'
Delayed::Worker.delay_jobs = !Rails.env.test?
Delayed::Worker.raise_signal_exceptions = :term
Delayed::Worker.logger = Logger.new(File.join(Rails.root, 'log', 'delayed_job.log'))
ActiveRecord::Base.logger.level = 1
`

in `config/initializers/delayed_job_config.rb`.

But, in my `production.rb`, it's full of `UPDATE "delayed_jobs" SET locked_at...` and my delayed_job log is only:

```
Logfile created on 2018-06-16 22:47:13 +0000 by logger.rb/56438
I, [2018-06-16T23:08:19.877957 #2355]  INFO -- : 2018-06-16T23:08:19+0000: [Worker(delayed_job host:ubuntu pid:2355)] Starting job worker
I, [2018-06-24T18:45:49.925238 #2355]  INFO -- : 2018-06-24T18:45:49+0000: [Worker(delayed_job host:ubuntu pid:2355)] Exiting...
I, [2018-06-24T18:47:00.827360 #2366]  INFO -- : 2018-06-24T18:47:00+0000: [Worker(delayed_job host:ubuntu pid:2366)] Starting job worker
```

I'm going bonkers. Lol. Appreciate any help given.

**Comment by albus522** [comment]
Log level 1 is Logger::INFO. You are actually specifically telling ActiveRecord to give you that noise and likely the rest of the app as by default the AR logger and rails app logger are the same. The Delayed::Worker logger is specifically for DJ messages from the worker and does not replace the app wide or AR logger. Also be aware your delayed job initializer is not specific to the worker process.

You could setup a plugin for worker specific setup similar to https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/plugins/clear_locks.rb

Instead of `around(:execute)` use `before(:execute)` and that will be called just before the worker starts processing the job loop.

**Comment by saifuddin** [comment]
Hey thanks for the reply @albus522. My bad then, I think I need to understand what I put on the config a bit more better. I'll try it out. Appreciate the response!

**Comment by Meekohi** [comment]
Hey sorry to revisit, but what is the solution here exactly? Tried running
`QUIET=1 bin/delayed_job restart`
but no luck...

**Comment by Meekohi** [comment]
Adding this nightmare worked for me:
```
# initializers/delayed_job.rb
unless Rails.env.development?
  module Delayed
    module Backend
      module ActiveRecord
        class Job
          class << self
            alias_method :reserve_original, :reserve
            def reserve(worker, max_run_time = Worker.max_run_time)
              previous_level = ::ActiveRecord::Base.logger.level
              ::ActiveRecord::Base.logger.level = Logger::WARN if previous_level < Logger::WARN
              value = reserve_original(worker, max_run_time)
              ::ActiveRecord::Base.logger.level = previous_level
              value
            end
          end
        end
      end
    end
  end
end
```

**Comment by dignoe** [comment]
I added this to `config/development.rb` to ignore the sql query logs in development:

    if caller_locations.map(&:path).any? { |c| c =~ %r{bin\/delayed_job} }
      ActiveRecord::Base.logger =
        Logger.new(Rails.root.join('log', 'delayed_job.runtime.log'))
    end

**Comment by localhostdotdev** [comment]
you can also do it with:

```ruby
if $ARGV.include?("jobs:work")
  ActiveRecord::Base.logger = nil
end
```

works with `bundle exec rake jobs:work` and `rake jobs:work`. you could of course customize it by putting it in the appropriate environment initializer or having checks like `Rails.env.production?` or `ENV["DISABLE_SQL_LOGGING_FOR_JOBS"]` (or have the logger log somewhere else, etc.)

**Comment by jcamejo** [comment]
Some time ago I've found an equivalent solution, similar to the one @Meekohi proposed but i can't find the original author and reference. I will post it to not forget

> 
> unless Rails.env.development?
>   Delayed::Backend::ActiveRecord::Job.singleton_class.prepend(
>     Module.new do
>       def reserve(*)
>         previous_level = ::ActiveRecord::Base.logger.level
>         ::ActiveRecord::Base.logger.level = Logger::WARN if previous_level < Logger::WARN
>         value = super
>         ::ActiveRecord::Base.logger.level = previous_level
>         value
>       end
>     end
>   )
> end

**Comment by pebneter** [comment]
Since my upgrade to Rails 6, this does not work anymore because of ```Unable to load application: NameError: uninitialized constant Delayed::Backend::ActiveRecord::Job```.
I tried many ways to load this in other places, but no luck. Any ideas?

**Comment by pebneter** [comment]
I posted my own answer to the question in a related thread: https://github.com/collectiveidea/delayed_job/issues/477#issuecomment-800341818

**Comment by akaspick** [comment]
Change your `bin/delayed_job` script to...
```ruby
#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'
Delayed::Backend::ActiveRecord::Job.logger.level = Logger::INFO # <---- Add this line
Delayed::Command.new(ARGV).daemonize
```

**Comment by carter-thaxton** [comment]
Here's a somewhat cleaner approach, which should work in any version of Rails or DelayedJob backend.
Drop this into:  `config/initializers/silence_delayed_worker_reserve_job.rb`

```
#
# Silence debug log output from Delayed::Worker::reserve_job
#
# When log_level is set to :debug, this prevents logs from filling up with lines such as:
#   Delayed::Backend::ActiveRecord::Job Load (0.6ms)  UPDATE "delayed_jobs" SET locked_at = ...
#
# Still logs from the jobs themselves, or any non-debug output from reserve_job.
#
module SilenceDelayedWorkerReserveJob
  def reserve_job
    Rails.logger.silence(:info) do # only log at :info or higher
      super
    end
  end
end

module Delayed
  class Worker
    prepend SilenceDelayedWorkerReserveJob
  end
end
```

**Comment by akaspick** [comment]
@carter-thaxton Did my method not work?  Seems like a 1 line change in the binstub can't go wrong.

**Comment by carter-thaxton** [comment]
@akaspick Your approach silences all SQL output logging from the jobs themselves, too.  I believe @pebneter also reported that it doesn't work in Rails 6+, but I haven't tried it personally.  I don't use it myself, but my approach also works for all backends, not just ActiveRecord, and more shallowly only depends on the `delayed_job` gem, and not `delayed_job_active_record`.

Anyway, just sharing an approach that I think matches what many readers may actually want:
Prevent just the periodic debug SQL logging that DelayedJob performs every 5 seconds, but still log everything else at the selected log level.
