### ISSUE TITLE
Certain jobs don't run

### ISSUE THREAD

**Issue by holgersindbaek** [collectiveidea/delayed_job#887]
I'm not sure what I did, but the last 24 hours, certain jobs simply don't run. I'm mostly using delayed job to send emails in the background and 1 email is consistently never executed. I can't find it in the job queue either, which is very worrying. It is, as if it gets created and deleted straight away.

Any idea of what could be causing this?

**Comment by albus522** [comment]
Check the logs

**Comment by holgersindbaek** [comment]
@albus522 If I look in the logs, I can't see the job being run anywhere... that's what confuses me. So it's not like the job is made, runs, fails and then gets deleted. It gets made and then gets deleted.

**Comment by holgersindbaek** [comment]
@albus522  It might have been a bug on my worker on Heroku that was running out of memory. It still confuses me that the job simply disappeared instead of failing or succeeding though. I'll keep an eye on it throughout the day.

**Comment by holgersindbaek** [comment]
Jobs are most definitely failing randomly and silently! What in the world is going on here?

If I run the following 3 jobs in the Heroku console, then only 1 or 2 will be executed and the rest will fail silently:

    Pushover.delay(run_at: 20.seconds.from_now).notification(title: 'TEST', message: "Test 1")
    Pushover.delay(run_at: 20.seconds.from_now).notification(title: 'TEST', message: "Test 2")
    Pushover.delay(run_at: 20.seconds.from_now).notification(title: 'TEST', message: "Test 3")

I hope someone can help debug this situation. My application is very dependent on jobs being run properly.

I'm using delayed_job_mongoid '2.1.0', Rails '4.1.6' and Ruby '2.2.1'.

**Comment by holgersindbaek** [comment]
@albus522 If I follow the logs, I can see that 1 or 2 jobs are getting run successfully, but I see NO logs for the 3 one. No failed logs, no successful logs. The jobs simply disappear into thin air, which is disastrous. What could be that cause of this?

I've tried to upgrade to the newest version of mongoid_delayed_job, but with no luck. I'm not sure what I did since this only started happening 2 days ago. Any guesses?

**Comment by holgersindbaek** [comment]
@albus522  I figured it out. I have another rails application (where I run delayed_job_web) which has delayed_job installed, shares the same database and has a worker running. So the jobs would simply run and apparently not fail. 

Is there any way to set which jobs should run on which worker?

**Comment by albus522** [comment]
https://github.com/collectiveidea/delayed_job#named-queues

**Comment by holgersindbaek** [comment]
Thanks. I don't understand how naming a task would make it run a specific worker?!

**Comment by albus522** [comment]
https://github.com/collectiveidea/delayed_job#running-jobs specifically limiting a worker to run jobs from specific queues

**Comment by holgersindbaek** [comment]
Oh, cool. Where do I set that? In my Procfile?

    worker: rake jobs:work --queues=mailers,tasks

**Comment by holgersindbaek** [comment]
Seems like this is the right way to do it:

    worker: QUEUE=api rake jobs:work

Thanks for the help.
