### ISSUE TITLE
multiworker efficacy

### ISSUE THREAD

**Issue by kaogaau** [collectiveidea/delayed_job#889]
Hi~,I use the delayed job gem under rails to do something.
I use the 4 workers ,10 workers,50 workers,70 workers,100 workers to do the same test process.
When number of workers from 4 to 10,the time for complicate the process decreasing,but when number of workers  from 10 to 50&70&100,I get the same time for complicate the process.
For the situation,it means the worker's  efficacy has "Marginal effect".
Can I ask the situation is normal or maybe has some issue someone has happened?

**Comment by albus522** [comment]
Having more workers does not mean a job runs faster. It means more jobs run at the same time. If you have a job that takes 10 minutes, it will take 10 minutes if you have 1 or 1000 workers.

**Comment by A20229** [comment]
sorry,I have wrong.I use the 4 workers ,10 workers,50 workers,70 workers,100 workers to do the 5000 jobs(same numbers of jobs).But get the same complicate time

**Comment by albus522** [comment]
I am sorry, but I guess I don't understand what you are saying. Maybe try detailing what each experiment you run is doing and what the outcome is for each. What jobs you are creating. What commands you are using. What the log file says is happening each time. Etc.

**Comment by betamatt** [comment]
If all you're doing is running empty jobs then what you're really testing is the concurrency limits of the reservation algorithm for that particular database.

**Comment by A20229** [comment]
Just give a example but real test :

TEST1 : I insert 5000 jobs in my delayed_job table ,all associate just one agent(output a event) , and use 10 workers to run, my Delayed::Worker.read_ahead = 5 ,then I get the complete time == 33 seconds(the time get by last event's created time - first event's created time)

TEST2 : I insert 5000 jobs in my delayed_job table ,all associate just one agent(output a event) , and use 20 workers to run, my Delayed::Worker.read_ahead = 5 ,then I get the complete time == 34 seconds(the time get by last event's created time - first event's created time)

The result looks not linear but has "Marginal effect" at 10 workers nearly.

My computer has 8 core CPU , I use the command "top" monitor the system's load ,the CPU loading in the 60% nearly

**Comment by kaogaau** [comment]
Sorry , I change the account...accidentally

Just give a example but real test :

TEST1 : I insert 5000 jobs in my delayed_job table ,all associate just one agent(output a event) , and use 10 workers to run, my Delayed::Worker.read_ahead = 5 ,then I get the complete time == 33 seconds(the time get by last event's created time - first event's created time)

TEST2 : I insert 5000 jobs in my delayed_job table ,all associate just one agent(output a event) , and use 20 workers to run, my Delayed::Worker.read_ahead = 5 ,then I get the complete time == 34 seconds(the time get by last event's created time - first event's created time)

The result looks not linear but has "Marginal effect" at 10 workers nearly.

My computer has 8 core CPU , I use the command "top" monitor the system's load ,the CPU loading in the 60% nearly

**Comment by albus522** [comment]
Ok. I am not sure if you are evaluating the created time on the jobs or some new db record being generated by the jobs you have queued up.

If the first, the speed of queuing jobs will never change no matter how many workers you are running.

If the second, you are testing extremely small fast jobs. DJ is not designed for that. DJ is for things that are too slow to run inline. In this case you are effectively doing what Matt says and simply testing the concurrency of the locking mechanism in your particular database (yes different db's would have different results).

If your use case is tons of super fast jobs, you will need to either use a different tool or just run them inline.

**Comment by kaogaau** [comment]
Thank you for your response. I think we have a test conclusion that similar your answer, we test used super fast jobs ,when we used many workers for super fast jobs ,it seems just some workers are doing jobs , but a lot of workers aren't doing jobs .

We still testing continuously..

Thank you for your response.
