### ISSUE TITLE
when no tmp directory, causes error

### ISSUE THREAD

**Issue by JeffKatzy** [collectiveidea/delayed_job#891]
I am trying to get started on a project that doesn't have a tmp directory.  We consistently then run into an issue.

[32766] * Preloading application
12:25:18 worker.1 | /Users/robjewell/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:78:in `mkdir': No such file or directory @ dir_s_mkdir - /Users/robjewell/code/dolores-landingham-bot/tmp/pids (Errno::ENOENT)
12:25:18 worker.1 |     from /Users/robjewell/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:78:in `daemonize'
12:25:18 worker.1 |     from bin/delayed_job:5:in `<main>'
12:25:18 worker.1 | exited with code 1

Delayed job could either not require the tmp directory, raise a better error message, or make the tmp directory.

**Comment by albus522** [comment]
DJ doesn't require the tmp/pids directory. The daemons gem does, which is not required by DJ. Running via `rake` will avoid this.
The error being raised by the daemons gem as you posted it `No such file or directory @ dir_s_mkdir - /Users/robjewell/code/dolores-landingham-bot/tmp/pids` seems about as clear as you can get.
Auto creating the tmp directory has deployment implications for which there are arguments both ways. We have chosen the route which requires user intervention.
