### ISSUE TITLE
Struct handler that cannot be resolved does not retry

### ISSUE THREAD

**Issue by johnnaegle** [collectiveidea/delayed_job#893]
I've struggled with the title for this issue, but here is what happened:

A job was queued up in a distributed system where the code had not yet been deployed to the delayed job servers; we assumed the job would fail retry.  However, it failed, did not report an error and did not retry.

Server A queued this job:

```
Delayed::Job.enqueue(User::Xyzzy.new(5))

class User < ActiveRecord::Base
  class Xyxxy < Struct.new(:id)
    def perform
    end

    def display_name
       "Xyzzy #{id}"
    end
  end
end
```

That code was not yet deployed to Server B.  The job was dequeued, failed, but did not retry or report errors:

rake jobs:work
```
[Worker(host:laptop.local pid:34356)] Job User::Xyzzy (id=104579022) RUNNING
```

then from the console:
```
[1] pry(main)> Delayed::Job.count
   (0.5ms)  SELECT COUNT(*) FROM "delayed_jobs"
=> 0
```

I've written a test case for this:

```
it "retries for a struct that does not exist" do
  job = Delayed::Job.create(:handler => "--- !ruby/struct:User::Xyzzy\nid: 5\n"
  worker.run(job)
  job.reload
  expect(job.last_error).to_not be_nil
  expect(job.attempts).to eq(1)
end
```
https://github.com/johnnaegle/delayed_job/commit/7aef58117a8fc8a8ab6e1af7605afb360572bdb5

This behaves very differently, and surprisingly from using performable method.    I'd be happy to look into the issue and fix if anybody has suggestions on where to start looking.

**Comment by betamatt** [comment]
I assume it's because the error is happening on deserialization, which is outside the job lifecycle. A performable method is going to deserialize, then fail to execute.

**Comment by johnnaegle** [comment]
When I step through in the debugger, I end up here:

```
[227, 236] in /Users/johnnaegle/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb
   227:       end
   228:       job_say job, format('COMPLETED after %.4f', runtime)
   229:       return true # did work
   230:     rescue DeserializationError => error
   231:       debugger
=> 232:       job.error = error
   233:       failed(job)
   234:     rescue Exception => error # rubocop:disable RescueException
   235:       debugger
   236:       self.class.lifecycle.run_callbacks(:error, self, job) { handle_failed_job(job, error) }
```

I expected to see: the job retried and at a minimum, some logging that the job failed.

Why is DeserializationError treated differently (`failed(job)`) than all other exceptions (`handle_failed_job(job, error)`)?

**Comment by albus522** [comment]
DeserializationErrors are almost never recoverable which is why we don't retry them. You could enable saving failed jobs, that way if you determine they are recoverable you could clear the failed time.

**Comment by robmathews** [comment]
Yes, I can understand not retrying them - but why doesn't the code write a message saying the job has failed permanently, like it does for other kinds of errors.

**Comment by johnnaegle** [comment]
I'll close this.  I accept that most deserialization cannot be recovered.  I opened a pull to log the fact that they failed (#894).
