### ISSUE TITLE
Timeline for Rails 5 Compatibility?

### ISSUE THREAD

**Issue by jakesorce** [collectiveidea/delayed_job#896]

**Comment by albus522** [comment]
Not until an RC is out, which should be soon

**Comment by rahuljaswa** [comment]
Any update on this?

**Comment by activestylus** [comment]
Full release is out - any progress?

**Comment by chrishough** [comment]
Any updates on this?

**Comment by llenodo** [comment]
No plans for rails 5 support?

**Comment by jakesorce** [comment]
this already works in rails 5 close this issue
