### ISSUE TITLE
Delayed_job firing Mailer twice with .deliver

### ISSUE THREAD

**Issue by scottrCT** [collectiveidea/delayed_job#899]
Running Rails 4.1.15 with delayed_job 4.0.1. When using a mailer, .deliver is no longer needed at the end of the call for the mailer to send the email. When running the mailer call without delay, only one email is sent even with .deliver in the method call (i.e. `TestMailer.send_test_email.deliver` sends one email). When the delay call is added (i.e. `TestMailer.delay.send_test_email.deliver`), the delayed_job worker sends the email twice.

Should the delayed_job worker work the same way as when the delay is not called?

**Comment by albus522** [comment]
https://github.com/collectiveidea/delayed_job#rails-3-mailers
