### ISSUE TITLE
3.x -> latest master: max_attempts may not be honored

### ISSUE THREAD

**Issue by johnnyshields** [collectiveidea/delayed_job#903]
I'm seeing on latest master that max_attempts is not being honored, and instead, failed jobs are flushed out of the queue after one attempt. Please investigate.

**Comment by albus522** [comment]
You upgraded something else and now the jobs don't deserialize leaving DJ with nothing to do but delete the jobs

**Comment by johnnyshields** [comment]
Guess it may be linked to this monkey patch:

```
# Report all Delayed Job errors to Bugsnag
# See: http://www.salsify.com/blog/delayed-jobs-callbacks-and-hooks-in-rails
class BugsnagDelayedPlugin < Delayed::Plugin

  callbacks do |lifecycle|
    lifecycle.around(:invoke_job) do |job, *args, &block|
      begin
        block.call(job, *args) # forward call to next callback in the chain
      rescue Exception => error
        ::Bugsnag.notify(error)
        raise error # propagate the error
      end
    end
  end
end
Delayed::Worker.plugins << BugsnagDelayedPlugin
```

Does that sound plausible to you?

**Comment by albus522** [comment]
I don't think anything changed in the callback structure. I mean DJ tries to deserialize the payload object and that fails leaving DJ with no way to recover that job. This can happen due to a change in the YAML structure or objects

**Comment by johnnyshields** [comment]
That doesn't sound like what happened in my case.

I'm 100% confident that the jobs deserialized correctly, and that the error occured while the body of the job was executing (after serialization). I know this because I can see objects in my database are partially processed, and they get set with an error status if and only if job fails. My expectation is that the DJ should keep the jobs in the database table and mark it as an error, then retry X times, but instead the jobs are immediately deleted.

Side note: although I'm almost positive my issue was NOT serialization related, I do think that DJ should not immediately flush jobs which can't be deserialized; IMHO DJ should err on the side caution and mark them as errored.

**Comment by johnnyshields** [comment]
By the way, downgrading DJ with no other changes fixes the issue.

**Comment by johnnyshields** [comment]
I found the root cause and it was in my own code. d'oh. sorry for sounding the alarm, the last time I upgraded delayed job I had several issues which did turn out to be inside DJ itself, so I guess I was overly cautious--once bitten twice shy.
