### ISSUE TITLE
3.x -> latest master: possible deadlock

### ISSUE THREAD

**Issue by johnnyshields** [collectiveidea/delayed_job#904]
After upgrading from 3.x to latest master, within 2 days of running in production I saw some DJ instances appear to be in a frozen/deadlocked state. This does not happen ever on 3.x after running for 1+ years. Please investigate.

**Comment by albus522** [comment]
That provides nothing to investigate. What else did you upgrade? What version of rails? What database? How many workers do you run? What do the logs tell you? Do you have a long running job that is managing to bypass the timeout (yes ruby timeout is not perfect)?

**Comment by johnnyshields** [comment]
Sorry, I'll close this for now. My queue got backed up in a way that feels very suspiciously linked to the version upgrade, however, on further investigation it doesn't seem to be a deadlock--logs were printing continuously. I'll investigate further and re-raise when I have a better picture of the issue.
