### ISSUE TITLE
Failure hook not running on custom job - how to test? 

### ISSUE THREAD

**Issue by brunzino** [collectiveidea/delayed_job#910]
I am building a custom job with hooks for failure and success. To test failure hook, I raise an exception using `raise "My test exception"`. The `error` hook executes, but I can't get the `failure` hook to run. 

1) Is it correct to assume the `failure` hook executes when exceptions happen? 
2) Is there a better way to test the `failure` hook?

```
class MyJob < Struct.new(:arg1)

  def perform()
    raise "My test exception"
  end

  def error(job, exception)
    Delayed::Worker.logger.error("FAILURE REPORTED FROM 'error'") # successfully logs
  end

  def failure(job)
    Delayed::Worker.logger.error("FAILURE REPORTED FROM 'failure'") # does not get called
  end

end
```

Thanks!

**Comment by albus522** [comment]
Failure runs when the job fails, meaning the job has reached its retry limit and will not be retried again.
