### ISSUE TITLE
Action_Mailer is not working with "delay" method and an Object as an argument (working with the email passed as arg)

### ISSUE THREAD

**Issue by davidchriqui** [collectiveidea/delayed_job#912]
Hi,

`UserMail.delay.send_mail_to("user@example.com")` does nothing 

while 

`UserMail.any_mailer_method(Object).deliver_now`

works perfectly.

I tried to call the deliver_now method through a "proxy" method like this, but it is not working neither:

```
class MailerCustomClass
  def self.send_mail_to(email)
   UserMail.send_mail_to(Object).deliver_now
  end
end
```

(Object has an email attribute that is passed to the "mail" method inside UserMailer class)

`MailerCustomClass.delay.send_mail_to(Object)`

Anyone get ActionMailer to work with DJ ?

**Comment by albus522** [comment]
I suspect you aren't running the worker process. DJ requires a separate process to run https://github.com/collectiveidea/delayed_job#running-jobs

**Comment by davidchriqui** [comment]
Yes, I do run the worker process. I monitor the delayed_job table and it's seems normal (new record appears and is then removed when the job is processed).

I edited the code in my first post to reflect the case where delayed_job prevent Action_mailer from actually sending email.

The delay method works properly with Action_Mailer when I put the email directly as an argument :

`UserMail.delay.send_mail_to("user@example.com")`

**Comment by albus522** [comment]
Both work just fine. Check the delay job and app log. I would wager you have an error. Likely culprit is a deserialization issue
