### ISSUE TITLE
Capistrano recipes error with Capistrano v3+

### ISSUE THREAD

**Issue by hugoarpin** [collectiveidea/delayed_job#913]
When adding 

``` ruby
require 'delayed/recipes'
```

in Capfile I get the following error

```
cap aborted!
NoMethodError: undefined method `instance' for Capistrano::Configuration:Class
Did you mean?  instance_of?
```

I'm using Capistrano 3.5.0. Any chance to get cap3 support?
Please correct me if there is something that I'm doing wrong that would cause this error!

Note: writing a custom cap task is an easy fix right now, but having cap support out of the box would be very nice.

Thanks!

**Comment by realhugh08** [comment]
Also please correct me if there is something that I'm doing wrong that would cause this error!

**Comment by sidwatal** [comment]
@hugoarpin https://github.com/collectiveidea/delayed_job/wiki/Delayed-Job-tasks-for-Capistrano-3

**Comment by hugoarpin** [comment]
https://github.com/collectiveidea/delayed_job/wiki/Delayed-Job-tasks-for-Capistrano-3
