### ISSUE TITLE
Delayed job makes NilClass respond_to human_attribute_name

### ISSUE THREAD

**Issue by Kounts** [collectiveidea/delayed_job#914]
I have a simple form in one of my pages that calls SimpleForm::Components::Labels.label_translation on a nil Object.
Since I installed delayed_job gem, the test  `elsif object.class.respond_to?(:human_attribute_name)` is true (causing my page to bug) and Delayed:MessageSending appears in the ancestors of my object.
Why is my nil object heriting from this class ?

**Comment by albus522** [comment]
It isn't inherited, it is included. Also this is all that is added https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/message_sending.rb
We do not define `human_attribute_name`. A quick search shows that is `ActiveModel::Translation`
