### ISSUE TITLE
Single worker picks up all jobs

### ISSUE THREAD

**Issue by gregops** [collectiveidea/delayed_job#915]
I tried with both named queues and no queues specified (everything in default queue), and I enqueue multiple jobs at the same time (low number of long running ones), but often all those queued jobs end up being locked by a single worker and everything's processed serially instead of in parallel.

I start DJ daemons in the following way:

`bin/delayed_job -n 20 start`

(also tried `bin/delayed_job --pool='*:20'` - single quotes required by ZSH apparently - but same effect).

Then I `Delayed::Job.enqueue()` a number of jobs, but all end up locked by 1 worker out of the 20 and run serially.

Any ideas why this could be happening and how to debug it? Sometimes when I restart `delayed_job` workers they behave as I expect and jobs are executed in parallel, but 4 out of 5 times it'll default to single-worker operation.

```
$ bundle list | grep delayed
  * delayed_job (4.1.1)
  * delayed_job_active_record (4.1.0)
  * delayed_job_web (1.2.10)
$ rails --version
Rails 4.2.5
$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
```

OS is Yosemite 10.10.5.

**Comment by jamesvanklink** [comment]
I am experiencing the same issue, did you ever make any progress on it?

**Comment by ogodei** [comment]
Hey James,

I'm running with `sleep rand(2..4)` between jobs and as the jobs come in at a slower pace, it seems to handle allocation to workers much better.

My scenario in fact is I schedule DJ jobs, which in turn schedule other DJ jobs, and my sleeps are actually in the `perform` and `enqueue` methods of my custom DJ object (the first thing each method does is sleep), to slow down the scheduling pace.

**Comment by jberry** [comment]
Anyone ever find a real fix for this? I've been seeing this behavior in one of my apps, and even a rand(2..4) sleep isn't enough to prevent it.  

Even if the rand prevents the lock for all of their first queued jobs, once all the workers are busy and the queue backs up, the next free worker locks multiple again.

**Comment by albus522** [comment]
Closing stale
