### ISSUE TITLE
Job is serialized successfully even if parameters fail serialization 

### ISSUE THREAD

**Issue by ntnmrndn** [collectiveidea/delayed_job#918]
Hi,

I tried recently to create a job using a Delayed::Job.enqueue and a Struct with some parameters including raw binary data.

The object with raw data fails serialization, but absolutely no error is emitted until the job is actually executed and I try to access the data.

I understand that binary data might not be supported, but shouldn't the job fail to be en inserted if the parameters fail serialization ?

**Comment by albus522** [comment]
It is also possible that the data serialized just fine, but the database silently inserted an incomplete row, mysql is well known to do this. When none of the standard libraries we use to store the information indicate anything is wrong, there isn't much we can do.
