### ISSUE TITLE
Can't access stderr piping of delayed_job worker

### ISSUE THREAD

**Issue by seanmakesgames** [collectiveidea/delayed_job#927]
```
ruby 2.2.4
rails 4.2.6
mongoid 5.1.3
delayed_job_mongoid 2.2.0
mini_racer 0.1.3 (head; custom)
```

I'm using delayed_job to run javascript code in background workers and the mini_racer c extension is crashing on production.
I'm trying to get at the production crash information (which is in stderr) so that we can fix the crashes. I might be barking up the wrong tree, but daemons has a log_output option that works for this purpose, but I can't access that flag from the startup script or command line flags. (I've hacked Command#run_process to include it temporarily)

Ideally, stderr output would show up in delayed_job.log (maybe a flag to turn that on) or stderr.log files for each worker

**Comment by albus522** [comment]
Closing stale
