### ISSUE TITLE
Rails 5 ActiveJob with Delayed::Job fails in production

### ISSUE THREAD

**Issue by cdekker** [collectiveidea/delayed_job#934]
Working on upgrading an app from Rails 3.2 to Rails 5 and ran into some problems with DJ in Production environment.

Updated all jobs correctly to inherit from ApplicationJob and added the new (empty) ApplicationJob superclass which all works fine in Development environment while running with rails jobs:workoff

However, in Production all jobs seem to lock up as soon as they are picked up by the 2 running workers. This is wat the jobs look like:

```
 => #<Delayed::Backend::ActiveRecord::Job id: 807, priority: 0, attempts: 0, handler: "--- !ruby/object:ActiveJob::QueueAdapters::Delayed...", last_error: "Job failed to load: undefined class/module ActiveJ...", run_at: "2016-08-18 19:26:13", locked_at: "2016-08-18 19:26:14", failed_at: "2016-08-18 19:26:14", locked_by: "delayed_job.0 host:**** pid:26289", queue: "builder", created_at: "2016-08-18 19:26:13", updated_at: "2016-08-18 19:26:14">
 => #<Delayed::Backend::ActiveRecord::Job id: 808, priority: 0, attempts: 0, handler: "--- !ruby/object:ActiveJob::QueueAdapters::Delayed...", last_error: "Job failed to load: undefined class/module ActiveJ...", run_at: "2016-08-18 19:30:02", locked_at: "2016-08-18 19:30:04", failed_at: "2016-08-18 19:30:04", locked_by: "delayed_job.0 host:**** pid:26289", queue: "generator", created_at: "2016-08-18 19:30:02", updated_at: "2016-08-18 19:30:04">
```

As you can see, attempts is still at 0, and the process remains locked_by one of the workers. The last_error expanded looks like this:

`Job failed to load: undefined class/module ActiveJob::`

Seems quite weird for such a base class that is defined in the app/jobs/application_job.rb as part of the new Rails 5 standard. It should be loaded and required as it sits in the app folder.

**Comment by albus522** [comment]
You likely still either have jobs from the previous code base that the new workers can't run or old workers still running that can't load the new jobs. You can see the worker pid for the failing worker process in `locked_by`, so 26289 in the above case.

**Comment by cdekker** [comment]
That is not the case. I always restart all workers when I deploy new code.

**Comment by albus522** [comment]
`undefined class/module ActiveJob::` means the worker did not startup against the right gemfile/working directory or an old worker is lingering.
There are situations where workers fail to restart properly. I suggest doing a stop and then confirm that no workers are running, don't count on pid files to be accurate, check the full process list. Then start the workers again. Also make sure you don't accidentally end up in the old deploy directory when you run the startup. Also certain process managers can get stuck on old working directories causing further issues.

**Comment by cdekker** [comment]
Thanks for the input! Just made sure everything is restarted from scratch. Even rebooted the entire server :)

Rails 5.0 project is running through Passenger / Apache.
DelayedJob is running with 2 workers on their unique PIDs which match those in tmp/pids/delayed_job.x.pid

Still same error on each job about ~4 seconds after creating it (workers run every 5 seconds)

I am still leaning towards a compatibility issue between DJ and Rails 5 :)

Were you able to get it working on Rails 5 yourself?

**Comment by besi** [comment]
@cdekker I just had to comment the following line in `application.rb` in order for `bin/delayed_job start` having work off the jobs:

```ruby
# config.active_job.queue_adapter = :delayed_job
```

I think that this could be some sort of locking issues.

**Comment by albus522** [comment]
Closing stale
