### ISSUE TITLE
rake jobs:work hangs

### ISSUE THREAD

**Issue by laci37** [collectiveidea/delayed_job#941]
I'm using Delayed Jobs with Rails 4.2.5 and the Mongoid backend. I have found a bug that after completing a few jobs the worker starts to hang (does not produce any output). Jobs either aren't inserted in the collection, or they are deleted by the hanging worker almost immediately. Restarting the worker solves the issue, but jobs that should have been queued while the worker hangs, won't begin, since they aren't in the DB. I haven't found any useful data in my logs.

**Comment by albus522** [comment]
Closing stale
