### ISSUE TITLE
Restart jobs terminates current running jobs

### ISSUE THREAD

**Issue by passabilities** [collectiveidea/delayed_job#942]
When I restart jobs, they kill any current jobs running and does not finish, leaving a locked job in the database.

I am restarting the jobs on production so it will refresh the updated code on push. I see that this already happens on development. Is there not a way to do that on production as well?

**Comment by fernandoluizao** [comment]
I have the same problem.

Is there any way to detect that the process that reserved the job is dead, and unlock the job? I'm wondering if its possible to use the pid on the locked_by column...

**Comment by passabilities** [comment]
I spent a good amount of time sorting through the source code to find where it terminates the jobs and keep coming up short. I imagine that it wouldn't be difficult to just update the record in the database to remove the `locked_` columns, which is ultimately the real issue I believe.

**Comment by albus522** [comment]
Normally terminating DJ waits for the job to finish, however daemons has a tendency to get impatient and force kills the process after a certain amount of time. This has the potential to cause a number of issues and is not ideal. Unfortunately, DJ can't automatically immediately unlock the job as nothing can definitively confirm what to unlock. DJ processes can be run on multiple servers to help load balance large workloads, so simply checking live processes isn't enough. Now I did say "immediately" for a reason. After max_run_time has expired, the job is considered unlocked and available regardless of what the locked_by column says.

**Comment by passabilities** [comment]
@albus522 so I see the default `max_run_time` is `4.hours`. Are you saying that after the allotted time, the job will reload the code and restart it, even if the process has been terminated?

**Comment by albus522** [comment]
Yes. The job will be picked up by any running work at that time.

**Comment by fernandoluizao** [comment]
For the record, I found this useful plugin:

https://github.com/salsify/delayed_job_heartbeat_plugin

Each worker will update a heartbeat table, so it works for distributed setups. If a worker dies, it will unlock the job after a short time (configurable). So far, so good :smiley:
