### ISSUE TITLE
Deprecation warning for cleanup and prepare on Rails 5

### ISSUE THREAD

**Issue by DannyBen** [collectiveidea/delayed_job#944]
I am trying to make DelayedJob work on a Rails 5 app.

When running `bin/delayed_job start` I get deprecation warnings in the log:

```
DEPRECATION WARNING: cleanup! is deprecated and will be removed from Rails 5.1 (use Rails.application.reloader.reload! instead of cleanup + prepare) (called from <main> at bin/delayed_job:5)

DEPRECATION WARNING: prepare! is deprecated and will be removed from Rails 5.1 (use Rails.application.reloader.prepare! instead) (called from <main> at bin/delayed_job:5)

Delayed::Backend::ActiveRecord::Job Load (0.4ms)[0m  [1m[37mUPDATE "delayed_jobs" SET locked_at = '2016-09-28 07:19:35.686953', locked_by = 'delayed_job host:ubuntu-xenial pid:6922' WHERE id IN (SELECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2016-09-28 07:19:35.686497' AND (locked_at IS NULL OR locked_at < '2016-09-28 03:19:35.686539') OR locked_by = 'delayed_job host:ubuntu-xenial pid:6922') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
```

The offending code starts in [the generator template](https://github.com/collectiveidea/delayed_job/blob/master/lib/generators/delayed_job/templates/script#L5) which I guess eventually leads to [`Worker#reload!`](https://github.com/collectiveidea/delayed_job/blob/2026cd46ce17192cd8efd876044e2e140fe7b603/lib/delayed/worker.rb#L321)

**Comment by malagant** [comment]
Same here. Any news on this?

**Comment by dg-ratiodata** [comment]
This is true for me too.

**Comment by lysender** [comment]
I'm having the same warnings on rails 5.0.0.1.

**Comment by hammady** [comment]
I have this too. Here is a temporary solution until delayed_job merges #948:

    # config/initializers/dj_rails5_patches.rb
    # RAILS 5 patches for delayed_job
    # TODO: REMOVE WHEN upstream is updated

    module DelayedWorkerPatches
      def reload!
        return unless self.class.reload_app?
        if defined?(ActiveSupport::Reloader)
          Rails.application.reloader.reload!
        else
          ActionDispatch::Reloader.cleanup!
          ActionDispatch::Reloader.prepare!
        end
      end
    end

    module Delayed
      class Worker
        prepend DelayedWorkerPatches
      end
    end

**Comment by atomaka** [comment]
Awesome, @hammady. Thanks for the temporary patch!

**Comment by maurosbu** [comment]
Hope to see this fixed soon!

**Comment by simonknoll** [comment]
It looks like #948 is merged now. Can the issue be closed?

**Comment by toobulkeh** [comment]
Looking forward to seeing this go out in the next version!

**Comment by shrkw** [comment]
Who is willing to release the next version?

**Comment by vuductuyen** [comment]
thank @hammady

**Comment by wfried** [comment]
Hello, I'm getting a warning that Delayed Job requires activerecord < 5.1 when trying to upgrade to Rails 5.1.  Is the blocker just creating a new version?

**Comment by simonknoll** [comment]
Any update on if this issue can be closed?
