### ISSUE TITLE
Fail job on "max_run_time"

### ISSUE THREAD

**Issue by holgersindbaek** [collectiveidea/delayed_job#950]
How can I make a job fail instead of re-running if the job exceeds max_run_time?

**Comment by phil9690** [comment]
@holgersindbaek just set the max_attempts for that job to 1 and it should fail once it exceeds the max_run_time.

```
NewsletterJob = Struct.new(:text, :emails) do
  def perform
    emails.each { |e| NewsletterMailer.deliver_text_to_email(text, e) }
  end

  def max_attempts
    1
  end
end
```

**Comment by holgersindbaek** [comment]
I already have "max_attempts" set as the default in my initializer, but it still tries again and again if a job fails.

**Comment by itsprdp** [comment]
@holgersindbaek I'm running into the same issue as well. By any chance, you figured out the problem?

**Comment by ryanrealscout** [comment]
We have also set `max_attempts` to 1 in our jobs and they are re-run after each timeout.

**Comment by itsprdp** [comment]
Watch out for the `after_commit` or any other `ActiveRecord` hooks. There was a bug in the `after_commit` logic which was leading to cloned DelayedJob entries.

**Comment by albus522** [comment]
Closing stale
