### ISSUE TITLE
DJ reload

### ISSUE THREAD

**Issue by kaogaau** [collectiveidea/delayed_job#953]
I see the document writ the DJ will auto-reload in development mode, but my app doesn't do that, I have to restart my app every time when I changed my code. If any else config must be set? I don't know what's wrong ><.

**Comment by pingram** [comment]
@kaogaau you should make sure that `Rails.application.config.cache_classes` is set to `false` if you want to use the reloading.

**Comment by kaogaau** [comment]
I have set this field to `false`, but it still didn't work. I use the Open-Source that contain delay_job, spring,...and many other gems, so maybe other stuff affect the function, I test and try to find the reason continuously, if I find the answer, I will reply to you guys. 

@pingram  thank for your help, wait for my good news^^

**Comment by kaogaau** [comment]
The answer id the Open-Source that contain `Rails.application.config.cache_classes == true` in somewhere i didn't find it. I set the `Rails.application.config.cache_classes == false` and solve it.

@pingram thanks for your help^^
