### ISSUE TITLE
Delayed job random creation behaviour with handle_asynchronously with rake test

### ISSUE THREAD

**Issue by anjain** [collectiveidea/delayed_job#955]
Delayed job showing random behavior sometimes the job get created and sometimes it gets initialized on running rake test in rails 4........
 #<Delayed::Backend::ActiveRecord::Job:0x00000014b20408
 id: nil,
 priority: 10,
 attempts: 0,
 handler:
  "--- !ruby/object:Delayed::PerformableMethod\nobject: !ruby/object:UserCommentEntry\n  raw_attributes:\n    type: UserCommentEntry\n    subject_id: 1\n    subject_type: UserComment\n    user_id: 1067646470\n    id: 973202260\n    created_at: 2016-11-03 09:39:29.505482609 Z\n    updated_at: 2016-11-03 09:39:29.505482609 Z\n  attributes: !ruby/object:ActiveRecord::AttributeSet\n    attributes: !ruby/object:ActiveRecord::LazyAttributeHash\n      types:\n        id: &4 !ruby/object:ActiveRecord::Type::Integer\n          precision: \n          scale: \n          limit: \n          range: !ruby/range\n            begin: -2147483648\n            end: 2147483648\n            excl: true\n        type: &2 !ruby/object:ActiveRecord::Type::String\n          precision: \n          scale: \n          limit: 255\n        user_id: &1 !ruby/object:ActiveRecord::Type::Integer\n          precision: \n          scale: \n          limit: \n          range: !ruby/range\n            begin: -2147483648\n            end: 2147483648\n            excl: true\n        subject_id: *1\n        subject_type: *2\n        created_at: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n          subtype: &3 !ruby/object:ActiveRecord::Type::DateTime\n            precision: \n            scale: \n            limit: \n        updated_at: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n          subtype: *3\n      values:\n        id: \n        type: \n        user_id: \n        subject_id: \n        subject_type: \n        created_at: \n        updated_at: \n      additional_types: {}\n      materialized: true\n      delegate_hash:\n        type: !ruby/object:ActiveRecord::Attribute::FromUser\n          name: type\n          value_before_type_cast: UserCommentEntry\n          type: *2\n          value: UserCommentEntry\n        subject_id: !ruby/object:ActiveRecord::Attribute::FromUser\n          name: subject_id\n          value_before_type_cast: 1\n          type: *1\n          value: 1\n        subject_type: !ruby/object:ActiveRecord::Attribute::FromUser\n          name: subject_type\n          value_before_type_cast: UserComment\n          type: *2\n          value: UserComment\n        user_id: !ruby/object:ActiveRecord::Attribute::FromUser\n          name: user_id\n          value_before_type_cast: 1067646470\n          type: *1\n          value: 1067646470\n        id: !ruby/object:ActiveRecord::Attribute::FromUser\n          name: id\n          value_before_type_cast: 973202260\n          type: *4\n          value: 973202260\n        created_at: !ruby/object:ActiveRecord::Attribute::FromUser\n          name: created_at\n          value_before_type_cast: 2016-11-03 09:39:29.505482609 Z\n          type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n            subtype: *3\n          value: 2016-11-03 09:39:29.505482609 Z\n        updated_at: !ruby/object:ActiveRecord::Attribute::FromUser\n          name: updated_at\n          value_before_type_cast: 2016-11-03 09:39:29.505482609 Z\n          type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n            subtype: *3\n          value: 2016-11-03 09:39:29.505482609 Z\n  new_record: false\nmethod_name: :deliver_later_without_delay!\nargs: []\n",
 last_error: nil,
 run_at: nil,
 locked_at: nil,
 failed_at: nil,
 locked_by: nil,
 created_at: nil,
 updated_at: nil,
 queue: "newsfeed">
See above job gets initialized with no created_at and updated_at.This happens randomly and i am unable to fetch the issue.

**Comment by albus522** [comment]
If a job saves or not is dependent on the result of `Delayed::Worker.delay_jobs`. If DJ is disabled via this configuration, the job just runs. It does not save.
