### ISSUE TITLE
Overriding logger in custom Job class

### ISSUE THREAD

**Issue by hspazio** [collectiveidea/delayed_job#958]
Hi everyone,
Is it possible to override `Delayed::Worker.logger` when using a custom Job class?

I would like each of my jobs to log to different files. Currently it's possible to override most of the Worker's attributes in the Job class

```ruby
class ExpensiveJob
  def perform
    # do something ...
  end

  # this override works
  def max_run_time
    60 * 60
  end

  # this override does not work
  # this could tell Delayed::Worker to use the job's logger if defined otherwise the default one.
  def logger
    Logger.new('log/jobs/expensive_job.log')
  end
end
```

I could work on a PR if there isn't a solution already.

**Comment by albus522** [comment]
Within `perform` you can change `Delayed::Worker.logger` to whatever you want, then change it back to its original value in an `ensure` clause.

**Comment by albus522** [comment]
Be aware `Delayed::Worker.logger` is only DJ messages. You may also need to change where `Rails.logger` points depending on your intentions.

**Comment by hspazio** [comment]
thank you @albus522! will try this out.
