### ISSUE TITLE
DelayedJob queue is not working

### ISSUE THREAD

**Issue by nazeef-ahmad-confiz** [collectiveidea/delayed_job#959]
I am using delayed_job gem in my rails application, gem version is :  4.03 
I have assigned particular workers for 2 queues e.g --queue=pictures , --queue=* 
One queue is for processing pictures and other is for everything else. 
But the problem is this queue priority scheme is not working. what am I doing wrong? 

This is the code : 

check process delayed_job_1 with pidfile /var/rails/apps/pakwheels_production/current/tmp/pids/delayed_job.1.pid
        start program = "/sbin/runuser -l pakboard -c 'cd /var/rails/apps/pakwheels_production/current && RAILS_ENV=production bundle exec script/delayed_job -i 1 start --queue=pictures'"
        stop program = "/sbin/runuser -l pakboard -c 'cd /var/rails/apps/pakwheels_production/current && RAILS_ENV=production bundle exec script/delayed_job -i 1 stop --queue=picture'"
        if mem is greater than 500.0 MB for 1 cycles then restart
        if cpu is greater than 80% for 5 cycles then restart

check process delayed_job_2 with pidfile /var/rails/apps/pakwheels_production/current/tmp/pids/delayed_job.2.pid
        start program = "/sbin/runuser -l pakboard /bin/bash -c 'cd /var/rails/apps/pakwheels_production/current && RAILS_ENV=production bundle exec script/delayed_job -i 2 start --queue=pictures'"
        stop program = "/sbin/runuser -l pakboard /bin/bash -c 'cd /var/rails/apps/pakwheels_production/current && RAILS_ENV=production bundle exec script/delayed_job -i 2 stop --queue=pictures'"
        if mem is greater than 500.0 MB for 1 cycles then restart
        if cpu is greater than 80% for 5 cycles then restart

check process delayed_job_3 with pidfile /var/rails/apps/pakwheels_production/current/tmp/pids/delayed_job.3.pid
        start program = "/sbin/runuser -l pakboard /bin/bash -c 'cd /var/rails/apps/pakwheels_production/current && RAILS_ENV=production bundle exec script/delayed_job -i 3 start --queue=*'"
        stop program = "/sbin/runuser -l pakboard /bin/bash -c 'cd /var/rails/apps/pakwheels_production/current && RAILS_ENV=production bundle exec script/delayed_job -i 3 stop --queue=*'"

**Comment by albus522** [comment]
If you desire the everything else workers to not process picture jobs, you need to set a default queue and have those workers pull from the default queue and any other queues you may use.
