### ISSUE TITLE
Delayed Job terminates on loss of db connection (psql)

### ISSUE THREAD

**Issue by haikobleumink** [collectiveidea/delayed_job#961]
Some environment information:
I have a wrapper script for delayed_job which starts up delayed_job using 5 workers.
This script can be managed using systemctl.
My application currently uses delayed_job_active_record version 4.1.1 after a 'bundle update'

When the application is started the status using systemctl looks like this:
> systemctl status testlab-manager
> ● testlab-manager.service - LSB: testlab-manager delayed jobs workers
>    Loaded: loaded (/etc/init.d/testlab-manager)
>   Drop-In: /etc/systemd/system/testlab-manager.service.d
>            └─myenv.conf
>    Active: active (running) since Wed 2017-01-04 15:47:10 CET; 17h ago
>   Process: 6963 ExecStop=/etc/init.d/testlab-manager stop (code=exited, status=0/SUCCESS)
>   Process: 6994 ExecStart=/etc/init.d/testlab-manager start (code=exited, status=0/SUCCESS)
>    CGroup: /system.slice/testlab-manager.service
>            ├─7013 delayed_job.0
>            ├─7021 delayed_job.1
>            ├─7028 delayed_job.2
>            ├─7035 delayed_job.3
>            └─7042 delayed_job.4
> 
> Jan 04 15:47:04 devel-o13 systemd[1]: Starting LSB: testlab-manager delayed jobs workers...
> Jan 04 15:47:04 devel-o13 sudo[6997]: root : TTY=unknown ; PWD=/ ; USER=qnet ; ENV=RAILS_ENV=development ; COMMAND=/home/qnet/testlab-manager/script/delayed_job start -n 5
> Jan 04 15:47:04 devel-o13 sudo[6997]: pam_unix(sudo:session): session opened for user qnet by (uid=0)
> Jan 04 15:47:10 devel-o13 systemd[1]: Started LSB: testlab-manager delayed jobs workers.
> Jan 04 15:47:10 devel-o13 testlab-manager[6994]: Starting testlab-manager delayed jobs workers.

But the problem occurs when postgresql is restarted, because after a '/etc/init.d/postgresql restart'

The status is the following after the restart:

> systemctl status testlab-manager
> ● testlab-manager.service - LSB: testlab-manager delayed jobs workers
>    Loaded: loaded (/etc/init.d/testlab-manager)
>   Drop-In: /etc/systemd/system/testlab-manager.service.d
>            └─myenv.conf
>    Active: active (exited) since Thu 2017-01-05 09:18:26 CET; 22s ago
>   Process: 19994 ExecStop=/etc/init.d/testlab-manager stop (code=exited, status=0/SUCCESS)
>   Process: 20016 ExecStart=/etc/init.d/testlab-manager start (code=exited, status=0/SUCCESS)
> 
> Jan 05 09:18:23 devel-o13 systemd[1]: Starting LSB: testlab-manager delayed jobs workers...
> Jan 05 09:18:23 devel-o13 testlab-manager[19994]: .
> Jan 05 09:18:23 devel-o13 sudo[20020]: root : TTY=unknown ; PWD=/ ; USER=qnet ; ENV=RAILS_ENV=development ; COMMAND=/home/qnet/testlab-manager/script/delayed_job start -n 5
> Jan 05 09:18:23 devel-o13 sudo[20020]: pam_unix(sudo:session): session opened for user qnet by (uid=0)
> Jan 05 09:18:26 devel-o13 systemd[1]: Started LSB: testlab-manager delayed jobs workers.
> Jan 05 09:18:26 devel-o13 testlab-manager[20016]: Starting testlab-manager delayed jobs workers.

And delayed_job is not alive anymore.

The logging that delayed_job produced is:
`
2017-01-05 09:18:40.779 [DEBUG] PG::UnableToSend: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
: UPDATE "delayed_jobs" SET locked_at = '2017-01-05 08:18:40.748856', locked_by = 'delayed_job.0 host:devel-o13 pid:20032' WHERE id IN (SELECT  id FROM "delayed_jobs"  WHERE ((run_at <= '2017-01-05 08:18:40.747631' AND (locked_at IS NULL OR locked_at < '2017-01-05 07:18:40.747666') OR locked_by = 'delayed_job.0 host:devel-o13 pid:20032') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING * (pid:20032)
2017-01-05 09:18:40.791 [DEBUG] PG::ConnectionBad: PQsocket() can't get socket descriptor:             SELECT COUNT(*)
            FROM pg_class c
            LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind in ('v','r')
            AND c.relname = 'delayed_jobs'
            AND n.nspname = ANY (current_schemas(false)) (pid:20032)
2017-01-05 09:18:40.791 [FATAL] PG::ConnectionBad: PQsocket() can't get socket descriptor:             SELECT COUNT(*)
            FROM pg_class c
            LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind in ('v','r')
            AND c.relname = 'delayed_jobs'
            AND n.nspname = ANY (current_schemas(false)) (pid:20032)
2017-01-05 09:18:40.874 [DEBUG] PG::UnableToSend: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
`
Why is this happening and is the database connection not restored after a restart?

**Comment by albus522** [comment]
DJ just uses rails connection handling. We do not do anything special other than reconnect after forking the worker processes so we can guarantee we don't share the same db connection between multiple processes. All connection handling is purely ActiveRecord's internal connection pool. 

Interestingly, that error message implies that your restart command did not do a safe restart, but instead aborted an in process update query which is quite dangerous for db consistency.
