### ISSUE TITLE
Method to find jobs associated with specific model

### ISSUE THREAD

**Issue by obfuscoder** [collectiveidea/delayed_job#962]
We use delayed_job to handle all communication work with backend systems which could take longer or fail sometimes. We also do contract management with this (creating contracts, provisioning, contract termination, etc.). We also have some business monitoring which allows us to see the status of customers and their processes. What we cannot show on a customers process details is the list of delayed jobs still pending for execution or which have run into an error and which will be tried again and when.

We would like to better associate a delayed job entry with specific models so that we can find the jobs associated to specific customers and list them (and possible cancel/retry them manually via the business monitoring frontend).

One solution which I could think of was creating a table defining a many-to-many connection between customers and delayed jobs and add an with whatever DelayedJob#enqueue returns. The problem here is that DJ deletes entries from the delayed_jobs table, but not from the many-to-many table. Another option would be to add a FK-column to the delayed_jobs table itself which points to the customer. Can I somehow set this column during a call to enqueue or would I need to do this after the enqueue?

**Comment by albus522** [comment]
This isn't something DJ is built to handle.

**Comment by obfuscoder** [comment]
Wow. I put so much work into explaining my intentions and question and am quite disappointed by the late, short and negtive response. Is this not a reasonable use case to find delayed jobs associated with a specific model instance to allow those jobs to be terminated when an update of that model instance's state renders the job obsolete?

**Comment by albus522** [comment]
It is a perfectly reasonable thing to do. It is not something we can reasonably support across all of DJ's supported databases and implementations. Also most use cases are very application specific and don't generally apply to all apps. If you want to put together a plugin that works in a limited subset of things that is fine, but it isn't something we have the ability to make widely supported across the DJ ecosystem.

If you would like to discuss possible things you can do in your app to track a running job, you can use the mailing list http://groups.google.com/group/delayed_job but this is not an issue/problem with DJ.
