### ISSUE TITLE
How to REMOVE these log in production.log.

### ISSUE THREAD

**Issue by qx** [collectiveidea/delayed_job#965]
D, [2017-02-20T23:42:51.836366 #15203] DEBUG -- :   Delayed::Backend::ActiveRecord::Job Load (2.2ms)  UPDATE "delayed_jobs" SET locked_at = '2017-02-20 23:42:51.833020', locked_by = 'delayed_job host:iZ234gc0upsZ pid:15203' WHERE id IN (SELECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2017-02-20 23:42:51.831862' AND (locked_at IS NULL OR locked_at < '2017-02-20 19:42:51.832018') OR locked_by = 'delayed_job host:iZ234gc0upsZ pid:15203') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *

Actually, the table of delayed_jobs is empty!  how can I remove this boring log?

**Comment by albus522** [comment]
Set the logger level above "debug"

**Comment by mib32** [comment]
@albus522 But if I set it like this, then the Rails logger also stops outputting DEBUG! Which is not what I want. 

I also tried dupping:

```
Delayed::Worker.logger = Delayed::Worker.logger.dup
Delayed::Worker.logger.level = Rails.env.dev? ? :debug : :info
Delayed::Worker.raise_signal_exceptions = :term
Delayed::Worker.max_run_time = 30.minutes
Delayed::Worker.max_attempts = 0
```

Though it is not working - I still get debug messages
