### ISSUE TITLE
Keep forking threads in delayed job process

### ISSUE THREAD

**Issue by McGar** [collectiveidea/delayed_job#966]
Hi guys

I found delayed job took too much memory and also used a lot of cpu resources, then did some research and found out delayed job process kept forking threads and there were like thousands of threads within each delayed job process,

ps -efL | grep delayed_job.0
root     28540     1 28540  0  167 05:43 ?        00:01:14 delayed_job.0
root     28540     1  4358  0  167 06:04 ?        00:00:00 delayed_job.0
root     28540     1  4359  0  167 06:04 ?        00:00:00 delayed_job.0
root     28540     1  4360  0  167 06:04 ?        00:00:00 delayed_job.0
root     28540     1  4361  0  167 06:04 ?        00:00:00 delayed_job.0
root     28540     1  4362  0  167 06:04 ?        00:00:00 delayed_job.0
root     28540     1  4374  0  167 06:04 ?        00:00:00 delayed_job.0
root     28540     1  4375  0  167 06:04 ?        00:00:00 delayed_job.0
root     28540     1  4376  0  167 06:04 ?        00:00:00 delayed_job.0
root     28540     1  4377  0  167 06:04 ?        00:00:00 delayed_job.0
root     28540     1  4378  0  167 06:04 ?        00:00:00 delayed_job.0
root     28540     1  4379  0  167 06:04 ?        00:00:00 delayed_job.0
root     28540     1  4380  0  167 06:04 ?        00:00:00 delayed_job.0
root     28540     1  4553  0  167 06:04 ?        00:00:00 delayed_job.0
root     28540     1 10202  0  167 06:17 ?        00:00:00 delayed_job.0
root     28540     1  5364  0  167 07:20 ?        00:00:00 delayed_job.0
root     28540     1  9220  0  167 07:30 ?        00:00:00 delayed_job.0
root     28540     1 11422  0  167 07:35 ?        00:00:00 delayed_job.0
root     28540     1 11423  0  167 07:35 ?        00:00:00 delayed_job.0
root     28540     1 28038  0  167 08:15 ?        00:00:00 delayed_job.0
root     28540     1 28039  0  167 08:15 ?        00:00:00 delayed_job.0
root     28540     1 28040  0  167 08:15 ?        00:00:00 delayed_job.0
...

Any ideas about if this is a bug or it's normal? Or anyway to solve this issue?

BTW, we're using

Linux 4.4.0-31-generic #50~14.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
   
 delayed_job (3.0.5)
      activesupport (~> 3.0)
    delayed_job_active_record (0.4.4)
      activerecord (>= 2.1.0, < 4)
      delayed_job (~> 3.0)

   ruby-1.9.3-p392

    rails (3.2.22.4)
      actionmailer (= 3.2.22.4)
      actionpack (= 3.2.22.4)
      activerecord (= 3.2.22.4)
      activeresource (= 3.2.22.4)
      activesupport (= 3.2.22.4)
      bundler (~> 1.0)
      railties (= 3.2.22.4)

Thanks a lot.

**Comment by albus522** [comment]
Delayed job doesn't use threads. Something else is starting threads within the worker process. Potentially a job you are running or a library you are using.
