### ISSUE TITLE
Rails mailer with action name = "success" cause exception

### ISSUE THREAD

**Issue by amerov** [collectiveidea/delayed_job#967]
![selection_044](https://cloud.githubusercontent.com/assets/196747/23929324/160ea0f2-0947-11e7-8f6d-30ba3850fe88.png)
![selection_045](https://cloud.githubusercontent.com/assets/196747/23929325/1611541e-0947-11e7-9137-473a37d38c0b.png)
![selection_046](https://cloud.githubusercontent.com/assets/196747/23929326/16156f36-0947-11e7-889c-de6a1993abb8.png)

**Comment by jous32** [comment]
What is that IDE??

**Comment by amerov** [comment]
@jous32 https://www.jetbrains.com/ruby/

**Comment by amerov** [comment]
by the way, the action performs and to spammed! :angry:

**Comment by albus522** [comment]
Closing stale
