### ISSUE TITLE
delayed_job turn off belongs_to_required_by_default

### ISSUE THREAD

**Issue by tongchaimd** [collectiveidea/delayed_job#969]
after I add delayed_job into Gemfile belongs_to_required_by_default is turned off.

add this to config/application.rb fixed the problem
config.active_record.belongs_to_required_by_default = true

I'm sorry if this is a feature.

**Comment by albus522** [comment]
`belongs_to_required_by_default` is no where in our codebase. What are you asking for? Why are you asking for it?
