### ISSUE TITLE
rate limits

### ISSUE THREAD

**Issue by eiked** [collectiveidea/delayed_job#971]
I have problems with the discogs api
they need throttle

This should be build into delayed_jobs

I'd like to enhace delayed_jobs
to add rate limiting

I'd like to configure max requests/second
and delayed_jobs should take care of that

This should be per queue
and also respecting that for reissuing jobs

**Comment by albus522** [comment]
DJ is designed to work though jobs as fast as it can. Rate limiting is not part of the architecture. To do what you want, you could track an external rate limit and when the job starts check if the rate limit would be exceeded. If it would be exceeded re-queue the job with a `run_at` time after the rate limit would expire.
