### ISSUE TITLE
Testing failure hook

### ISSUE THREAD

**Issue by bruschill** [collectiveidea/delayed_job#973]
I've been trying for the past couple of days to write an RSpec test that tests that the failure hook gets called, but to no avail.

### Classes
```ruby
class ApplicationJob < ActiveJob::Base
end

class CreateBondInDominoJob < ApplicationJob
  def perform(bond_hash)
    raise "it failed"
  end
end
```

### Spec
```ruby
RSpec.describe CreateBondInDominoJob, type: :job do
  include ActiveJob::TestHelper

  before do
    @job = CreateBondInDominoJob.perform_later({})
  end

  it "prints the failure message" do
    25.times do
      Delayed::Worker.new.run(@job)
    end
  end
end
```
Essentially what I'm trying to do is get the the test to error 25 times (the default attempt limit) so that the `failure` hook is called, but I can't for the life of me get it to work.

Now this exact test fails due to `NoMethodError: undefined method 'error='`, but my other past attempts have also not worked.

Thanks in advance for your help!

**Comment by albus522** [comment]
Check that DJ is set as the ActiveJob handler in the test env. Make sure DJ is enabled in the test env `Delayed::Worker.delay_jobs = true`. Also make sure that ActiveJob is enable to background jobs. Check that `@job` is an instance of `Delayed::Job` as I am not sure what `perform_later` actually returns. Lastly do not create a new worker instance for every call, while that isn't likely your issue, it can have some nasty side effects.

**Comment by bruschill** [comment]
`perform_later` returns an instance of the job class itself:
- `#<CreateBondInDominoJob:0x007fd285989608 ... >`

How would you recommend running the same job again?

**Comment by albus522** [comment]
`Delayed::Worker` needs the `Delayed::Job` instance, not the job class instance. Probably `Delayed::Job.first` in your test case

**Comment by bruschill** [comment]
Is `Delayed::Job.first` just for returning a `Delayed::Job` instance? After calling `CreateBondInDominoJob.perform_later({})`, `Delayed::Job.first` returns nothing. Is that because it's getting processed?

**Comment by albus522** [comment]
That means ActiveJob is not configured to use DJ in tests and/or `Delayed::Worker.delay_jobs` is false.

**Comment by bruschill** [comment]
ActiveJob is (or at least should be) configured properly:

### `config/environments/test.rb`
```ruby
Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # The test environment is used exclusively to run your application's
  # test suite. You never need to work with it otherwise. Remember that
  # your test database is "scratch space" for the test suite and is wiped
  # and recreated between test runs. Don't rely on the data there!
  config.cache_classes = true

  # Do not eager load code on boot. This avoids loading your whole application
  # just for the purpose of running a single test. If you are using a tool that
  # preloads Rails for running tests, you may have to set it to true.
  config.eager_load = false

  # Configure public file server for tests with Cache-Control for performance.
  config.public_file_server.enabled = true
  config.public_file_server.headers = {
    'Cache-Control' => 'public, max-age=3600'
  }

  # Show full error reports and disable caching.
  config.consider_all_requests_local       = true
  config.action_controller.perform_caching = false

  # Raise exceptions instead of rendering exception templates.
  config.action_dispatch.show_exceptions = false

  # Disable request forgery protection in test environment.
  config.action_controller.allow_forgery_protection = false
  config.action_mailer.perform_caching = false

  # Tell Action Mailer not to deliver emails to the real world.
  # The :test delivery method accumulates sent emails in the
  # ActionMailer::Base.deliveries array.
  config.action_mailer.delivery_method = :test

  # Print deprecation notices to the stderr.
  config.active_support.deprecation = :stderr

  # Raises error for missing translations
  # config.action_view.raise_on_missing_translations = true

  # Randomize the order test cases are executed.
  config.active_support.test_order = :random

  config.active_job.queue_adapter = :delayed_job
end
```

### `config/application.rb`
```ruby
require_relative 'boot'
require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Hubble
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    config.time_zone = 'Central Time (US & Canada)'

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    # config.i18n.default_locale = :de

    # Autoload anything in lib/constraints
    config.eager_load_paths += %W( #{config.root}/lib/constraints )

    config.active_job.queue_adapter = :delayed_job
  end
end
```

And `Delayed::Worker.delay_jobs` is set to `true` in the initializer:

### `config/initializers/delayed_job_config.rb`
```ruby
Delayed::Worker.sleep_delay = 1
Delayed::Worker.destroy_failed_jobs = false
Delayed::Worker.delay_jobs = true
```

Is there something else I'm missing here?

**Comment by albus522** [comment]
Looks like ActiveJob may be running some testing interference http://www.rubydoc.info/gems/activejob/5.0.2/ActiveJob/TestHelper
I do not know enough about ActiveJob's internals to know how to get around that.

**Comment by bruschill** [comment]
You were right about ActiveJob running testing interference.

After removing `include ActiveJob::TestHelper` in the spec allowed me to get the job to fail:

```ruby
RSpec.describe CreateBondInDominoJob, type: :job do
  before do
    CreateBondInDominoJob.perform_later({})
  end

  it 'fails after 25 attempts' do
    #job => #<Delayed::Backend::ActiveRecord::Job:0x007fc3664b0808>
    job = Delayed::Job.first

    25.times do
      Delayed::Worker.new.run(job)
    end

    #this passes
    expect(job.failed_at).to_not be_nil
  end
end
```

After updating `#failure(job)` in `CreateBondInDominoJob` to deliver the mailer,

```ruby
class CreateBondInDominoJob < ActiveJob
  #...

  def failure(job)
    DominoBondCreationFailureMailer.failure_notification.deliver
  end
end
```

I'm still unable to verify that the mailer is sent.

```ruby
RSpec.describe CreateBondInDominoJob, type: :job do
  before do
    CreateBondInDominoJob.perform_later({})
  end

  # other test

  it 'sends an email' do
    #this fails
    expect(DominoBondCreationFailureMailer).to receive_message_chain(:failure_notification, :deliver)

    job = Delayed::Job.first

    25.times do
      Delayed::Worker.new.run(job)
    end
  end
end
```

Any thoughts/suggestions?

**Comment by FLemon** [comment]
@bruschill 
i ran into the same problem, and my research shows that because you(and me) are using activeJob as the bridge to integrate with DJ, because both ActiveJob implements `#perform` which delegated to DJ's `#perform`, but ActiveJob does not implement hook method to delegate to DJ's `#failure`, hence, I am guessing this is why it is not being triggered...
I am still working this out...but if you get any further, please let me know, thank you

**Comment by FLemon** [comment]
further to my last comment, I've dig in more, and find that, in the DJ's lefecycle, [when a job is marked as failed `#failed(job)` call in the Worker](https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/worker.rb#L255)
[it will call the hook methods](https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/worker.rb#L262),
and if the job payload object respond to the hook methods(error, failure, etc)](https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/backend/base.rb#L99)
if will excuse the method, however, the payload_object there is a `ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper` object, which does not implement `failure, error, etc`. hence it does not respond to the hook method, and the worker skips this step

am looking for solutions to this cases

^ @albus522 ?

**Comment by FLemon** [comment]
I've have my own fix for this, I think it is ActiveJob's issue, hence posted a bug report, and a patch that will do the fix
https://github.com/rails/rails/issues/30205

**Comment by albus522** [comment]
Closing stale
