### ISSUE TITLE
Rails 5.1 DEPRECATION WARNING

### ISSUE THREAD

**Issue by Shooshpanius** [collectiveidea/delayed_job#977]
DEPRECATION WARNING: cleanup! is deprecated and will be removed from Rails 5.1 (use Rails.application.reloader.reload! instead of cleanup + prepare) (called from <top (required)> at bin/delayed_job:5)

DEPRECATION WARNING: prepare! is deprecated and will be removed from Rails 5.1 (use Rails.application.reloader.prepare! instead) (called from <top (required)> at bin/delayed_job:5)

**Comment by albus522** [comment]
Fixed in master
