### ISSUE TITLE
Testing :handle_asynchronously methods

### ISSUE THREAD

**Issue by stevenspiel** [collectiveidea/delayed_job#979]
I'm using Rails 5, Rspec 3.5.0 and delayed_job 4.1.2

I have a class:

```rb
class Scheduler
  def schedule_emails
    SomeMailer.the_email.deliver_later(wait_until: Date.today + 1.day)
  end
  handle_asynchronously :schedule_emails
end
```

And I want to test that the delayed_job record is scheduled for the expected date:

```rb
describe '#schedule_emails' do
  it 'schedules emails for the correct date'
    expect { Scheduler.schedule_emails }.to change { Delayed::Job.count }.by(1)
    expect(Delayed::Job.last.run_at).to eq Date.today + 1.day
  end
end
```

The method doesn't run because it is handled asynchronously. And so I added `Delayed::Worker.delay_jobs = false` but that makes the mailer run, as well.

So, my questions are:

1) Is there a way to turn off the :handle_asynchronously flag when calling the method directly (like in a spec that is testing that method)

2) In testing, scoped to specific blocks, is there a way to run delayed job while adhering to the `run_at` timestamp (or `wait_until` with mailers)?

**Comment by stevenspiel** [comment]
It appears that `:handle_asynchronously` methods may be called directory by [appending `_without_delay` to the end of the method](https://github.com/collectiveidea/delayed_job#parameters). 

However, I am still curious about question 2

**Comment by stevenspiel** [comment]
And [the answer to question 2](https://gist.github.com/dblock/3370052#gistcomment-1610733) is:

```rb
Delayed::Worker.delay_jobs = ->(job) {
  job.run_at && job.run_at > Time.now.utc
}
```

4.1.0 allows Delayed::Worker.delay_jobs to be a proc (ce88693)

**Comment by hugoh59** [comment]
What about methods like after_create inside the model?
