### ISSUE TITLE
DJ process stop running alone

### ISSUE THREAD

**Issue by monteirobrena** [collectiveidea/delayed_job#984]
I've been a problem using delayed_job to send email in the background. Without any reason, the process appears frequently as no running. I've one server to run my application and other only to run the jobs. 

That's my configuration of production deploy:

**config/deploy/production.rb**
```
# APP
server '0.0.0.0', port: 22, roles: [:web, :app, :db], primary: true

# JOBS
role :jobs,                   '0.0.0.0'
set :delayed_job_server_role, :jobs
set :rails_env,               'production'
set :branch,                  :master
set :stage,                   :production

```

I'm using this gems:

**Gemfile**

```
gem 'delayed_job_active_record', '~> 4.1', '>= 4.1.1'                                                                                                
gem 'daemons', '~> 1.2', '>= 1.2.4'                                                                                                                  
gem 'delayed_job_web', '~> 1.2', '>= 1.2.10'                                                                                                         
gem 'whenever', '~> 0.9.7', require: false    
gem 'capistrano3-delayed-job', '~> 1.7', '>= 1.7.2' 
```

Also, I'm not sure if I need to have my application running on both servers...

**Comment by albus522** [comment]
What do the logs tell you?

**Comment by monteirobrena** [comment]
@albus522 unfortunately, I couldn't find anything that helps to identify when and why it's been stopped. No errors, no warning.

**Comment by ngeren** [comment]
I've been seeing similar behavior too. I've checked system logs, rails logs, and even setup an independent logger for delayed job ..not a thing is being outputted prior to the process failing. My next test will be to run it in the foreground and redirect output to a file handle to see if I can come up to something. Will post an update if I do, otherwise, time for a process watchdog.

**Comment by ngeren** [comment]
Process is still failing without anything logged after several days --- in my case about a week. I gave up trying to get something out of it and threw in a "-m" flag to the delayed_job start command. This flag runs an extra monitoring process through the daemon gem that watches and restarts the process when it fails. The exact command for usage for me is:

RAILS_ENV=production bin/delayed_job -m start

**Comment by albus522** [comment]
Closing stale
