### ISSUE TITLE
DJ stopping process when worker is processing job

### ISSUE THREAD

**Issue by RyanVerhey** [collectiveidea/delayed_job#985]
I'm not sure if this is a current feature or not, but after sending the stop command, DJ does not wait to kill the process even if a worker is currently working on a job. If it is supposed to wait, then that is not working, but if it is supposed to wait, then I believe that would be a helpful feature. We restart workers and processes when deploying to production with Capistrano, and it would be nice to not have to check every time if there are any active jobs before deploying.

**Comment by albus522** [comment]
DJ does wait, however some process management handlers give the process a fixed amount of time to exit after sending a standard term signal after which it sends a kill signal which DJ can do nothing about as the OS simply stops running the process.

**Comment by RyanVerhey** [comment]
Thank you for your reply. We're not killing the process, however, using the `kill` command or anything like that. We're using the `script/delayed_job -n 9 stop` command, so it's going through DJ before anything happens. Is there a reason it doesn't wait in that scenario?

**Comment by albus522** [comment]
I wish that were going through DJ, however, that is mostly going through the daemons gem. The daemons gem comes with a lot of functionality that makes things way more reliable across more platforms than manual handling, but it comes with side effects and bugs that have plagued us for years. One of the side effects is that daemons does a dual sweep stop operation. First it goes through and asks everything to quit nicely. Then it waits for a bit but gets impatient and hard kills everything. You can get around this by telling it not to wait with a nowait option but then you don't know that all the processes have finished.

**Comment by RyanVerhey** [comment]
I see. This may be beyond the scope of DJ, but even when passing a `force_kill_waittime` option to daemons, sending the stop command kills a running process immediately. I tested this by setting up a job that had `sleep 60` and daemons had a `force_kill_waittime` of 30, and the process was killed immediately.

**Comment by albus522** [comment]
Do you have `Delayed::Worker.raise_signal_exceptions` set to anything other than false?

**Comment by RyanVerhey** [comment]
I have it set to `:term`

**Comment by albus522** [comment]
That is why it dies. That means a ruby signal exception will be raised in your job. Error handling will finish and the process exits. It is behaving exactly as it should.

**Comment by RyanVerhey** [comment]
You're very right, I just tested it. That option was set by someone at my company who left, so I didn't know it was there or what it did, but now it makes sense. You saved us a lot of time debugging. Thank you!
