### ISSUE TITLE
DJ worker failing with SIGQUIT

### ISSUE THREAD

**Issue by begor** [collectiveidea/delayed_job#986]
Hi! 
About 2-3 times per week my DJ workers dies with SIGQUIT. 
The only thing in logs is:

```
E, [2017-06-14T17:03:45.400674 #126515] ERROR -- : 2017-06-14T17:03:45+0300: [Worker(delayed_job.12 host:...)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=...) FAILED (0 prior attempts) with SignalException: SIGQUIT
```

So I should restart workers manually, which is quite annoying.
In my config I don't have `Delayed::Worker.raise_signal_exceptions = :term`.
What may cause this kind of trouble?

**Comment by albus522** [comment]
SIGQUIT is not SIGTERM. DJ only catches TERM and INT. Everything else will bubble up in your jobs. You have something in your server environment sending the DJ process a QUIT signal. There are many ways this can happen and might even be something like an incorrect PID file for a different process type that normally responds to QUIT. To be clear, nothing in DJ or any of DJ's process management uses or responds to the QUIT signal.
