### ISSUE TITLE
Execute Job in a transaction

### ISSUE THREAD

**Issue by fab-girard** [collectiveidea/delayed_job#991]
Hello,
I've searched a similar issue without success except this one #585 closed.

In my personnal use of DJ, I need to execute job in a sql transaction which includes deletion of the job (performed by DJ infrastructure).
In my case, I perform inside job heavy operations in database (postgres) which are really commited by postgres after the deletion of job (even if update/delete in database are correctly ordered). It seems to occur more often depending of the hardware: SSD (rarely) vs HDD (more often) hard disks.

Transaction is fixing my problem but I need a hook in DJ to set my transaction around job perform AND job deletion. I cannot find this hook in DJ documentation...
A possible implementation (if this not already exists) could be to implement an `around` function on Struct/Job class (like existing `before` cb for instance) with a block.

For the moment, I'm working with a monkey patch of `Delayed::Worker::run` method (which adds the transaction which is fixing my problem.
```
Delayed::Worker.class_eval do
  alias_method :run_was, :run
  def run(job)
    ActiveRecord::Base.transaction do
      run_was job
    end
  end
end
```

Thanks for your support,
Fab

**Comment by albus522** [comment]
Closing stale
