### ISSUE TITLE
Using worker pools with `bin/delayed_job run` does not seem to create a pool

### ISSUE THREAD

**Issue by caalberts** [collectiveidea/delayed_job#992]
I started a delayed job worker process using Supervisord and the `supervisord.conf` is as follows:

```
[program:delayed_job]
command = bin/delayed_job --pool=important:5 --pool=*:1 run
```

Using `start`, I could see the 6 PIDs created and 5 of them are working the jobs off the `important` queue and the workers are concurrently working on the jobs.

However, when I used `run`, I'm not able to see if there are indeed 5+1 workers. The jobs are also being worked on sequentially.

Has anyone used worker pools with supervisord, and if so, how did you configure supervisord?

**Comment by rvfx** [comment]
`run` isn't working for me either in the latest version of DJ. No pid is created and the jobs stay untouched in the database. I noticed this locally without working with a pool. `start` works great though.

**Comment by toao** [comment]
I'm having the same issue (nothing happens, even with a simple ```bin/delayed_job run```) on v4.1.4.
any updates?

**Comment by albus522** [comment]
`run` does not have the ability to spawn multiple processes. You have to use `start` to do that.

**Comment by albus522** [comment]
Closing stale
