### ISSUE TITLE
Jobs in failed state remain locked

### ISSUE THREAD

**Issue by claytron** [collectiveidea/delayed_job#993]
When you set `destroy_failed_jobs = false` and you reach the `max_attempts`, the job is updated with the `failed_at` timestamp. The problem is that the `locked_at` and `locked_by` attributes are never cleared. This makes things like delayed_job_web show a large number of "working" jobs when they are actually just "failed".

**Comment by albus522** [comment]
The fields aren't cleared because they don't need to be and could be valuable debugging info if something has gone wrong.

This is a bug in delayed_job_web, not DJ
