### ISSUE TITLE
 MySQL deadlock when a job is complete 

### ISSUE THREAD

**Issue by varun-gupta4u** [collectiveidea/delayed_job#997]
I am running 6 processes of delayed_job and queued some thousands jobs that takes couple hundred ms to complete. Jobs looks like to be completed successfully but some times errors are thrown while trying to remove the job after completion.

Also i have tried [https://github.com/collectiveidea/delayed_job_active_record]() this, but it won't helped me still facing the issue.

My gem file 

`    delayed_job (4.1.3)
      activesupport (>= 3.0, < 5.2)
    delayed_job_active_record (4.1.2)
      activerecord (>= 3.0, < 5.2)
      delayed_job (>= 3.0, < 5)`

Here's my error message. I've got hundreds of like this:

`Mysql::Error: Deadlock found when trying to get lock; try restarting transaction: DELETE FROM delayed_jobs WHERE delayed_jobs`.`id = ?`

**Comment by jbritten** [comment]
I'm also seeing this with the same gem versions. Ever manage to resolve it?

**Comment by fa-cruzfernandez** [comment]
Does this intialization help on `config/initializers/delayed_job_config.rb`:

```
Delayed::Backend::ActiveRecord.configure do |config|
  config.reserve_sql_strategy = :default_sql
end
```

?

**Comment by fa-cruzfernandez** [comment]
Seems also related with https://github.com/collectiveidea/delayed_job_active_record/issues/63

**Comment by albus522** [comment]
Closing stale
